const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],AI=window.AI_STRATEGY,LOCAL_AI_LAB=['localhost','127.0.0.1','::1'].includes(location.hostname);
const VIEW_COLS=9,COLS=21,ROWS=14,rowWidths=[0,15,17,19,19,17,17,19,19,17,17,15,11,0],map=Array.from({length:ROWS},(_,y)=>Array.from({length:COLS},(_,x)=>{let width=rowWidths[y],left=Math.floor((COLS-width)/2);return width&&x>=left&&x<left+width?0:1}));
const BASE_TERRAIN=map.map(row=>row.slice()),TIDAL_CELLS=[];
for(let y=1;y<ROWS-1;y++)for(let x=1;x<COLS-1;x++)if(!BASE_TERRAIN[y][x]&&[[1,0],[-1,0],[0,1],[0,-1]].some(([dx,dy])=>BASE_TERRAIN[y+dy][x+dx]))TIDAL_CELLS.push({x,y});
const defs={wood:['木头','🪵'],grass:['草','🌿'],berry:['浆果','🫐'],fish:['生鱼','🐟'],carcass:['动物肉','🥩'],meal:['熟食','🍲'],warmCoat:['保暖衣','🧥'],coolClothes:['凉爽衣','👕'],spear:['木矛','🗡️'],strongSpear:['加固长矛','🔱'],hunterSpear:['猎兽矛','⚔️'],rod:['鱼竿','🎣'],trap:['陷阱','⌗'],fence:['木围栏','▥'],door:['木门','▯'],kitchen:['野外厨房','♨'],fridge:['木冰箱','🧊'],bed:['木床','🛏️'],shelter:['简易棚屋','⌂'],strongShelter:['加固庇护所','🏠']};
Object.assign(defs,{bridge:['木桥','🌉'],boat:['木船','🛶']});
const INITIAL_OBJECTS=[{x:3,y:2,type:'wood'},{x:5,y:2,type:'grass'},{x:6,y:3,type:'berry'},{x:2,y:4,type:'grass'},{x:5,y:4,type:'wood'},{x:6,y:5,type:'grass'},{x:3,y:7,type:'berry'},{x:5,y:7,type:'wood'},{x:6,y:8,type:'grass'},{x:2,y:8,type:'wood'},{x:4,y:9,type:'wood'},{x:5,y:9,type:'grass'}].map(a=>({...a,x:a.x+6}));
let objects=INITIAL_OBJECTS.map(a=>({...a})),structures=[],enemies=[],drops=[];
let p={x:10,y:6,px:10,py:6,path:[],health:100,hunger:80,tile:40,ox:0,oy:0},cameraX=6,inv=Object.fromEntries(Object.keys(defs).map(k=>[k,0]));
const BATCH_SPEED=80;
let lastBatchProgressDay=-1;
let selected=null,mode='hand',started=false,paused=false,aiOn=false,time=0,last=performance.now(),day=1,lastSpoilDay=1,weather='晴朗',tide='退潮',lastBridgeDamageDay=0,enemyClock=0,weatherClock=0,aiClock=0,resourceClock=0,gameLogs=[],batchLeft=0,runEnding=false,recommendedStrategy=null,recommendationMode='test',runStats={kills:0,meals:0,damage:{enemy:0,weather:0,hunger:0},lastDamageSource:null,minHealth:100,minHunger:80};
let playerAttackUntil=0,playerAttackTarget=null,playerHitUntil=0,combatFx=[];
const SIM_STEP=50;let simAccumulator=0;
let evolution=null;
function randomWorldProfile(){let roll=()=>Number((.85+Math.random()*.3).toFixed(2)),names=['丰饶但危险','灾害频繁','野兽领地','资源稀疏','气候温和'];return{name:names[Math.floor(Math.random()*names.length)],resource:roll(),enemy:roll(),disaster:roll(),yieldBonus:Math.random()<.35?1:0}}
let worldProfile=randomWorldProfile(),dailyEvent='平静';
const SEASONS=[{name:'春',weather:[['晴朗',0],['小雨',0],['暴雨',1],['多云',0]],resources:[.4,.35]},{name:'夏',weather:[['炎热',1],['晴朗',0],['雷雨',1],['多云',0]],resources:[.32,.3]},{name:'秋',weather:[['晴朗',0],['秋雨',1],['大风',1],['多云',0]],resources:[.48,.34]},{name:'冬',weather:[['严寒',2],['寒风',1],['降雪',1],['晴朗',1]],resources:[.58,.32]}];
const weatherList=SEASONS.flatMap(s=>s.weather);
function seasonInfo(){return SEASONS[Math.floor((day-1)/7)%SEASONS.length]}
function worldEra(){return Math.floor((day-1)/7)}
function weatherInfo(){let base=seasonInfo().weather.find(a=>a[0]===weather)||[weather,0],escalation=Math.floor(worldEra()/2),eventBonus=dailyEvent==='灾害预警'?1:0,worldBonus=worldProfile.disaster>1.05?1:0;return[base[0],base[1]?base[1]+escalation+eventBonus+worldBonus:0]}
const ANIMALS={boar:{name:'野猪',rank:'普通',color:'#76523f',hp:50,damage:8,meat:2,unlock:1,tier:1,seasons:['春','夏','秋']},wildDog:{name:'荒岛野犬',rank:'危险',color:'#8a6b46',hp:68,damage:11,meat:2,unlock:4,tier:2,seasons:['春','夏','秋','冬']},wolf:{name:'灰狼',rank:'精英',color:'#59636a',hp:95,damage:15,meat:3,unlock:8,tier:3,seasons:['秋','冬']},bear:{name:'棕熊',rank:'小型Boss',color:'#4b3327',hp:155,damage:21,meat:5,unlock:14,tier:4,seasons:['夏','秋']},tiger:{name:'猛虎',rank:'大型Boss',color:'#b66b2d',hp:225,damage:29,meat:7,unlock:20,tier:5,seasons:['春','夏','秋']}};
const BASE={x:10,y:6},BASE_PLAN=[];for(let y=4;y<=8;y++)for(let x=8;x<=12;x++)if(x===8||x===12||y===4||y===8)BASE_PLAN.push({x,y,type:x===10&&y===8?'door':'fence'});
const recipes=[{id:'warmCoat',name:'保暖衣',desc:'冬季与寒冷天气保暖',cost:{grass:7,carcass:2},cat:'clothing'},{id:'coolClothes',name:'凉爽衣',desc:'夏季与炎热天气降温',cost:{grass:8},cat:'clothing'},{id:'spear',name:'木矛',desc:'基础武器，攻击伤害 40',cost:{wood:3,grass:2},cat:'weapon'},{id:'strongSpear',name:'加固长矛',desc:'替换木矛，攻击伤害 65',cost:{spear:1,wood:5,grass:2},cat:'weapon'},{id:'hunterSpear',name:'猎兽矛',desc:'替换长矛，攻击伤害 95',cost:{strongSpear:1,wood:8,grass:4},cat:'weapon'},{id:'trap',name:'简易陷阱',desc:'自动重伤踩中的动物',cost:{wood:2,grass:3},place:1,cat:'defense'},{id:'rod',name:'粗制鱼竿',desc:'站在岸边点击水面钓鱼',cost:{wood:3,grass:2},cat:'tool'},{id:'fence',name:'简易木栏',desc:'1级耐久40；点击可升级替换',cost:{wood:2},place:1,cat:'defense'},{id:'door',name:'木门',desc:'与围栏一起封闭小屋，可通行',cost:{wood:2,grass:1},place:1,cat:'defense'},{id:'kitchen',name:'野外厨房',desc:'生鱼和动物肉只能在这里烹饪',cost:{wood:4,grass:2},place:1,cat:'facility'},{id:'fridge',name:'木冰箱',desc:'无电保鲜箱，防止生鲜每日腐坏',cost:{wood:6,grass:3},place:1,cat:'facility'},{id:'bed',name:'木床',desc:'靠近后睡觉，恢复30点健康',cost:{wood:5,grass:4},place:1,cat:'facility'},{id:'shelter',name:'简易棚屋',desc:'天气防护1',cost:{wood:6,grass:5},place:1,cat:'defense'},{id:'strongShelter',name:'加固庇护所',desc:'天气防护2',cost:{wood:10,grass:6},place:1,cat:'defense'}];
recipes.push({id:'bridge',name:'木桥',desc:'铺在水面或潮汐浅滩上；涨潮可通行，但会持续损耗',cost:{wood:5,grass:2},place:1,cat:'tool'},{id:'boat',name:'木船',desc:'第15天解锁，之后可以直接在水面航行',cost:{wood:12,grass:6},unlock:15,cat:'tool'});
function resize(){let r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio,2);canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);p.tile=Math.floor(Math.min(r.width/VIEW_COLS,r.height/ROWS));p.ox=Math.floor((r.width-p.tile*VIEW_COLS)/2);p.oy=Math.floor((r.height-p.tile*ROWS)/2)}
function updateCamera(){let target=Math.max(0,Math.min(COLS-VIEW_COLS,p.px-Math.floor(VIEW_COLS/2)));cameraX+=Math.max(-.22,Math.min(.22,target-cameraX));if(Math.abs(target-cameraX)<.01)cameraX=target}
function tileXY(x,y){return[p.ox+(x-cameraX)*p.tile,p.oy+y*p.tile]}
function growthInfo(a){let age=Math.max(0,time-(a.born||0));if(a.type==='wood'){if(age>=60000)return{name:'成熟树',icon:'🌳',yield:7,stage:3,next:0};if(age>=35000)return{name:'小树',icon:'🌲',yield:4,stage:2,next:60000-age};if(age>=15000)return{name:'小树苗',icon:'🌱',yield:2,stage:1,next:35000-age};return{name:'断枝',icon:'🪵',yield:1,stage:0,next:15000-age}}if(a.type==='grass'){if(age>=50000)return{name:'茂盛草丛',icon:'🌾',yield:5,stage:3,next:0};if(age>=28000)return{name:'高草',icon:'🌿',yield:3,stage:2,next:50000-age};if(age>=12000)return{name:'草丛',icon:'☘️',yield:2,stage:1,next:28000-age};return{name:'嫩芽',icon:'🌱',yield:1,stage:0,next:12000-age}}return{name:defs[a.type]?.[0]||a.type,icon:defs[a.type]?.[1]||'•',yield:a.amount||1,stage:0,next:0}}
function draw(){updateCamera();let t=p.tile;ctx.fillStyle='#102119';ctx.fillRect(0,0,canvas.clientWidth,canvas.clientHeight);for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++){let[X,Y]=tileXY(x,y);if(X+t<0||X>canvas.clientWidth)continue;ctx.fillStyle=map[y][x]?((x+y)%2?'#245769':'#286174'):((x+y)%2?'#476a45':'#426341');ctx.fillRect(X,Y,t,t);if(map[y][x]){ctx.fillStyle='#78b5ad66';ctx.fillRect(X+(time/90+x*7)%Math.max(8,t-8),Y+t*.35,8,2)}else{ctx.fillStyle='#6f925c';ctx.fillRect(X+7+(x*5+y*3)%12,Y+8+(x*3)%17,2,4)}ctx.strokeStyle='#203a2d';ctx.strokeRect(X+.5,Y+.5,t-1,t-1)}
 if(selected){let[X,Y]=tileXY(selected.x,selected.y);ctx.strokeStyle='#f2c96b';ctx.lineWidth=2;ctx.strokeRect(X+2,Y+2,t-4,t-4);ctx.lineWidth=1}structures.forEach(drawStructure);[...objects,...drops].forEach(drawItem);enemies.forEach(drawEnemy);drawPlayer();drawCombatFx();if(weather==='暴雨'){ctx.strokeStyle='#c3e0e477';for(let i=0;i<18;i++){let x=(i*47+time*.13)%canvas.clientWidth,y=(i*71+time*.21)%canvas.clientHeight;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-5,y+12);ctx.stroke()}}}
function drawItem(a){let[X,Y]=tileXY(a.x,a.y),t=p.tile,g=growthInfo(a);ctx.font=`${t*(g.stage>=2?.68:.52)}px sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(g.icon,X+t/2,Y+t*.5);if(['wood','grass'].includes(a.type)){ctx.fillStyle='#101812aa';ctx.fillRect(X+t*.18,Y+t*.84,t*.64,3);ctx.fillStyle=['#8da565','#a9ba69','#d0b85c','#e1c067'][g.stage];ctx.fillRect(X+t*.18,Y+t*.84,t*.64*((g.stage+1)/4),3)}}
function drawStructure(a){let[X,Y]=tileXY(a.x,a.y),t=p.tile;ctx.save();ctx.translate(X,Y);if(['fridge','bed'].includes(a.type)){ctx.font=`${t*.62}px sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(defs[a.type][1],t*.5,t*.5)}else if(a.type==='fence'){ctx.fillStyle=['#8a6138','#a87842','#65716a'][(a.level||1)-1];ctx.fillRect(t*.1,t*.3,t*.8,t*.13);ctx.fillRect(t*.1,t*.64,t*.8,t*.13);for(let i=0;i<3;i++)ctx.fillRect(t*(.15+i*.31),t*.13,t*.13,t*.72)}else if(a.type==='door'){ctx.fillStyle=['#ad7a42','#bc8b53','#68756c'][(a.level||1)-1];ctx.fillRect(t*.2,t*.12,t*.6,t*.76);ctx.fillStyle='#201811';ctx.fillRect(t*.64,t*.48,4,4)}else if(a.type==='trap'){ctx.strokeStyle='#dec477';ctx.lineWidth=3;ctx.strokeRect(t*.2,t*.2,t*.6,t*.6);ctx.beginPath();ctx.moveTo(t*.2,t*.2);ctx.lineTo(t*.8,t*.8);ctx.moveTo(t*.8,t*.2);ctx.lineTo(t*.2,t*.8);ctx.stroke()}else{ctx.fillStyle=a.type==='kitchen'?'#584638':a.type==='strongShelter'?'#53635a':'#795535';ctx.fillRect(t*.12,t*.35,t*.76,t*.52);ctx.fillStyle=a.type==='kitchen'?'#e27443':a.type==='strongShelter'?'#aeb7a9':'#c79a5d';ctx.fillRect(t*.28,t*.17,t*.44,t*.3);ctx.fillStyle='#251a14';ctx.fillRect(t*.42,t*.57,t*.18,t*.3)}ctx.restore()}
const landStructureDraw=drawStructure;
drawStructure=function(a){if(a.type!=='bridge')return landStructureDraw(a);let[X,Y]=tileXY(a.x,a.y),t=p.tile;ctx.save();ctx.translate(X,Y);ctx.fillStyle='#5e3f28';for(let i=0;i<4;i++)ctx.fillRect(t*.08,t*(.14+i*.21),t*.84,t*.13);ctx.fillStyle='#c59655';ctx.fillRect(t*.12,t*.08,t*.12,t*.84);ctx.fillRect(t*.76,t*.08,t*.12,t*.84);ctx.fillStyle='#241912';ctx.fillRect(t*.12,t*.08,t*.76,3);ctx.fillStyle='#101812aa';ctx.fillRect(t*.14,t*.91,t*.72,3);ctx.fillStyle='#7fc26b';ctx.fillRect(t*.14,t*.91,t*.72*Math.max(0,a.hp)/(a.maxHp||100),3);ctx.restore()};
function drawEnemy(e){let[X,Y]=tileXY(e.x,e.y),t=p.tile,a=ANIMALS[e.kind]||ANIMALS.boar,now=performance.now();if(e.attackUntil>now){let pulse=Math.sin((e.attackUntil-now)/230*Math.PI),dx=p.px-e.x,dy=p.py-e.y;X+=dx*t*.22*pulse;Y+=dy*t*.22*pulse}if(e.hit&&Math.floor(now/45)%2){X+=Math.random()*4-2;Y+=Math.random()*4-2}if(a.tier>=4){ctx.strokeStyle=a.tier===5?'#ff9f43':'#d9b46c';ctx.lineWidth=2;ctx.strokeRect(X+t*.1,Y+t*.17,t*.8,t*.68)}ctx.fillStyle=e.hit?'#f4d6b0':a.color;ctx.fillRect(X+t*.18,Y+t*.4,t*.64,t*.34);ctx.fillRect(X+t*.56,Y+t*.23,t*.31,t*.3);ctx.fillStyle='#211512';ctx.fillRect(X+t*.7,Y+t*.31,3,3);ctx.fillStyle='#39201b';ctx.fillRect(X+t*.16,Y+t*.12,t*.58,4);ctx.fillStyle='#66ad63';ctx.fillRect(X+t*.16,Y+t*.12,t*.58*Math.max(0,e.hp)/(e.maxHp||50),4);ctx.font=`bold ${Math.max(7,t*.18)}px sans-serif`;ctx.textAlign='center';ctx.fillStyle=a.tier>=4?'#ffd27a':'#d8dfd8';ctx.fillText(a.name,X+t*.5,Y+t*.94)}
function drawPlayer(){let[X,Y]=tileXY(p.px,p.py),t=p.tile,b=p.path.length?Math.sin(time/80)*2:0,now=performance.now(),swing=0;if(playerAttackUntil>now&&playerAttackTarget){let pulse=Math.sin((playerAttackUntil-now)/260*Math.PI),dx=playerAttackTarget.x-p.px,dy=playerAttackTarget.y-p.py;X+=dx*t*.2*pulse;Y+=dy*t*.2*pulse;swing=pulse}if(playerHitUntil>now){X+=Math.random()*5-2.5;Y+=Math.random()*5-2.5}Y+=b;ctx.fillStyle='#111b16aa';ctx.beginPath();ctx.ellipse(X+t*.5,Y+t*.82,t*.25,t*.1,0,0,7);ctx.fill();ctx.fillStyle=playerHitUntil>now?'#d66a58':'#283c32';ctx.fillRect(X+t*.3,Y+t*.48,t*.4,t*.36);ctx.fillStyle='#d5a06e';ctx.fillRect(X+t*.31,Y+t*.18,t*.38,t*.34);ctx.fillStyle='#3b2921';ctx.fillRect(X+t*.27,Y+t*.12,t*.46,t*.16);ctx.fillStyle='#171c19';ctx.fillRect(X+t*.4,Y+t*.3,3,3);ctx.fillRect(X+t*.59,Y+t*.3,3,3);if(swing){ctx.save();ctx.translate(X+t*.65,Y+t*.48);ctx.rotate(-1+swing*2);ctx.font=`${t*.45}px sans-serif`;ctx.fillText(weaponInfo().icon,0,0);ctx.restore()}}
function addCombatFx(x,y,text,color='#fff0a6'){if(batchLeft)return;combatFx.push({x,y,text,color,born:performance.now()})}
function drawCombatFx(){let now=performance.now();combatFx=combatFx.filter(f=>now-f.born<700);for(let f of combatFx){let age=(now-f.born)/700,[X,Y]=tileXY(f.x,f.y);ctx.globalAlpha=1-age;ctx.fillStyle=f.color;ctx.font=`bold ${Math.max(13,p.tile*.34)}px sans-serif`;ctx.textAlign='center';ctx.strokeStyle='#24130e';ctx.lineWidth=3;ctx.strokeText(f.text,X+p.tile*.5,Y+p.tile*(.25-age*.45));ctx.fillText(f.text,X+p.tile*.5,Y+p.tile*(.25-age*.45));ctx.globalAlpha=1}}
function itemAt(x,y){return objects.concat(drops).some(a=>a.x===x&&a.y===y)}
function occupied(x,y,animal=false){if(x<0||y<0||x>=COLS||y>=ROWS||map[y][x])return true;if(structures.some(a=>a.x===x&&a.y===y&&a.type!=='trap'&&!(a.type==='door'&&!animal)))return true;return !animal&&enemies.some(a=>a.x===x&&a.y===y)}
occupied=function(x,y,animal=false){if(x<0||y<0||x>=COLS||y>=ROWS)return true;let bridge=structures.some(a=>a.x===x&&a.y===y&&a.type==='bridge');if(map[y][x]&&!bridge&&(animal||!inv.boat))return true;if(structures.some(a=>a.x===x&&a.y===y&&!['trap','bridge'].includes(a.type)&&!(a.type==='door'&&!animal)))return true;return !animal&&enemies.some(a=>a.x===x&&a.y===y)};
function pathfind(tx,ty,animal=false,start={x:p.x,y:p.y}){let q=[start],seen=new Map([[`${start.x},${start.y}`,null]]),end;while(q.length){let a=q.shift();if(a.x===tx&&a.y===ty){end=a;break}for(let[dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){let n={x:a.x+dx,y:a.y+dy},k=`${n.x},${n.y}`;if(!seen.has(k)&&(!occupied(n.x,n.y,animal)||(n.x===tx&&n.y===ty))){seen.set(k,a);q.push(n)}}}if(!end)return null;let out=[];while(end.x!==start.x||end.y!==start.y){out.unshift(end);end=seen.get(`${end.x},${end.y}`)}return out}
function nextTo(x,y){let best=[[1,0],[-1,0],[0,1],[0,-1]].map(([dx,dy])=>({x:x+dx,y:y+dy})).filter(a=>!occupied(a.x,a.y)).map(a=>({a,path:pathfind(a.x,a.y)})).filter(a=>a.path).sort((a,b)=>a.path.length-b.path.length)[0];if(best)p.path=best.path;else if(aiOn)logEvent(`AI跳过无法到达的目标 ${x},${y}`,'ai');else toast('无法靠近目标')}
function tap(e){if(!started||p.health<=0)return;let r=canvas.getBoundingClientRect(),x=Math.floor((e.clientX-r.left-p.ox)/p.tile+cameraX),y=Math.floor((e.clientY-r.top-p.oy)/p.tile);if(x<0||y<0||x>=COLS||y>=ROWS)return;selected={x,y};showDismantle(null);if(['trap','fence','door','kitchen','fridge','bed','shelter','strongShelter'].includes(mode)){place(x,y);return}let foe=enemies.find(a=>a.x===x&&a.y===y);if(foe){Math.abs(p.x-x)+Math.abs(p.y-y)===1?attack(foe):nextTo(x,y);return}let item=objects.concat(drops).find(a=>a.x===x&&a.y===y);if(item){Math.abs(p.x-x)+Math.abs(p.y-y)===1?pickupPrompt(item):nextTo(x,y);return}let build=structures.find(a=>a.x===x&&a.y===y);if(build&&Math.abs(p.x-x)+Math.abs(p.y-y)===1){if(build.type==='kitchen')kitchenPrompt(build);else if(build.type==='bed')bedPrompt(build);else if(['fence','door'].includes(build.type))fencePrompt(build);else buildingPrompt(build);return}hideAction();if(map[y][x]){if(inv.rod&&Math.abs(p.x-x)+Math.abs(p.y-y)===1)fish();else toast(inv.rod?'请先站到岸边':'水里不能走，需要鱼竿');return}let path=pathfind(x,y);if(path)p.path=path;else toast('那里过不去')}
function pickupPrompt(a){let g=growthInfo(a),growing=['wood','grass'].includes(a.type);$('#actionIcon').textContent=g.icon;$('#actionTitle').textContent=`采集${g.name}`;$('#actionText').textContent=a.type==='carcass'?'必须在厨房烹饪':growing?(g.next?`现在获得 ${g.yield} 份；继续生长会增产`:`已经成熟，可获得 ${g.yield} 份`):'收入背包';$('#actionButton').textContent='采集';$('#actionButton').disabled=false;$('#actionButton').onclick=()=>pickup(a);$('#actionPrompt').classList.remove('hidden')}
function pickup(a){let pool=objects.includes(a)?objects:drops,g=growthInfo(a),bonus=['wood','grass'].includes(a.type)?Math.floor(worldEra()/2)+(worldProfile.yieldBonus||0)+(dailyEvent==='丰收'?2:0):0,total=g.yield+bonus;pool.splice(pool.indexOf(a),1);inv[a.type]+=total;toast(`采集 ${g.icon} ${g.name}，获得${defs[a.type][0]} ×${total}${bonus?`（世界进程 +${bonus}）`:''}`);hideAction();updateUI();save()}
function kitchenPrompt(build){let n=inv.fish+inv.carcass;$('#actionIcon').textContent='♨';$('#actionTitle').textContent='野外厨房';$('#actionText').textContent=n?`可烹饪 ${n} 份食材`:'没有生鱼或动物肉';$('#actionButton').textContent='烹饪';$('#actionButton').disabled=!n;$('#actionButton').onclick=cook;showDismantle(build);$('#actionPrompt').classList.remove('hidden')}
function cook(){let n=inv.fish+inv.carcass;if(!n)return;inv.meal+=n;inv.fish=inv.carcass=0;toast(`得到熟食 ×${n}`);kitchenPrompt();updateUI();save()}
function bedPrompt(build){$('#actionIcon').textContent='🛏️';$('#actionTitle').textContent='木床';$('#actionText').textContent=p.health>=100?'健康已经全满':'睡觉恢复 30 点健康';$('#actionButton').textContent='睡觉';$('#actionButton').disabled=p.health>=100;$('#actionButton').onclick=sleep;showDismantle(build);$('#actionPrompt').classList.remove('hidden')}
function sleep(){p.health=Math.min(100,p.health+30);p.hunger=Math.max(0,p.hunger-8);toast('休息完成：健康 +30，饥饿 -8');hideAction();save()}
function wallName(wall,level=wall.level||1){let names=wall.type==='door'?['简易木门','加固木门','强化木门']:['简易木栏','加固木栏','强化护栏'];return names[level-1]}
function fencePrompt(wall){let level=wall.level||1,cost={wood:level+2,grass:1},can=level<3&&inv.wood>=cost.wood&&inv.grass>=cost.grass;$('#actionIcon').textContent=wall.type==='door'?'▯':'▥';$('#actionTitle').textContent=`${wallName(wall)} · ${level}级`;$('#actionText').textContent=level>=3?`最高等级 · 耐久 ${Math.ceil(wall.hp)}/${wall.maxHp}`:`点击升级后直接替换为${wallName(wall,level+1)} · 需要木头 ${cost.wood}、草 1 · 当前耐久 ${Math.ceil(wall.hp)}/${wall.maxHp}`;$('#actionButton').textContent=level>=3?'已满级':'升级替换';$('#actionButton').disabled=!can;$('#actionButton').onclick=()=>upgradeWall(wall);showDismantle(wall);$('#actionPrompt').classList.remove('hidden')}
function upgradeWall(wall){let level=wall.level||1;if(level>=3)return;let wood=level+2;if(inv.wood<wood||inv.grass<1)return;inv.wood-=wood;inv.grass--;wall.level=level+1;wall.maxHp=[80,200,400][level];wall.hp=wall.maxHp;toast(`已替换为${wallName(wall)}，房屋防护 ${wall.level}，耐久 ${wall.maxHp}`);hideAction();updateUI();save()}
function spoilRawFood(){if(structures.some(a=>a.type==='fridge'))return;let lost=0;for(let type of ['fish','carcass'])if(inv[type]>0){inv[type]--;lost++}if(lost)toast(`没有木冰箱，${lost} 份生鲜腐坏了`)}
function showDismantle(build){let b=$('#dismantleButton');b.classList.toggle('hidden',!build);if(build)b.onclick=()=>dismantle(build)}
function buildingPrompt(build){$('#actionIcon').textContent=defs[build.type]?.[1]||'⌂';$('#actionTitle').textContent=defs[build.type]?.[0]||'建筑';$('#actionText').textContent='可以拆除后重新规划或扩建';$('#actionButton').textContent='保留';$('#actionButton').disabled=false;$('#actionButton').onclick=hideAction;showDismantle(build);$('#actionPrompt').classList.remove('hidden')}
const normalBuildingPrompt=buildingPrompt;
buildingPrompt=function(build){if(build.type!=='bridge')return normalBuildingPrompt(build);let missing=Math.max(0,(build.maxHp||100)-build.hp),cost=Math.max(1,Math.ceil(missing/25)),can=missing>0&&inv.wood>=cost;$('#actionIcon').textContent='🌉';$('#actionTitle').textContent='木桥维护';$('#actionText').textContent=missing?`耐久 ${Math.ceil(build.hp)}/${build.maxHp} · 使用木头 ${cost} 完全修复`:'耐久完好；涨潮期间会逐渐损耗';$('#actionButton').textContent=missing?'维修':'无需维修';$('#actionButton').disabled=!can;$('#actionButton').onclick=()=>{inv.wood-=cost;build.hp=build.maxHp;toast('木桥已经修复');hideAction();updateUI();save()};showDismantle(build);$('#actionPrompt').classList.remove('hidden')};
function dismantle(build){let i=structures.indexOf(build);if(i<0)return;structures.splice(i,1);let recipe=recipes.find(r=>r.id===build.type);if(recipe)for(let[k,n]of Object.entries(recipe.cost))if(defs[k]&&!['spear','strongSpear'].includes(k))inv[k]+=Math.floor(n/2);toast(`拆除${defs[build.type]?.[0]||'建筑'}，返还部分材料`);hideAction();updateUI();save()}
function hideAction(){$('#actionPrompt').classList.add('hidden');showDismantle(null)}
function fish(){toast('抛下鱼线…');setTimeout(()=>{inv.fish++;toast('钓到生鱼，请带到厨房');updateUI()},1000)}
function weaponInfo(){if(inv.hunterSpear)return{name:'猎兽矛',icon:'⚔️',damage:95};if(inv.strongSpear)return{name:'加固长矛',icon:'🔱',damage:65};if(inv.spear)return{name:'木矛',icon:'🗡️',damage:40};return{name:'徒手',icon:'✊',damage:15}}
function attack(e){let animal=ANIMALS[e.kind]||ANIMALS.boar,weapon=weaponInfo();playerAttackUntil=performance.now()+260;playerAttackTarget={x:e.x,y:e.y};e.hp-=weapon.damage;e.hit=true;addCombatFx(e.x,e.y,`-${weapon.damage}`,'#ffe07b');setTimeout(()=>e.hit=false,180);toast(`${weapon.name}攻击${animal.name}，伤害 ${weapon.damage}`);if(e.hp<=0){runStats.kills++;enemies.splice(enemies.indexOf(e),1);drops.push({x:e.x,y:e.y,type:'carcass',amount:animal.meat});toast(`击败${animal.name}，掉落生肉 ×${animal.meat}`)}}
function place(x,y){if(!inv[mode])return setMode('hand');let tidal=TIDAL_CELLS.some(a=>a.x===x&&a.y===y),bridge=structures.find(a=>a.x===x&&a.y===y&&a.type==='bridge'),blocked=structures.some(a=>a.x===x&&a.y===y&&a.type!=='bridge');if(tidal&&!bridge)return toast('洪泛浅滩必须先铺木桥，建筑才能以桥面为地基');if(occupied(x,y)||itemAt(x,y)||blocked||p.x===x&&p.y===y)return toast('这里不能建造');let durability={trap:1,fence:80,door:80,kitchen:60,fridge:50,bed:45,shelter:80,strongShelter:160}[mode]||40,building={x,y,type:mode,hp:durability,maxHp:durability,bridgeFoundation:!!bridge};if(['fence','door'].includes(mode))building.level=1;structures.push(building);inv[mode]--;let protection=houseProtection();toast(protection?`房屋已封闭！抵挡动物，天气防护 ${protection}`:`已放置${defs[mode][0]}${bridge?'（桥面地基）':''}`);setMode('hand');updateUI();save()}
function houseInterior(x,y){if(map[y]?.[x])return false;let q=[{x,y}],seen=new Set([`${x},${y}`]),walls=0;while(q.length){let a=q.shift();for(let[dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){let nx=a.x+dx,ny=a.y+dy;if(nx<0||ny<0||nx>=COLS||ny>=ROWS||map[ny][nx])return false;if(structures.some(s=>s.x===nx&&s.y===ny&&['fence','door'].includes(s.type))){walls++;continue}let k=`${nx},${ny}`;if(!seen.has(k)){seen.add(k);q.push({x:nx,y:ny});if(seen.size>40)return false}}}return walls>=4&&structures.some(s=>s.type==='door')}
function spawnEnemy(){let season=seasonInfo(),spots=[];for(let y=1;y<ROWS-1;y++)for(let x=1;x<COLS-1;x++)if(!occupied(x,y,true)&&!itemAt(x,y)&&!houseInterior(x,y)&&Math.abs(x-p.x)+Math.abs(y-p.y)>5)spots.push({x,y});let maxEnemies=Math.min(9,3+worldEra()+Math.floor(day/5));if(!spots.length||enemies.length>=maxEnemies||Math.random()>Math.min(1,worldProfile.enemy+(dailyEvent==='兽潮'?.25:0)))return;let pool=Object.entries(ANIMALS).filter(([,a])=>day>=a.unlock&&a.seasons.includes(season.name)).sort((a,b)=>a[1].tier-b[1].tier);if(!pool.length)return;let chosen=Math.random()<Math.min(.85,.55+worldEra()*.05)?pool[pool.length-1]:pool[Math.floor(Math.random()*pool.length)],kind=chosen[0],animal=chosen[1],spot=spots[Math.floor(Math.random()*spots.length)],hp=Math.round((animal.hp+Math.floor((day-animal.unlock)/7)*12)*worldProfile.enemy);enemies.push({...spot,kind,hp,maxHp:hp,lastMove:time,lastAttack:0,hit:false});toast(`${animal.tier>=4?'🚨':'⚠'} ${animal.rank}·${animal.name}出现！${hp} 生命 / 攻击 ${animal.damage}`)}
function spawnResources(count=1){const MAX=20+worldEra()*2,season=seasonInfo(),rates=season.resources;if(objects.length>=MAX||Math.random()>Math.min(1,worldProfile.resource+(dailyEvent==='丰收'?.2:0)))return 0;let empty=[];for(let y=1;y<ROWS-1;y++)for(let x=1;x<COLS-1;x++)if(!map[y][x]&&!occupied(x,y)&&!itemAt(x,y)&&!houseInterior(x,y)&&!(p.x===x&&p.y===y))empty.push({x,y});let added=0;while(count--&&empty.length&&objects.length<MAX){let i=Math.floor(Math.random()*empty.length),spot=empty.splice(i,1)[0],roll=Math.random(),type=roll<rates[0]?'wood':roll<rates[0]+rates[1]?'grass':'berry';objects.push({...spot,type,born:time});added++}if(added)save();return added}
function houseProtection(){let q=[{x:p.x,y:p.y}],seen=new Set([`${p.x},${p.y}`]),boundary=[];while(q.length){let a=q.shift();for(let[dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){let x=a.x+dx,y=a.y+dy;if(x<0||y<0||x>=COLS||y>=ROWS||map[y][x])return 0;let wall=structures.find(s=>s.x===x&&s.y===y&&['fence','door'].includes(s.type));if(wall){boundary.push(wall);continue}let k=`${x},${y}`;if(!seen.has(k)){seen.add(k);q.push({x,y});if(seen.size>40)return 0}}}return boundary.some(s=>s.type==='door')&&boundary.length>=4?Math.min(...boundary.map(s=>s.level||1)):0}
function enclosedByFence(){return houseProtection()>0}
function weatherProtection(){let strength=houseProtection();if(structures.some(a=>a.type==='shelter'&&Math.abs(a.x-p.x)+Math.abs(a.y-p.y)<=1))strength=Math.max(strength,1);if(structures.some(a=>a.type==='strongShelter'&&Math.abs(a.x-p.x)+Math.abs(a.y-p.y)<=1))strength=Math.max(strength,2);return strength}
function enemyAI(){for(let e of [...enemies]){if(time-e.lastMove<750)continue;e.lastMove=time;let animal=ANIMALS[e.kind]||ANIMALS.boar,d=Math.abs(e.x-p.x)+Math.abs(e.y-p.y);if(d===1){if(time-e.lastAttack>1200){let hit=animal.damage+Math.floor((day-animal.unlock)/4)*2;e.lastAttack=time;p.health=Math.max(0,p.health-hit);runStats.damage.enemy+=hit;runStats.lastDamageSource='enemy';toast(`${animal.name}攻击！健康 -${hit}`)}continue}let path=pathfind(p.x,p.y,true,{x:e.x,y:e.y});if(!path?.length){let targets=structures.filter(s=>s.type!=='trap').map(s=>({s,path:pathfind(s.x,s.y,true,{x:e.x,y:e.y})})).filter(a=>a.path?.length).sort((a,b)=>a.path.length-b.path.length),target=targets[0];if(!target)continue;if(target.path.length===1){let building=target.s;building.maxHp=building.maxHp||(['fence','door'].includes(building.type)?40:60);building.hp=(building.hp??building.maxHp)-animal.damage;toast(`${animal.name}攻击${defs[building.type][0]}，耐久 -${animal.damage}`);if(building.hp<=0){structures.splice(structures.indexOf(building),1);toast(`${defs[building.type][0]}被摧毁！`)}continue}path=target.path}let n=path[0];if(n.x===p.x&&n.y===p.y)continue;e.x=n.x;e.y=n.y;let trap=structures.find(a=>a.x===e.x&&a.y===e.y&&a.type==='trap');if(trap){structures.splice(structures.indexOf(trap),1);e.hp-=50;toast(`陷阱命中${animal.name}，生命 -50！`);if(e.hp<=0){runStats.kills++;enemies.splice(enemies.indexOf(e),1);drops.push({x:e.x,y:e.y,type:'carcass',amount:animal.meat});toast(`${animal.name}被陷阱击败，掉落生肉 ×${animal.meat}`)}}}}
function clothingProtection(){let s=seasonInfo().name;if(s==='冬'||['严寒','寒风','降雪'].includes(weather))return inv.warmCoat?1:0;if(s==='夏'||weather==='炎热')return inv.coolClothes?1:0;return 1}
function simulateStep(dt){if(!started||p.health<=0)return;time+=dt;p.hunger=Math.max(0,p.hunger-dt*.00055);if(!p.hunger){let loss=dt*.001;p.health=Math.max(0,p.health-loss);runStats.damage.hunger+=loss;runStats.lastDamageSource='hunger'}let d=Math.floor(time/60000)+1;if(d!==day){let oldSeason=seasonInfo().name;day=d;let season=seasonInfo();weather=season.weather[Math.floor(Math.random()*season.weather.length)][0];let grown=spawnResources(4);toast(`${season.name} · 第 ${day} 天：${weather}，新生物资 ${grown} 份${oldSeason!==season.name?'，新季节开始':''}`)}resourceClock+=dt;while(resourceClock>=8000){resourceClock-=8000;spawnResources(1)}let severity=weatherInfo()[1],weatherDamage=Math.max(0,severity-weatherProtection()),clothingDamage=clothingProtection()?0:1,damage=weatherDamage+clothingDamage;if(damage){weatherClock+=dt;while(weatherClock>=2500){weatherClock-=2500;p.health=Math.max(0,p.health-damage);runStats.damage.weather+=damage;runStats.lastDamageSource='weather';toast(`${weather}与${seasonInfo().name}季环境伤害 ${damage}（建筑防护 ${weatherProtection()}，衣物 ${clothingProtection()?'合适':'不合适'}）`)}}else weatherClock=0;enemyClock+=dt;while(enemyClock>=12000){enemyClock-=12000;if(Math.random()<.75)spawnEnemy()}aiClock+=dt;while(aiOn&&aiClock>=650){aiClock-=650;aiStep()}enemyAI();if(p.path.length){let n=p.path[0],speed=dt*.006,dist=Math.hypot(n.x-p.px,n.y-p.py);if(dist<=speed){p.px=p.x=n.x;p.py=p.y=n.y;p.path.shift()}else{p.px+=(n.x-p.px)/dist*speed;p.py+=(n.y-p.py)/dist*speed}}runStats.minHealth=Math.min(runStats.minHealth,p.health);runStats.minHunger=Math.min(runStats.minHunger,p.hunger);updateStats()}
const baseSimulateStep=simulateStep;
function floodUnprotectedTiles(){let tidal=new Set(TIDAL_CELLS.map(a=>`${a.x},${a.y}`)),bridged=new Set(structures.filter(a=>a.type==='bridge').map(a=>`${a.x},${a.y}`)),lostBuildings=structures.filter(a=>a.type!=='bridge'&&tidal.has(`${a.x},${a.y}`)&&!bridged.has(`${a.x},${a.y}`));for(let a of lostBuildings)structures.splice(structures.indexOf(a),1);let before=objects.length+drops.length;objects=objects.filter(a=>!tidal.has(`${a.x},${a.y}`)||bridged.has(`${a.x},${a.y}`));drops=drops.filter(a=>!tidal.has(`${a.x},${a.y}`)||bridged.has(`${a.x},${a.y}`));let lostItems=before-objects.length-drops.length;if(lostBuildings.length||lostItems)toast(`洪水摧毁：未架桥建筑 ${lostBuildings.length} 座，地面物资 ${lostItems} 份`)}
function damageBridgesForDay(){if(tide!=='涨潮'||lastBridgeDamageDay===day)return;lastBridgeDamageDay=day;let collapsed=[];for(let bridge of structures.filter(a=>a.type==='bridge')){bridge.hp-=15;if(bridge.hp<=0)collapsed.push({x:bridge.x,y:bridge.y})}if(collapsed.length){let keys=new Set(collapsed.map(a=>`${a.x},${a.y}`));structures=structures.filter(a=>!keys.has(`${a.x},${a.y}`));objects=objects.filter(a=>!keys.has(`${a.x},${a.y}`));drops=drops.filter(a=>!keys.has(`${a.x},${a.y}`));toast(`${collapsed.length} 座失修木桥连同桥面建筑和物资被冲垮！`)}else if(structures.some(a=>a.type==='bridge'))toast('涨潮日结算：木桥耐久 -15')}
function updateTide(){let weekDay=(day-1)%7+1,next=weekDay===5||weekDay===6?'涨潮':'退潮';if(next!==tide){tide=next;for(let a of TIDAL_CELLS)map[a.y][a.x]=tide==='涨潮'?1:BASE_TERRAIN[a.y][a.x];p.path=[];if(tide==='涨潮'){floodUnprotectedTiles();toast('🌊 周期涨潮！第5—6天浅滩被淹；无桥建筑和物资会被摧毁')}else toast('🏝 第7天退潮！沿岸浅滩重新露出')}damageBridgesForDay()}
function strandedByTide(){return !!map[p.y]?.[p.x]&&!inv.boat&&!structureAt(p.x,p.y,'bridge')}
simulateStep=function(dt){let previousTime=time,heldAI=aiOn;if(strandedByTide()){p.path=[];aiOn=false}baseSimulateStep(dt);aiOn=heldAI;if(!started)return;updateTide();if(Math.floor(previousTime/12000)!==Math.floor(time/12000))spawnResources(1)};
function animate(now){let elapsed=Math.min(100,now-last);last=now;if(!paused||batchLeft)simAccumulator+=elapsed*(batchLeft?BATCH_SPEED:1);let steps=0;while(simAccumulator>=SIM_STEP&&steps<200){simulateStep(SIM_STEP);simAccumulator-=SIM_STEP;steps++}if(!batchLeft)draw();requestAnimationFrame(animate)}
function rollDailyEvent(){let events=['平静','平静','丰收','兽潮','灾害预警'];dailyEvent=events[Math.floor(Math.random()*events.length)];logEvent(`今日世界事件：${dailyEvent}`,'info')}
function gameSnapshot(){return JSON.parse(JSON.stringify({day,time,weather,dailyEvent,worldProfile,objects,structures,enemies,drops,inv,p:{x:p.x,y:p.y,px:p.x,py:p.y,health:p.health,hunger:p.hunger},runStats}))}
function saveCheckpoint(){if(batchLeft||(day!==1&&(day-1)%3!==0))return;let list=JSON.parse(localStorage.getItem('island-checkpoints-v1')||'[]').filter(s=>s.day!==day);list.push(gameSnapshot());localStorage.setItem('island-checkpoints-v1',JSON.stringify(list.slice(-3)))}
function checkpointCount(){return JSON.parse(localStorage.getItem('island-checkpoints-v1')||'[]').length}
function restoreCheckpoint(){let list=JSON.parse(localStorage.getItem('island-checkpoints-v1')||'[]');if(!list.length)return restartGame();let s=list[list.length-1];objects=s.objects||[];structures=s.structures||[];enemies=s.enemies||[];drops=s.drops||[];inv={...Object.fromEntries(Object.keys(defs).map(k=>[k,0])),...s.inv};worldProfile=s.worldProfile||randomWorldProfile();dailyEvent=s.dailyEvent||'平静';time=s.time;day=lastSpoilDay=s.day;weather=s.weather;p={...p,...s.p,path:[],tile:p.tile,ox:p.ox,oy:p.oy};runStats=s.runStats||{kills:0,meals:0,damage:{enemy:0,weather:0,hunger:0},lastDamageSource:null,minHealth:p.health,minHunger:p.hunger};enemyClock=weatherClock=aiClock=resourceClock=0;runEnding=false;started=true;aiOn=false;localStorage.setItem('island-checkpoints-v1',JSON.stringify([s]));$('#welcome').classList.add('closed');$('#welcome').classList.remove('gameover');$('#restartButton').classList.add('hidden');$('#clearGameButton').classList.add('hidden');updateAIButton();updateUI();save();toast(`已回到第 ${day} 天的安全存档`)}
function updateBatchProgress(force=false){let key=`${batchLeft}-${day}-${evolution?.generation||0}-${evolution?.candidate||0}`;if(!batchLeft||(!force&&lastBatchProgressDay===key))return;lastBatchProgressDay=key;let completed=10-batchLeft,current=completed+1;if(evolution){let overall=(evolution.generation-1)*60+evolution.candidate*10+completed;$('#batchProgressText').textContent=`第 ${evolution.generation} / ${evolution.maxGenerations} 代 · 候选 ${evolution.candidate+1} / ${evolution.population.length} · 本候选第 ${current} / 10 局`;$('#batchProgressBar').style.width=`${overall/3}%`}else{$('#batchProgressText').textContent=`正在模拟第 ${current} / 10 局 · 已完成 ${completed} 局`;$('#batchProgressBar').style.width=`${completed*10}%`}$('#batchProgressDay').textContent=`本局当前存活：${seasonInfo().name} · 第 ${day} 天 · 健康 ${Math.ceil(p.health)}`}
function updateStats(){if(day>lastSpoilDay){lastSpoilDay=day;rollDailyEvent();spoilRawFood();saveCheckpoint();if(!batchLeft)updateUI()}if(p.health<=0&&!runEnding)finishRun(false);if(batchLeft){updateBatchProgress();return}$('#healthBar').style.width=p.health+'%';$('#healthText').textContent=Math.ceil(p.health);$('#hungerBar').style.width=p.hunger+'%';$('#hungerText').textContent=Math.ceil(p.hunger);$('#dayLabel').textContent=`${seasonInfo().name} · 第 ${day} 天 · ${weather} · ${tide}`}
function inventoryGroup(title,keys,note=''){let filled=keys.filter(k=>inv[k]);return `<h3 style="font-size:10px;color:#d6bd7c;margin:10px 0 6px">${title}</h3><div class="inventory">${filled.length?filled.map(k=>`<div class="item"><em>${inv[k]}</em><div class="item-icon">${defs[k][1]}</div><b>${defs[k][0]}</b>${['berry','meal'].includes(k)?`<button data-eat="${k}"></button>`:''}</div>`).join(''):'<div class="item empty">暂无</div>'}</div>${note?`<p style="color:#89988e;font-size:9px">${note}</p>`:''}`}
function craftGroup(title,cat){let list=recipes.filter(r=>r.cat===cat);return `<section class="craft-group"><h3>${title}</h3>${list.map(r=>{let unlocked=!r.unlock||day>=r.unlock,can=unlocked&&Object.entries(r.cost).every(([k,n])=>inv[k]>=n);return `<div class="craft-card"><div class="craft-icon">${defs[r.id][1]}</div><div><h3>${r.name}${unlocked?'':` · 第${r.unlock}天解锁`}</h3><p>${r.desc}</p><div class="cost">${Object.entries(r.cost).map(([k,n])=>`<span class="${inv[k]>=n?'ok':''}">${defs[k][1]} ${inv[k]}/${n}</span>`).join('　')}</div></div><button data-craft="${r.id}" ${can?'':'disabled'}>${unlocked?'制作':'未解锁'}</button></div>`}).join('')}</section>`}
function updateUI(){let total=Object.values(inv).reduce((a,b)=>a+b,0),other=Object.keys(defs).filter(k=>!['berry','fish','carcass','meal'].includes(k)),weapon=weaponInfo(),hand=$('[data-slot="hand"]');$('#bagCount').textContent=`${total} / 24`;$('#itemsPanel').innerHTML=inventoryGroup('可直接食用',['berry'],'浆果无需加工。')+inventoryGroup('生鲜 · 不可直接食用',['fish','carcass'],'必须靠近厨房烹饪；没有木冰箱时每天腐坏一份。')+inventoryGroup('熟食',['meal'],'熟食可以安全食用并恢复健康。')+inventoryGroup('材料与装备',other);$('#craftPanel').innerHTML=craftGroup('🧥 衣服','clothing')+craftGroup('⚔ 武器','weapon')+craftGroup('🛠 工具','tool')+craftGroup('🛡 防御建筑','defense')+craftGroup('🏕 生活设施','facility');$('#craftBadge').textContent=recipes.filter(r=>Object.entries(r.cost).every(([k,n])=>inv[k]>=n)).length;hand.querySelector('span').textContent=weapon.icon;hand.querySelector('small').textContent=weapon.name;$$('[data-eat]').forEach(b=>b.onclick=()=>eat(b.dataset.eat));$$('[data-craft]').forEach(b=>b.onclick=()=>craft(b.dataset.craft));['rod','trap','fence'].forEach(k=>$(`[data-slot="${k}"]`).classList.toggle('locked',!inv[k]))}
function eat(type){if(!inv[type])return;inv[type]--;runStats.meals++;let gain=type==='meal'?45:12;p.hunger=Math.min(100,p.hunger+gain);if(type==='meal')p.health=Math.min(100,p.health+8);toast(`${defs[type][0]}：饱食 +${gain}`);updateUI();save()}
function craft(id){let r=recipes.find(a=>a.id===id);if(!r||(r.unlock&&day<r.unlock)||!Object.entries(r.cost).every(([k,n])=>inv[k]>=n))return;Object.entries(r.cost).forEach(([k,n])=>inv[k]-=n);inv[id]++;toast(`制作完成：${r.name}${r.place?(id==='bridge'?'，请点击水面或潮汐浅滩放置':'，请点击空地放置'):''}`);updateUI();save();if(r.place){closeBag();setMode(id);if(aiOn)aiPlace()}}
function setMode(m){if(m!=='hand'&&!inv[m])return toast(`没有${defs[m][0]}`);mode=m;$$('.quick').forEach(b=>b.classList.toggle('active',b.dataset.slot===m));hideAction();toast(m==='hand'?'攻击模式：点击相邻动物':`点击空地放置${defs[m][0]}`)}
function canCraft(id){let r=recipes.find(a=>a.id===id);return r&&Object.entries(r.cost).every(([k,n])=>inv[k]>=n)}
function nearest(list){return list.map(a=>({a,path:pathfind(a.x,a.y)})).filter(v=>v.path).map(v=>({...v,score:v.path.length-(objects.includes(v.a)?growthInfo(v.a).yield*AI.growthValueWeight:0)})).sort((a,b)=>a.score-b.score)[0]}
function structureAt(x,y,type){return structures.some(a=>a.x===x&&a.y===y&&(!type||a.type===type))}
function nextBasePart(){return BASE_PLAN.find(a=>!structureAt(a.x,a.y,a.type))}
function waterEdge(x,y){return[[1,0],[-1,0],[0,1],[0,-1]].some(([dx,dy])=>map[y+dy]?.[x+dx])}
function safeUtilitySpot(){let choices=[{x:9,y:5},{x:10,y:5},{x:11,y:5},{x:9,y:6},{x:11,y:6},{x:9,y:7},{x:10,y:7},{x:11,y:7},{x:13,y:7},{x:13,y:8}];return choices.find(a=>!occupied(a.x,a.y)&&!structureAt(a.x,a.y)&&!(p.x===a.x&&p.y===a.y)&&!waterEdge(a.x,a.y)&&!BASE_PLAN.some(b=>b.x===a.x&&b.y===a.y))}
function aiPlace(){if(mode==='trap'){let nearestEnemy=enemies.map(e=>({e,d:Math.abs(e.x-p.x)+Math.abs(e.y-p.y)})).sort((a,b)=>a.d-b.d)[0]?.e,path=nearestEnemy&&pathfind(p.x,p.y,true,{x:nearestEnemy.x,y:nearestEnemy.y}),spot=path?.find(a=>!(a.x===p.x&&a.y===p.y)&&!occupied(a.x,a.y,true)&&!structureAt(a.x,a.y));if(spot){logEvent(`AI：预测动物路线，在 ${spot.x},${spot.y} 放陷阱`,'ai');place(spot.x,spot.y);return true}}if(['fence','door'].includes(mode)){let part=nextBasePart();if(part&&part.type===mode&&!occupied(part.x,part.y)&&!structureAt(part.x,part.y)){logEvent(`AI：按基地蓝图建造 ${mode} ${part.x},${part.y}`,'ai');place(part.x,part.y);return true}}if(['kitchen','fridge','bed','shelter','strongShelter'].includes(mode)){let spot=safeUtilitySpot();if(spot){logEvent(`AI：避开水边放置${defs[mode][0]}`,'ai');place(spot.x,spot.y);return true}}setMode('hand');return false}
function aiStep(){if(p.path.length||p.health<=0)return;if(['trap','fence','door','kitchen','shelter','strongShelter'].includes(mode)&&inv[mode])return void aiPlace();let adjacent=enemies.find(e=>Math.abs(e.x-p.x)+Math.abs(e.y-p.y)===1);if(adjacent){logEvent('AI：反击近身野猪','ai');return void attack(adjacent)}if(p.hunger<AI.eatMealBelow&&inv.meal)return logEvent('AI：饥饿，食用熟食','ai'),void eat('meal');if(p.hunger<AI.eatBerryBelow&&inv.berry)return logEvent('AI：低饥饿，食用浆果','ai'),void eat('berry');let bad=weatherList.find(a=>a[0]===weather)?.[1],shelter=structures.find(a=>['shelter','strongShelter'].includes(a.type));if(bad&&shelter&&weatherProtection()<bad)return logEvent('AI：天气恶劣，前往庇护所','ai'),void nextTo(shelter.x,shelter.y);let threat=enemies.some(e=>Math.abs(e.x-p.x)+Math.abs(e.y-p.y)<=AI.trapThreatDistance);if(threat){if(inv.trap){logEvent('AI：野猪进入警戒区，准备路径陷阱','ai');setMode('trap');return}if(canCraft('trap')){logEvent('AI：优先制作反野猪陷阱','ai');craft('trap');return}}let raw=inv.fish+inv.carcass,kitchen=structures.find(a=>a.type==='kitchen');if(raw&&kitchen){if(Math.abs(kitchen.x-p.x)+Math.abs(kitchen.y-p.y)===1)return void cook();return void nextTo(kitchen.x,kitchen.y)}if(!kitchen){if(inv.kitchen)return void setMode('kitchen');if(canCraft('kitchen'))return logEvent('AI：建设食物基础设施','ai'),void craft('kitchen')}if(AI.buildShelterBeforeBase&&!structures.some(a=>a.type==='shelter')){if(inv.shelter)return void setMode('shelter');if(canCraft('shelter'))return void craft('shelter')}let part=nextBasePart();if(part){let blocker=objects.concat(drops).find(a=>a.x===part.x&&a.y===part.y);if(blocker){if(Math.abs(blocker.x-p.x)+Math.abs(blocker.y-p.y)===1)return void pickup(blocker);return void nextTo(blocker.x,blocker.y)}if(inv[part.type])return void setMode(part.type);if(canCraft(part.type))return logEvent(`AI：为封闭基地制作${defs[part.type][0]}`,'ai'),void craft(part.type)}if(!structures.some(a=>a.type==='shelter')){if(inv.shelter)return void setMode('shelter');if(canCraft('shelter'))return void craft('shelter')}let target=nearest(objects.concat(drops));if(target){if(Math.abs(target.a.x-p.x)+Math.abs(target.a.y-p.y)===1)return void pickup(target.a);return void nextTo(target.a.x,target.a.y)}if(!inv.rod&&canCraft('rod'))return void craft('rod');if(p.hunger<AI.fishBelow&&inv.rod){let shores=[];for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++)if(!map[y][x]&&[[1,0],[-1,0],[0,1],[0,-1]].some(([dx,dy])=>map[y+dy]?.[x+dx]))shores.push({x,y});let shore=nearest(shores);if(shore){if(shore.path.length===0){inv.fish++;toast('AI 钓到一条生鱼')}else p.path=shore.path}}}
const coreAiStep=aiStep;
function aiGatherMaterials(){let target=nearest(objects);if(!target)return false;if(Math.abs(target.a.x-p.x)+Math.abs(target.a.y-p.y)===1)pickup(target.a);else nextTo(target.a.x,target.a.y);return true}
aiStep=function(){if(p.path.length||p.health<=0)return;let adjacent=enemies.find(e=>Math.abs(e.x-p.x)+Math.abs(e.y-p.y)===1);if(adjacent)return void attack(adjacent);if(p.hunger<AI.eatMealBelow&&inv.meal)return void eat('meal');if(p.hunger<AI.eatBerryBelow&&inv.berry)return void eat('berry');let kitchen=structures.find(a=>a.type==='kitchen');if(!kitchen){if(inv.kitchen){setMode('kitchen');aiPlace();return}if(canCraft('kitchen')){logEvent('AI里程碑 1：优先完成厨房','ai');craft('kitchen');return}aiGatherMaterials();return}let bed=structures.find(a=>a.type==='bed');if(!bed){if(inv.bed){setMode('bed');aiPlace();return}if(canCraft('bed')){logEvent('AI里程碑 2：厨房后立即制作木床','ai');craft('bed');return}aiGatherMaterials();return}let weaponGoal=!inv.spear&&!inv.strongSpear&&!inv.hunterSpear?'spear':day>=(AI.weapon3Day||10)&&!inv.hunterSpear?'hunterSpear':day>=(AI.weapon2Day||5)&&!inv.strongSpear&&!inv.hunterSpear?'strongSpear':null;if(weaponGoal){if(canCraft(weaponGoal)){logEvent(`AI武器里程碑：制作${defs[weaponGoal][0]}`,'ai');craft(weaponGoal)}else aiGatherMaterials();return}if(p.health<AI.bedHealthBelow){if(Math.abs(bed.x-p.x)+Math.abs(bed.y-p.y)===1){logEvent('AI：生命偏低，使用床休息','ai');sleep()}else nextTo(bed.x,bed.y);return}let raw=inv.fish+inv.carcass;if(raw>=2&&!structures.some(a=>a.type==='fridge')){if(inv.fridge){setMode('fridge');aiPlace();return}if(canCraft('fridge')){logEvent('AI里程碑 3：制作木冰箱保存生鲜','ai');craft('fridge');return}}let targetLevel=day>=AI.wallLevel3Day?3:day>=AI.wallLevel2Day?2:1,weakWall=structures.find(a=>['fence','door'].includes(a.type)&&(a.level||1)<targetLevel);if(weakWall){let need=(weakWall.level||1)+2;if(inv.wood>=need&&inv.grass>=1){logEvent(`AI：升级防线到 ${targetLevel} 级`,'ai');upgradeWall(weakWall)}else aiGatherMaterials();return}coreAiStep()}
const armedAiStep=aiStep;
aiStep=function(){if(!p.path.length&&p.health>0){let needed=seasonInfo().name==='冬'?'warmCoat':seasonInfo().name==='夏'?'coolClothes':null;if(needed&&!inv[needed]){if(canCraft(needed)){logEvent(`AI季节准备：制作${defs[needed][0]}`,'ai');craft(needed)}else aiGatherMaterials();return}}armedAiStep()}
function setPaused(value){paused=!!value;simAccumulator=0;document.body.classList.toggle('game-paused',paused);let b=$('#pauseButton');b.classList.toggle('on',paused);b.querySelector('span').textContent=paused?'▶':'Ⅱ';b.querySelector('b').textContent=paused?'继续':'暂停';b.querySelector('small').textContent=paused?'已暂停':'游戏中';$('#pauseOverlay').classList.toggle('hidden',!paused)}
function togglePause(){if(!started||p.health<=0||batchLeft)return;setPaused(!paused)}
function toggleAI(){aiOn=!aiOn;updateAIButton();toast(aiOn?'AI 已接管，将自动求生':'AI 已关闭，恢复手动操作')}
function updateAIButton(){let b=$('#aiButton');b.classList.toggle('on',aiOn);b.querySelector('small').textContent=aiOn?'运行中':'关闭'}
function mainDamageCause(){return Object.entries(runStats.damage).sort((a,b)=>b[1]-a[1])[0][0]}
function deathCause(){return runStats.lastDamageSource||mainDamageCause()}
function weatherDiagnosis(){let severity=weatherInfo()[1],protection=weatherProtection(),clothing=clothingProtection(),enclosed=enclosedByFence(),hasShelter=structures.some(a=>['shelter','strongShelter'].includes(a.type)),reason=!clothing?'季节衣物不合适':protection>=severity?'防护充足':!enclosed&&!hasShelter?'尚未建造房屋或庇护所':protection===0?'已有设施，但角色不在防护范围内':`防护 ${protection} 低于天气强度 ${severity}`;return{season:seasonInfo().name,weather,severity,protection,clothing,enclosed,hasShelter,reason}}
function archiveRun(success){let history=JSON.parse(localStorage.getItem('island-ai-history')||'[]'),record={at:new Date().toLocaleString(),strategyVersion:AI.version,strategy:{...AI,craftPriority:[...AI.craftPriority]},success,day,seconds:Math.floor(time/1000),cause:success?'survived':deathCause(),mainDamage:mainDamageCause(),weatherReport:weatherDiagnosis(),kills:runStats.kills,meals:runStats.meals,minHealth:Math.ceil(runStats.minHealth),minHunger:Math.ceil(runStats.minHunger),damage:Object.fromEntries(Object.entries(runStats.damage).map(([k,v])=>[k,Math.round(v)])),builds:structures.map(a=>a.type),logs:[...gameLogs]};history.unshift(record);localStorage.setItem('island-ai-history',JSON.stringify(history.slice(0,50)));renderHistory();return record}
function finishRun(success){if(runEnding)return;runEnding=true;started=false;let wasBatch=!!batchLeft,result=LOCAL_AI_LAB?archiveRun(success):{cause:deathCause()};logEvent(success?'测试达标':`本局倒下：主要原因 ${result.cause}`,'damage');if(batchLeft){batchLeft--;if(batchLeft)return void setTimeout(resetRun,10)}document.body.classList.remove('batch-running');$('#runTenButton').textContent='▶ 连续测试 10 局';if(wasBatch&&LOCAL_AI_LAB)renderStrategyReview();aiOn=false;updateAIButton();updateUI();draw();$('#welcome').classList.remove('closed');$('#welcome').classList.add('gameover');$('.modal h1').textContent=wasBatch?'10 局测试完成':success?'测试达标':'你倒下了';$('.modal>p').textContent=wasBatch?'十局高速模拟已完成，结果已汇总并生成下一版策略建议。':'本局已经结束，点击下方按钮重新开始。';$('#startButton').classList.add('hidden');if(LOCAL_AI_LAB)$('#viewDeathLog').classList.remove('hidden');$('#restartButton').classList.remove('hidden');save()}
function resetRun(){objects=INITIAL_OBJECTS.map(a=>({...a}));structures=[];enemies=[];drops=[];p={x:10,y:6,px:10,py:6,path:[],health:100,hunger:80,tile:p.tile,ox:p.ox,oy:p.oy};cameraX=6;inv=Object.fromEntries(Object.keys(defs).map(k=>[k,0]));selected=null;mode='hand';time=0;day=lastSpoilDay=1;weather='晴朗';enemyClock=weatherClock=aiClock=resourceClock=0;gameLogs=[];runStats={kills:0,meals:0,damage:{enemy:0,weather:0,hunger:0},lastDamageSource:null,minHealth:100,minHunger:80};runEnding=false;started=true;aiOn=true;$('#welcome').classList.add('closed');$('#welcome').classList.remove('gameover');$('#viewDeathLog').classList.add('hidden');$('#restartButton').classList.add('hidden');updateAIButton();updateUI();logEvent(`自动测试开始，批次剩余 ${batchLeft||1} 局`,'ai')}
function startTenRuns(){if(!LOCAL_AI_LAB)return;batchLeft=10;recommendedStrategy=null;recommendationMode='test';$('#batchProgressTitle').textContent='当前策略 · 10 局基准测试';$('#strategyReviewTitle').textContent='10 局基准评估与改进建议';document.body.classList.add('batch-running');let button=$('#applyStrategyButton');button.disabled=false;button.dataset.applied='';button.textContent='应用推荐策略并更新文件';$('#strategyReview').classList.add('hidden');logEvent(`启动策略 v${AI.version} 的无渲染高速 10 局测试`,'ai');$('#logPanel').classList.remove('open');$('#scrim').classList.remove('open');resetRun()}
function renderHistory(){let history=JSON.parse(localStorage.getItem('island-ai-history')||'[]'),last=history.slice(0,10);if(!last.length){$('#runSummary').textContent='尚无历史测试结果';return}let days=last.map(a=>a.day).sort((a,b)=>a-b),avg=(days.reduce((a,b)=>a+b,0)/days.length).toFixed(1),median=days[Math.floor(days.length/2)],causes={enemy:0,weather:0,hunger:0};last.forEach(a=>causes[a.cause]=(causes[a.cause]||0)+1);let names={enemy:'动物',weather:'天气',hunger:'饥饿'},top=Object.entries(causes).sort((a,b)=>b[1]-a[1])[0],version=last[0].strategyVersion||'旧版';$('#runSummary').textContent=`策略 v${version} · ${last.length} 局：平均 ${avg} 天 · 中位数 ${median} 天 · 最长 ${Math.max(...days)} 天 · 主要死因 ${names[top[0]]} ${top[1]} 局`}
function showLastHistory(){let last=JSON.parse(localStorage.getItem('island-ai-history')||'[]')[0];if(!last)return;let n={enemy:'动物',weather:'天气',hunger:'饥饿',survived:'通过'},report=last.weatherReport,diagnosis=last.cause==='weather'&&report?` · 诊断：${report.reason}`:'';$('#logDay').textContent=`历史：${last.at} · 第 ${last.day} 天 · 致命原因 ${n[last.cause]||last.cause}`;$('#logState').textContent=`累计伤害：动物 ${last.damage.enemy} · 天气 ${last.damage.weather} · 饥饿 ${last.damage.hunger}${diagnosis}`;$('#logEntries').innerHTML=last.logs.map(a=>`<div class="log-entry ${a.type}"><b>${a.stamp}</b>${a.text} <small>[H${a.hp}/F${a.food}]</small></div>`).join('')}
function normalizeStrategy(s={}){let out={...AI,...s};for(let k of Object.keys(AI))if(out[k]===undefined||out[k]===null)out[k]=AI[k];out.version=/^\d+\.\d+\.\d+$/.test(out.version||'')?out.version:AI.version;out.craftPriority=Array.isArray(out.craftPriority)&&out.craftPriority.length?[...new Set(out.craftPriority.filter(x=>typeof x==='string'))]:[...AI.craftPriority];return out}
function nextVersion(v){let a=v.split('.').map(Number);a[2]++;return a.join('.')}
function moveFirst(list,id){return[id,...list.filter(x=>x!==id)]}
function renderStrategyReview(){let runs=JSON.parse(localStorage.getItem('island-ai-history')||'[]').slice(0,10),deaths={enemy:0,weather:0,hunger:0};runs.forEach(r=>deaths[r.cause]=(deaths[r.cause]||0)+1);let top=Object.entries(deaths).sort((a,b)=>b[1]-a[1])[0][0],next={...AI,craftPriority:[...AI.craftPriority],version:nextVersion(AI.version)};if(top==='enemy'){next.trapThreatDistance=Math.min(6,AI.trapThreatDistance+1);next.description='降低野猪死亡：扩大路径陷阱警戒范围'}else if(top==='hunger'){next.eatMealBelow=Math.min(85,AI.eatMealBelow+7);next.eatBerryBelow=Math.min(70,AI.eatBerryBelow+7);next.fishBelow=Math.min(90,AI.fishBelow+8);next.description='降低饥饿死亡：提前进食和钓鱼'}else{next.buildShelterBeforeBase=true;next.description='降低天气死亡：围墙完成前先造棚屋'}recommendedStrategy=next;let names={enemy:'野猪',weather:'天气',hunger:'饥饿'},days=runs.map(r=>r.day),avg=(days.reduce((a,b)=>a+b,0)/days.length).toFixed(1);$('#resultTable').innerHTML=`<table><thead><tr><th>局</th><th>存活天数</th><th>致命原因</th><th>主要累计伤害</th></tr></thead><tbody>${runs.map((r,i)=>`<tr><td>${i+1}</td><td>${r.day}</td><td>${names[r.cause]}</td><td>${names[r.mainDamage||r.cause]}</td></tr>`).join('')}</tbody></table><p>平均 ${avg} 天 · 最长 ${Math.max(...days)} 天</p>`;let rows=[['版本',AI.version,next.version],['熟食阈值',AI.eatMealBelow,next.eatMealBelow],['浆果阈值',AI.eatBerryBelow,next.eatBerryBelow],['钓鱼阈值',AI.fishBelow,next.fishBelow],['陷阱距离',AI.trapThreatDistance,next.trapThreatDistance],['先造棚屋',AI.buildShelterBeforeBase?'是':'否',next.buildShelterBeforeBase?'是':'否']];$('#strategyDiff').innerHTML=`<p>主要致命原因：${names[top]}（${deaths[top]} 局）。${next.description}</p><table><tr><th>参数</th><th>当前</th><th>推荐</th></tr>${rows.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td class="${r[1]!==r[2]?'changed':''}">${r[2]}</td></tr>`).join('')}</table>`;$('#strategyReview').classList.remove('hidden');$('#strategyStatus').textContent='建议尚未应用。'}
function strategySignature(s){let copy={...s};delete copy.version;delete copy.description;return JSON.stringify(copy)}
const heuristicStrategyReview=renderStrategyReview;
renderStrategyReview=function(){heuristicStrategyReview();let runs=JSON.parse(localStorage.getItem('island-ai-history')||'[]').slice(0,10),avg=runs.reduce((n,r)=>n+r.day,0)/runs.length,champion=JSON.parse(localStorage.getItem('island-ai-champion')||'null'),current={...AI,craftPriority:[...AI.craftPriority]},sameChampion=champion&&strategySignature(champion.strategy)===strategySignature(current),rejected=JSON.parse(localStorage.getItem('island-ai-rejected')||'[]');if(!champion||avg>champion.avg){champion={avg,strategy:current,version:AI.version};localStorage.setItem('island-ai-champion',JSON.stringify(champion));$('#strategyStatus').textContent=`当前策略成为冠军：平均生存 ${avg.toFixed(1)} 天。建议测试下一候选。`}else if(!sameChampion&&avg<=champion.avg){rejected.push(strategySignature(current));localStorage.setItem('island-ai-rejected',JSON.stringify(rejected.slice(-20)));recommendedStrategy={...champion.strategy,craftPriority:[...champion.strategy.craftPriority],version:nextVersion(AI.version),description:`候选策略退步，回滚冠军 v${champion.version}`};$('#strategyDiff').insertAdjacentHTML('afterbegin',`<p class="damage">本代平均 ${avg.toFixed(1)} 天，低于冠军 ${champion.avg.toFixed(1)} 天。拒绝本代并回滚，不会继续重复。</p>`);$('#strategyStatus').textContent='推荐操作：回滚到冠军策略。'}else if(sameChampion&&rejected.includes(strategySignature(recommendedStrategy))){recommendedStrategy.bedHealthBelow=Math.min(90,(AI.bedHealthBelow||75)+5);recommendedStrategy.wallLevel2Day=Math.max(2,(AI.wallLevel2Day||5)-1);recommendedStrategy.growthValueWeight=Number(((AI.growthValueWeight||1.5)+.25).toFixed(2));recommendedStrategy.description='避开已失败候选：更早休息、更早升级围栏、提高成熟资源价值';$('#strategyStatus').textContent='原建议曾失败，已自动换用不同的候选策略。'}}
async function applyRecommendedStrategy(){let button=$('#applyStrategyButton');if(button.dataset.applied)return button.dataset.applied==='evolve'?startEvolution():startTenRuns();if(!LOCAL_AI_LAB||!recommendedStrategy)return;button.disabled=true;$('#strategyStatus').textContent='正在迁移并写入最佳策略…';try{let payload=normalizeStrategy(recommendedStrategy),res=await fetch('/__ai_strategy',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),data=await res.json();if(!res.ok)throw new Error(data.error||'写入失败');recommendedStrategy=normalizeStrategy(data.strategy||payload);Object.assign(AI,recommendedStrategy);localStorage.setItem('island-ai-champion',JSON.stringify({avg:Number(JSON.parse(localStorage.getItem('island-ai-champion')||'{}').avg)||0,strategy:{...AI,craftPriority:[...AI.craftPriority]},version:AI.version}));$('#strategyStatus').textContent=`最佳策略 v${data.version} 已写入本地 ai-strategy.js；下一轮会以它作为父代继续变异，而不是重新随机开始。`;button.dataset.applied=recommendationMode==='evolution'?'evolve':'test';button.disabled=false;button.textContent=recommendationMode==='evolution'?`用冠军 v${data.version} 继续进化 300 局`:`用 v${data.version} 继续测试 10 局`}catch(e){$('#strategyStatus').textContent=`无法更新：${e.message}。本地写入需要通过 node server.js 打开游戏。`;button.disabled=false}}
function clearHistory(){localStorage.removeItem('island-ai-history');renderHistory();logEvent('历史测试记录已清空')}
function restartGame(){['island-v3','island-save-v3','island-save','island-checkpoints-v1'].forEach(k=>localStorage.removeItem(k));location.reload()}
function logEvent(text,type='info'){let stamp=`D${day} ${String(Math.floor((time%60000)/1000)).padStart(2,'0')}s`,entry={stamp,text,type,hp:Math.ceil(p.health),food:Math.ceil(p.hunger)};gameLogs.unshift(entry);gameLogs=gameLogs.slice(0,120);$('#logDay').textContent=`${seasonInfo().name} · 第 ${day} 天 · ${weather} · 防护 ${weatherProtection()} · 衣物 ${clothingProtection()?'合适':'不合适'}`;$('#logState').textContent=`健康 ${entry.hp} · 饥饿 ${entry.food}`;$('#logEntries').innerHTML=gameLogs.map(a=>`<div class="log-entry ${a.type}"><b>${a.stamp}</b>${a.text} <small>[H${a.hp}/F${a.food}]</small></div>`).join('')}
function toast(s){let e=$('#toast');e.textContent=s;e.classList.add('show');logEvent(s,/攻击|伤害|健康 -|倒下/.test(s)?'damage':s.startsWith('AI')?'ai':'info');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1800)}
const visualUpdateUI=updateUI,visualLogEvent=logEvent,visualToast=toast,visualRenderHistory=renderHistory;
updateUI=function(){if(!batchLeft)visualUpdateUI()}
renderHistory=function(){if(!batchLeft)visualRenderHistory()}
logEvent=function(text,type='info'){if(!batchLeft)return visualLogEvent(text,type);let stamp=`D${day} ${String(Math.floor((time%60000)/1000)).padStart(2,'0')}`;gameLogs.unshift({stamp,text,type,hp:Math.ceil(p.health),food:Math.ceil(p.hunger)});gameLogs=gameLogs.slice(0,120)}
toast=function(s){if(batchLeft)return logEvent(s,/攻击|伤害|健康 -|倒下/.test(s)?'damage':s.startsWith('AI')?'ai':'info');let hit=s.match(/攻击！健康 -(\d+)/);if(hit){playerHitUntil=performance.now()+240;addCombatFx(p.x,p.y,`-${hit[1]}`,'#ff7868');let attacker=enemies.find(e=>time-e.lastAttack<80);if(attacker)attacker.attackUntil=performance.now()+230}visualToast(s)}
function toggleLog(){$('#logPanel').classList.toggle('open');$('#scrim').classList.toggle('open',$('#logPanel').classList.contains('open'))}
function openBag(){$('#bag').classList.add('open');$('#scrim').classList.add('open');updateUI()}function closeBag(){$('#bag').classList.remove('open');$('#scrim').classList.remove('open')}
function save(){if(batchLeft)return;localStorage.setItem('island-v3',JSON.stringify({inv,objects,structures,enemies,drops,health:p.health,hunger:p.hunger,day,time,weather,dailyEvent,worldProfile}))}
function placeBridge(x,y){let tidal=TIDAL_CELLS.some(a=>a.x===x&&a.y===y),water=BASE_TERRAIN[y]?.[x]===1;if(!inv.bridge)return setMode('hand');if(!water&&!tidal)return toast('木桥只能铺在水面或潮汐浅滩');if(structureAt(x,y)||p.x===x&&p.y===y)return toast('这里不能建造');structures.push({x,y,type:'bridge',hp:100,maxHp:100});inv.bridge--;toast('木桥已架设；涨潮期间记得检查耐久');setMode('hand');updateUI();save()}
function promptPlacedBuilding(build){if(build.type==='kitchen')kitchenPrompt(build);else if(build.type==='bed')bedPrompt(build);else if(['fence','door'].includes(build.type))fencePrompt(build);else buildingPrompt(build)}
function calibratedTap(e){let touch=e.pointerType==='touch'||e.pointerType==='pen',verticalOffset=touch?p.tile*.24:0,clientY=e.clientY+verticalOffset,r=canvas.getBoundingClientRect(),x=Math.floor((e.clientX-r.left-p.ox)/p.tile+cameraX),y=Math.floor((clientY-r.top-p.oy)/p.tile);if(x<0||y<0||x>=COLS||y>=ROWS)return;if(mode==='bridge')return placeBridge(x,y);let bridge=structures.find(a=>a.x===x&&a.y===y&&a.type==='bridge'),building=structures.find(a=>a.x===x&&a.y===y&&a.type!=='bridge');if(bridge&&building&&Math.abs(p.x-x)+Math.abs(p.y-y)===1){selected={x,y};return bridge.hp<bridge.maxHp?buildingPrompt(bridge):promptPlacedBuilding(building)}if(strandedByTide())return toast('被涨潮困住了：等待退潮，或提前准备木桥和船');let navigableWater=map[y][x]&&(inv.boat||bridge);if(navigableWater){let original=map[y][x];map[y][x]=0;tap({clientX:e.clientX,clientY});map[y][x]=original;return}tap({clientX:e.clientX,clientY})}
canvas.addEventListener('pointerup',calibratedTap);$('#bagButton').onclick=openBag;$('#aiButton').onclick=toggleAI;$('#logButton').onclick=toggleLog;$('#closeLog').onclick=toggleLog;$('#runTenButton').onclick=startTenRuns;$('#clearHistoryButton').onclick=clearHistory;$('#applyStrategyButton').onclick=applyRecommendedStrategy;$('#runSummary').onclick=showLastHistory;$('#viewDeathLog').onclick=()=>{$('#logPanel').classList.add('open')};$('#closeBag').onclick=closeBag;$('#scrim').onclick=()=>{$('#logPanel').classList.remove('open');closeBag()};$('#startButton').onclick=()=>{started=true;logEvent('游戏开始：春季第 1 天');$('#welcome').classList.add('closed')};$('#restartButton').onclick=restartGame;$$('.quick').forEach(b=>b.onclick=()=>setMode(b.dataset.slot));$$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.toggle('active',x===b));$('#itemsPanel').classList.toggle('hidden',b.dataset.tab!=='items');$('#craftPanel').classList.toggle('hidden',b.dataset.tab!=='craft')});
$('#pauseButton').onclick=togglePause;
async function setupUpdates(){if(!('serviceWorker'in navigator))return;let hadController=!!navigator.serviceWorker.controller,reg=await navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'});reg.update();setInterval(()=>reg.update(),60000);navigator.serviceWorker.addEventListener('controllerchange',()=>{if(hadController)$('#updateBanner').classList.remove('hidden');hadController=true});$('#reloadUpdate').onclick=()=>location.reload()}
const championStrategyReview=renderStrategyReview;
const normalFinishRun=finishRun;
const originalResetRun=resetRun;
resetRun=function(){worldProfile=randomWorldProfile();dailyEvent='平静';tide='退潮';lastBridgeDamageDay=0;for(let a of TIDAL_CELLS)map[a.y][a.x]=BASE_TERRAIN[a.y][a.x];originalResetRun()}
const GENE_BOUNDS={eatMealBelow:[45,90,5],eatBerryBelow:[25,75,5],fishBelow:[45,95,5],trapThreatDistance:[2,6,1],growthValueWeight:[.5,3,.25],bedHealthBelow:[45,95,5],wallLevel2Day:[2,8,1],wallLevel3Day:[6,16,1],weapon2Day:[2,8,1],weapon3Day:[6,16,1]};
function mutateStrategy(base,rate=.45){let out=normalizeStrategy(base);for(let[k,[min,max,step]]of Object.entries(GENE_BOUNDS))if(Math.random()<rate)out[k]=Math.max(min,Math.min(max,Number((out[k]+(Math.random()<.5?-step:step)).toFixed(2))));if(Math.random()<.2)out.buildShelterBeforeBase=!out.buildShelterBeforeBase;if(Math.random()<.25){let a=Math.floor(Math.random()*out.craftPriority.length),b=Math.floor(Math.random()*out.craftPriority.length);[out.craftPriority[a],out.craftPriority[b]]=[out.craftPriority[b],out.craftPriority[a]]}out.wallLevel3Day=Math.max(out.wallLevel2Day+2,out.wallLevel3Day);out.weapon3Day=Math.max(out.weapon2Day+2,out.weapon3Day);return out}
function crossStrategies(a,b){let out=normalizeStrategy(a);for(let k of Object.keys(GENE_BOUNDS))out[k]=Math.random()<.5?a[k]:b[k];out.buildShelterBeforeBase=Math.random()<.5?a.buildShelterBeforeBase:b.buildShelterBeforeBase;out.craftPriority=(Math.random()<.5?a:b).craftPriority.slice();return mutateStrategy(out,.35)}
function evolutionScore(runs){let days=runs.map(r=>r.day),avg=days.reduce((a,b)=>a+b,0)/days.length,min=Math.min(...days),kills=runs.reduce((n,r)=>n+r.kills,0)/runs.length,meals=runs.reduce((n,r)=>n+r.meals,0)/runs.length,variance=days.reduce((n,d)=>n+(d-avg)**2,0)/days.length;return avg*100+min*25+kills*4+meals*2-Math.sqrt(variance)*12}
function evolutionPopulation(parents){if(!parents)return[normalizeStrategy(AI),...Array.from({length:5},()=>mutateStrategy(AI))];let[a,b]=parents;return[normalizeStrategy(a),normalizeStrategy(b),...Array.from({length:4},()=>crossStrategies(a,b))]}
function loadEvolutionCandidate(){let candidate=evolution.population[evolution.candidate];Object.assign(AI,normalizeStrategy(candidate));evolution.currentRuns=[];batchLeft=10;lastBatchProgressDay=-1;resetRun()}
function startEvolution(){if(!LOCAL_AI_LAB||evolution)return;evolution={generation:1,maxGenerations:5,candidate:0,population:evolutionPopulation(),results:[],currentRuns:[],best:null,generationHistory:[]};recommendedStrategy=null;$('#batchProgressTitle').textContent='遗传算法 · 自动进化 300 局';$('#strategyReviewTitle').textContent='遗传算法冠军报告';document.body.classList.add('batch-running');$('#logPanel').classList.remove('open');$('#scrim').classList.remove('open');loadEvolutionCandidate()}
function finishEvolutionRun(success){
  if(runEnding)return;
  runEnding=true;started=false;
  let record=archiveRun(success);
  evolution.currentRuns.push(record);batchLeft--;
  if(batchLeft>0)return void setTimeout(resetRun,10);
  let strategy=normalizeStrategy(evolution.population[evolution.candidate]);
  let score=evolutionScore(evolution.currentRuns);
  let result={strategy,score,runs:evolution.currentRuns.slice(),generation:evolution.generation,candidate:evolution.candidate+1};
  evolution.results.push(result);
  if(!evolution.best||score>evolution.best.score)evolution.best=result;
  evolution.candidate++;
  if(evolution.candidate<evolution.population.length)return void loadEvolutionCandidate();
  let ranked=evolution.results.slice().sort((a,b)=>b.score-a.score),generationWinner=ranked[0];
  let days=generationWinner.runs.map(r=>r.day);
  evolution.generationHistory.push({generation:evolution.generation,score:generationWinner.score,avg:days.reduce((a,b)=>a+b,0)/days.length,min:Math.min(...days),max:Math.max(...days),candidate:generationWinner.candidate});
  let parents=ranked.slice(0,2).map(r=>r.strategy);
  if(evolution.generation<evolution.maxGenerations){
    evolution.generation++;evolution.candidate=0;evolution.results=[];evolution.population=evolutionPopulation(parents);
    return void loadEvolutionCandidate();
  }
  let winner=evolution.best,history=evolution.generationHistory.slice();
  let winnerDays=winner.runs.map(r=>r.day),winnerAvg=winnerDays.reduce((a,b)=>a+b,0)/winnerDays.length;
  recommendationMode='evolution';
  recommendedStrategy={...winner.strategy,version:nextVersion(AI.version),description:`第 ${winner.generation} 代冠军：适应度 ${winner.score.toFixed(1)}，平均生存 ${winnerAvg.toFixed(1)} 天`};
  evolution=null;batchLeft=0;document.body.classList.remove('batch-running');
  Object.assign(AI,normalizeStrategy(JSON.parse(localStorage.getItem('island-ai-champion')||'null')?.strategy||AI));
  $('#welcome').classList.remove('closed');$('#welcome').classList.add('gameover');
  $('.modal h1').textContent='自动进化完成';$('.modal>p').textContent='300局统一规则模拟完成。下方已生成逐代成绩和冠军参数。';
  $('#strategyReviewTitle').textContent='遗传算法冠军报告';$('#strategyReview').classList.remove('hidden');
  $('#resultTable').innerHTML=`<p><b>这不是普通10局测试：</b>共进化 5 代，每代比较 6 个候选策略，每个候选跑 10 局。</p><table><thead><tr><th>代</th><th>冠军适应度</th><th>平均天数</th><th>最短</th><th>最长</th></tr></thead><tbody>${history.map(h=>`<tr class="${h.generation===winner.generation?'changed':''}"><td>${h.generation}</td><td>${h.score.toFixed(1)}</td><td>${h.avg.toFixed(1)}</td><td>${h.min}</td><td>${h.max}</td></tr>`).join('')}</tbody></table><p>最终采用第 <b>${winner.generation}</b> 代第 <b>${winner.candidate}</b> 个候选：平均 <b>${winnerAvg.toFixed(1)}</b> 天，最短 ${Math.min(...winnerDays)} 天，最长 ${Math.max(...winnerDays)} 天。</p>`;
  renderFinalStrategyDiff();$('#strategyStatus').textContent='冠军参数尚未写入；点击下方按钮后才会成为新的本地/线上候选策略。';
  $('#applyStrategyButton').disabled=false;$('#applyStrategyButton').dataset.applied='';$('#applyStrategyButton').textContent='写入进化冠军策略';
  updateUI();draw();
}
finishRun=function(success){if(evolution)return finishEvolutionRun(success);let manual=!batchLeft;normalFinishRun(success);if(manual&&!success){let count=checkpointCount();$('.modal>p').textContent=count?`你倒下了。系统每3天保存一次，当前保留 ${count} 个检查点，可以回到最近的安全日继续。`:'没有可用检查点，只能清空本局重新开始。';$('#restartButton').textContent=count?'回到最近的安全存档':'重新开始';$('#clearGameButton').classList.remove('hidden')}}
const evolutionFinishCore=finishEvolutionRun;
finishEvolutionRun=function(success){let wasRunning=!!evolution;evolutionFinishCore(success);if(wasRunning&&!evolution){$('#startButton').classList.add('hidden');$('#restartButton').classList.add('hidden');$('#clearGameButton').classList.add('hidden');$('#viewDeathLog').textContent='查看进化结果并写入';$('#viewDeathLog').classList.remove('hidden');$('#logPanel').classList.add('open');$('#scrim').classList.add('open')}}
function strategyValue(v){if(Array.isArray(v))return v.join(' → ');if(typeof v==='boolean')return v?'是':'否';return String(v)}
function strategyChanges(from,to){return Object.keys(to).filter(k=>!['version','description'].includes(k)&&strategyValue(from[k])!==strategyValue(to[k]))}
function ensureRealStrategyChange(){let changed=strategyChanges(AI,recommendedStrategy);if(changed.length)return changed;let runs=JSON.parse(localStorage.getItem('island-ai-history')||'[]').slice(0,10),enemy=runs.filter(r=>r.cause==='enemy').length,weatherDeaths=runs.filter(r=>r.cause==='weather').length;if(enemy>=weatherDeaths){recommendedStrategy.weapon2Day=Math.max(2,(AI.weapon2Day||5)-1);recommendedStrategy.wallLevel2Day=Math.max(2,(AI.wallLevel2Day||5)-1);recommendedStrategy.description='陷阱距离已到上限：改为更早升级武器和围栏'}else{recommendedStrategy.wallLevel2Day=Math.max(2,(AI.wallLevel2Day||5)-1);recommendedStrategy.bedHealthBelow=Math.min(95,(AI.bedHealthBelow||75)+5);recommendedStrategy.description='原天气参数已无变化：改为更早升级防线并提前休息'}changed=strategyChanges(AI,recommendedStrategy);if(!changed.length){recommendedStrategy.growthValueWeight=Number(((AI.growthValueWeight||1.5)+.25).toFixed(2));recommendedStrategy.description='原候选没有真实变化：提高成熟资源的采集价值'}return strategyChanges(AI,recommendedStrategy)}
function renderFinalStrategyDiff(){if(!recommendedStrategy)return;let labels={eatMealBelow:'熟食进食阈值',eatBerryBelow:'浆果进食阈值',fishBelow:'开始钓鱼阈值',trapThreatDistance:'陷阱警戒距离',buildShelterBeforeBase:'围墙前先造棚屋',growthValueWeight:'成熟资源价值权重',bedHealthBelow:'上床休息生命阈值',wallLevel2Day:'二级围栏目标日',wallLevel3Day:'三级围栏目标日',weapon2Day:'加固长矛目标日',weapon3Day:'猎兽矛目标日',craftPriority:'制作优先级',testSpeed:'旧测试倍率'},changed=ensureRealStrategyChange(),rows=changed.map(k=>`<tr><td>${labels[k]||k}</td><td>${strategyValue(AI[k])}</td><td class="changed">${strategyValue(recommendedStrategy[k])}</td></tr>`).join('');$('#strategyDiff').innerHTML=`<p><b>本轮实际优化：</b>${recommendedStrategy.description}</p><p>版本 ${AI.version} → ${recommendedStrategy.version}，共改变 <b>${changed.length}</b> 个策略参数。</p><table><thead><tr><th>改变的参数</th><th>当前</th><th>新策略</th></tr></thead><tbody>${rows}</tbody></table><small>未变化的参数已隐藏，避免把版本升级误当成策略优化。</small>`}
renderStrategyReview=function(){championStrategyReview();renderFinalStrategyDiff()}
$('#evolveButton').onclick=startEvolution;
$('#restartButton').onclick=restoreCheckpoint;
$('#clearGameButton').onclick=restartGame;
$('#startButton').addEventListener('click',()=>{rollDailyEvent();saveCheckpoint();toast(`本局世界：${worldProfile.name}`)});
document.documentElement.classList.add(LOCAL_AI_LAB?'local-ai-lab':'production');window.addEventListener('resize',resize);resize();updateUI();if(LOCAL_AI_LAB){let oldChampion=JSON.parse(localStorage.getItem('island-ai-champion')||'null');if(oldChampion?.strategy){oldChampion.strategy=normalizeStrategy(oldChampion.strategy);oldChampion.version=oldChampion.strategy.version;localStorage.setItem('island-ai-champion',JSON.stringify(oldChampion))}renderHistory()}requestAnimationFrame(animate);window.addEventListener('load',setupUpdates);
