const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],AI=window.AI_STRATEGY,LOCAL_AI_LAB=['localhost','127.0.0.1','::1'].includes(location.hostname);
const COLS=9,ROWS=12,map=[[1,1,1,1,1,1,1,1,1],[1,1,0,0,0,0,1,1,1],[1,0,0,0,0,0,0,1,1],[1,0,0,0,0,0,0,0,1],[1,0,0,0,0,0,0,0,1],[1,1,0,0,0,0,0,0,1],[1,1,0,0,0,0,0,1,1],[1,0,0,0,0,0,0,1,1],[1,0,0,0,0,0,0,0,1],[1,1,0,0,0,0,0,1,1],[1,1,1,0,0,0,1,1,1],[1,1,1,1,1,1,1,1,1]];
const defs={wood:['木头','🪵'],grass:['草','🌿'],berry:['浆果','🫐'],fish:['生鱼','🐟'],carcass:['动物肉','🥩'],meal:['熟食','🍲'],rod:['鱼竿','🎣'],trap:['陷阱','⌗'],fence:['木围栏','▥'],door:['木门','▯'],kitchen:['野外厨房','♨'],shelter:['简易棚屋','⌂'],strongShelter:['加固庇护所','🏠']};
const INITIAL_OBJECTS=[{x:3,y:2,type:'wood'},{x:5,y:2,type:'grass'},{x:6,y:3,type:'berry'},{x:2,y:4,type:'grass'},{x:5,y:4,type:'wood'},{x:6,y:5,type:'grass'},{x:3,y:7,type:'berry'},{x:5,y:7,type:'wood'},{x:6,y:8,type:'grass'},{x:2,y:8,type:'wood'},{x:4,y:9,type:'wood'},{x:5,y:9,type:'grass'}];
let objects=INITIAL_OBJECTS.map(a=>({...a})),structures=[],enemies=[],drops=[];
let p={x:4,y:6,px:4,py:6,path:[],health:100,hunger:80,tile:40,ox:0,oy:0},inv=Object.fromEntries(Object.keys(defs).map(k=>[k,0]));
let selected=null,mode='hand',started=false,aiOn=false,time=0,last=performance.now(),day=1,weather='晴朗',enemyClock=0,weatherClock=0,aiClock=0,resourceClock=0,gameLogs=[],batchLeft=0,runEnding=false,recommendedStrategy=null,runStats={kills:0,meals:0,damage:{enemy:0,weather:0,hunger:0},minHealth:100,minHunger:80};
const weatherList=[['晴朗',0],['小雨',0],['暴雨',1],['寒风',1],['多云',0]];
const recipes=[{id:'trap',name:'简易陷阱',desc:'自动重伤踩中的动物',cost:{wood:2,grass:3},place:1},{id:'rod',name:'粗制鱼竿',desc:'站在岸边点击水面钓鱼',cost:{wood:3,grass:2}},{id:'fence',name:'木围栏',desc:'坚固度 1；完整围合可挡天气',cost:{wood:2},place:1},{id:'door',name:'木门',desc:'与围栏一起封闭小屋，可通行',cost:{wood:2,grass:1},place:1},{id:'kitchen',name:'野外厨房',desc:'把生鱼和动物肉做成熟食',cost:{wood:4,grass:2},place:1},{id:'shelter',name:'简易棚屋',desc:'天气防护 1',cost:{wood:6,grass:5},place:1},{id:'strongShelter',name:'加固庇护所',desc:'升级防护，天气防护 2',cost:{wood:10,grass:6},place:1}];
function resize(){let r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio,2);canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);p.tile=Math.floor(Math.min(r.width/COLS,r.height/ROWS));p.ox=Math.floor((r.width-p.tile*COLS)/2);p.oy=Math.floor((r.height-p.tile*ROWS)/2)}
function tileXY(x,y){return[p.ox+x*p.tile,p.oy+y*p.tile]}
function draw(){let t=p.tile;ctx.fillStyle='#102119';ctx.fillRect(0,0,canvas.clientWidth,canvas.clientHeight);for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++){let[X,Y]=tileXY(x,y);ctx.fillStyle=map[y][x]?((x+y)%2?'#245769':'#286174'):((x+y)%2?'#476a45':'#426341');ctx.fillRect(X,Y,t,t);if(map[y][x]){ctx.fillStyle='#78b5ad66';ctx.fillRect(X+(time/90+x*7)%Math.max(8,t-8),Y+t*.35,8,2)}else{ctx.fillStyle='#6f925c';ctx.fillRect(X+7+(x*5+y*3)%12,Y+8+(x*3)%17,2,4)}ctx.strokeStyle='#203a2d';ctx.strokeRect(X+.5,Y+.5,t-1,t-1)}
 if(selected){let[X,Y]=tileXY(selected.x,selected.y);ctx.strokeStyle='#f2c96b';ctx.lineWidth=2;ctx.strokeRect(X+2,Y+2,t-4,t-4);ctx.lineWidth=1}structures.forEach(drawStructure);[...objects,...drops].forEach(drawItem);enemies.forEach(drawEnemy);drawPlayer();if(weather==='暴雨'){ctx.strokeStyle='#c3e0e477';for(let i=0;i<18;i++){let x=(i*47+time*.13)%canvas.clientWidth,y=(i*71+time*.21)%canvas.clientHeight;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-5,y+12);ctx.stroke()}}}
function drawItem(a){let[X,Y]=tileXY(a.x,a.y),t=p.tile;if(['wood','grass','berry'].includes(a.type)){ctx.font=`${t*.55}px sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(defs[a.type][1],X+t/2,Y+t/2)}else{ctx.font=`${t*.5}px sans-serif`;ctx.textAlign='center';ctx.fillText(defs[a.type][1],X+t/2,Y+t*.68)}}
function drawStructure(a){let[X,Y]=tileXY(a.x,a.y),t=p.tile;ctx.save();ctx.translate(X,Y);if(a.type==='fence'){ctx.fillStyle='#8a6138';ctx.fillRect(t*.1,t*.3,t*.8,t*.13);ctx.fillRect(t*.1,t*.64,t*.8,t*.13);for(let i=0;i<3;i++)ctx.fillRect(t*(.15+i*.31),t*.13,t*.13,t*.72)}else if(a.type==='door'){ctx.fillStyle='#ad7a42';ctx.fillRect(t*.2,t*.12,t*.6,t*.76);ctx.fillStyle='#201811';ctx.fillRect(t*.64,t*.48,4,4)}else if(a.type==='trap'){ctx.strokeStyle='#dec477';ctx.lineWidth=3;ctx.strokeRect(t*.2,t*.2,t*.6,t*.6);ctx.beginPath();ctx.moveTo(t*.2,t*.2);ctx.lineTo(t*.8,t*.8);ctx.moveTo(t*.8,t*.2);ctx.lineTo(t*.2,t*.8);ctx.stroke()}else{ctx.fillStyle=a.type==='kitchen'?'#584638':a.type==='strongShelter'?'#53635a':'#795535';ctx.fillRect(t*.12,t*.35,t*.76,t*.52);ctx.fillStyle=a.type==='kitchen'?'#e27443':a.type==='strongShelter'?'#aeb7a9':'#c79a5d';ctx.fillRect(t*.28,t*.17,t*.44,t*.3);ctx.fillStyle='#251a14';ctx.fillRect(t*.42,t*.57,t*.18,t*.3)}ctx.restore()}
function drawEnemy(e){let[X,Y]=tileXY(e.x,e.y),t=p.tile;ctx.fillStyle=e.hit?'#d86d57':'#76523f';ctx.fillRect(X+t*.18,Y+t*.4,t*.64,t*.34);ctx.fillRect(X+t*.56,Y+t*.23,t*.31,t*.3);ctx.fillStyle='#211512';ctx.fillRect(X+t*.7,Y+t*.31,3,3);ctx.fillStyle='#39201b';ctx.fillRect(X+t*.16,Y+t*.12,t*.58,4);ctx.fillStyle='#66ad63';ctx.fillRect(X+t*.16,Y+t*.12,t*.58*e.hp/50,4)}
function drawPlayer(){let[X,Y]=tileXY(p.px,p.py),t=p.tile,b=p.path.length?Math.sin(time/80)*2:0;Y+=b;ctx.fillStyle='#111b16aa';ctx.beginPath();ctx.ellipse(X+t*.5,Y+t*.82,t*.25,t*.1,0,0,7);ctx.fill();ctx.fillStyle='#283c32';ctx.fillRect(X+t*.3,Y+t*.48,t*.4,t*.36);ctx.fillStyle='#d5a06e';ctx.fillRect(X+t*.31,Y+t*.18,t*.38,t*.34);ctx.fillStyle='#3b2921';ctx.fillRect(X+t*.27,Y+t*.12,t*.46,t*.16);ctx.fillStyle='#171c19';ctx.fillRect(X+t*.4,Y+t*.3,3,3);ctx.fillRect(X+t*.59,Y+t*.3,3,3)}
function occupied(x,y,animal=false){if(x<0||y<0||x>=COLS||y>=ROWS||map[y][x])return true;if(objects.concat(drops).some(a=>a.x===x&&a.y===y))return true;if(structures.some(a=>a.x===x&&a.y===y&&a.type!=='trap'&&!(a.type==='door'&&!animal)))return true;return !animal&&enemies.some(a=>a.x===x&&a.y===y)}
function pathfind(tx,ty,animal=false,start={x:p.x,y:p.y}){let q=[start],seen=new Map([[`${start.x},${start.y}`,null]]),end;while(q.length){let a=q.shift();if(a.x===tx&&a.y===ty){end=a;break}for(let[dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){let n={x:a.x+dx,y:a.y+dy},k=`${n.x},${n.y}`;if(!seen.has(k)&&(!occupied(n.x,n.y,animal)||(n.x===tx&&n.y===ty))){seen.set(k,a);q.push(n)}}}if(!end)return null;let out=[];while(end.x!==start.x||end.y!==start.y){out.unshift(end);end=seen.get(`${end.x},${end.y}`)}return out}
function nextTo(x,y){let best=[[1,0],[-1,0],[0,1],[0,-1]].map(([dx,dy])=>({x:x+dx,y:y+dy})).filter(a=>!occupied(a.x,a.y)).map(a=>({a,path:pathfind(a.x,a.y)})).filter(a=>a.path).sort((a,b)=>a.path.length-b.path.length)[0];if(best)p.path=best.path;else toast('无法靠近目标')}
function tap(e){if(!started||p.health<=0)return;let r=canvas.getBoundingClientRect(),x=Math.floor((e.clientX-r.left-p.ox)/p.tile),y=Math.floor((e.clientY-r.top-p.oy)/p.tile);if(x<0||y<0||x>=COLS||y>=ROWS)return;selected={x,y};if(['trap','fence','door','kitchen','shelter','strongShelter'].includes(mode)){place(x,y);return}let foe=enemies.find(a=>a.x===x&&a.y===y);if(foe){Math.abs(p.x-x)+Math.abs(p.y-y)===1?attack(foe):nextTo(x,y);return}let item=objects.concat(drops).find(a=>a.x===x&&a.y===y);if(item){Math.abs(p.x-x)+Math.abs(p.y-y)===1?pickupPrompt(item):nextTo(x,y);return}let build=structures.find(a=>a.x===x&&a.y===y);if(build?.type==='kitchen'&&Math.abs(p.x-x)+Math.abs(p.y-y)===1){kitchenPrompt();return}hideAction();if(map[y][x]){if(inv.rod&&Math.abs(p.x-x)+Math.abs(p.y-y)===1)fish();else toast(inv.rod?'请先站到岸边':'水里不能走，需要鱼竿');return}let path=pathfind(x,y);if(path)p.path=path;else toast('那里过不去')}
function pickupPrompt(a){$('#actionIcon').textContent=defs[a.type][1];$('#actionTitle').textContent=`拾取${defs[a.type][0]}`;$('#actionText').textContent=a.type==='carcass'?'必须在厨房烹饪':'收入背包';$('#actionButton').textContent='拾取';$('#actionButton').disabled=false;$('#actionButton').onclick=()=>pickup(a);$('#actionPrompt').classList.remove('hidden')}
function pickup(a){let pool=objects.includes(a)?objects:drops;pool.splice(pool.indexOf(a),1);inv[a.type]++;toast(`获得 ${defs[a.type][1]} ${defs[a.type][0]}`);hideAction();updateUI();save()}
function kitchenPrompt(){let n=inv.fish+inv.carcass;$('#actionIcon').textContent='♨';$('#actionTitle').textContent='野外厨房';$('#actionText').textContent=n?`可烹饪 ${n} 份食材`:'没有生鱼或动物肉';$('#actionButton').textContent='烹饪';$('#actionButton').disabled=!n;$('#actionButton').onclick=cook;$('#actionPrompt').classList.remove('hidden')}
function cook(){let n=inv.fish+inv.carcass;if(!n)return;inv.meal+=n;inv.fish=inv.carcass=0;toast(`得到熟食 ×${n}`);kitchenPrompt();updateUI();save()}
function hideAction(){$('#actionPrompt').classList.add('hidden')}
function fish(){toast('抛下鱼线…');setTimeout(()=>{inv.fish++;toast('钓到生鱼，请带到厨房');updateUI()},1000)}
function attack(e){e.hp-=25;e.hit=true;setTimeout(()=>e.hit=false,120);toast('攻击野猪，伤害 25');if(e.hp<=0){runStats.kills++;enemies.splice(enemies.indexOf(e),1);drops.push({x:e.x,y:e.y,type:'carcass'});toast('击败野猪，可以拾取动物肉')}}
function place(x,y){if(!inv[mode])return setMode('hand');if(occupied(x,y)||p.x===x&&p.y===y)return toast('这里不能建造');structures.push({x,y,type:mode});inv[mode]--;toast(`已放置${defs[mode][0]}`);setMode('hand');updateUI();save()}
function spawnEnemy(){let spots=[];for(let y=1;y<ROWS-1;y++)for(let x=1;x<COLS-1;x++)if(!occupied(x,y,true)&&Math.abs(x-p.x)+Math.abs(y-p.y)>5)spots.push({x,y});if(!spots.length||enemies.length>=3)return;let a=spots[Math.floor(Math.random()*spots.length)];enemies.push({...a,hp:50,lastMove:time,lastAttack:0,hit:false});toast('⚠ 野猪出现在附近！')}
function spawnResources(count=1){const MAX=12;if(objects.length>=MAX)return 0;let empty=[];for(let y=1;y<ROWS-1;y++)for(let x=1;x<COLS-1;x++)if(!map[y][x]&&!occupied(x,y)&&!(p.x===x&&p.y===y))empty.push({x,y});let added=0;while(count--&&empty.length&&objects.length<MAX){let i=Math.floor(Math.random()*empty.length),spot=empty.splice(i,1)[0],roll=Math.random(),type=roll<.42?'wood':roll<.77?'grass':'berry';objects.push({...spot,type});added++}if(added)save();return added}
function enclosedByFence(){let q=[{x:p.x,y:p.y}],seen=new Set([`${p.x},${p.y}`]);while(q.length){let a=q.shift();for(let[dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){let x=a.x+dx,y=a.y+dy;if(x<0||y<0||x>=COLS||y>=ROWS||map[y][x])return false;let wall=structures.some(s=>s.x===x&&s.y===y&&['fence','door'].includes(s.type));if(wall)continue;let k=`${x},${y}`;if(!seen.has(k)){seen.add(k);q.push({x,y});if(seen.size>24)return false}}}return structures.some(s=>s.type==='door')&&structures.filter(s=>s.type==='fence').length>=3}
function weatherProtection(){let strength=enclosedByFence()?1:0;if(structures.some(a=>a.type==='shelter'&&Math.abs(a.x-p.x)+Math.abs(a.y-p.y)<=1))strength=Math.max(strength,1);if(structures.some(a=>a.type==='strongShelter'&&Math.abs(a.x-p.x)+Math.abs(a.y-p.y)<=1))strength=Math.max(strength,2);return strength}
function enemyAI(){for(let e of [...enemies]){if(time-e.lastMove<750)continue;e.lastMove=time;let d=Math.abs(e.x-p.x)+Math.abs(e.y-p.y);if(d===1){if(time-e.lastAttack>1200){e.lastAttack=time;p.health=Math.max(0,p.health-8);runStats.damage.enemy+=8;toast('野猪攻击！健康 -8')}continue}let path=pathfind(p.x,p.y,true,{x:e.x,y:e.y});if(!path?.length)continue;let n=path[0];if(n.x===p.x&&n.y===p.y)continue;e.x=n.x;e.y=n.y;let trap=structures.find(a=>a.x===e.x&&a.y===e.y&&a.type==='trap');if(trap){structures.splice(structures.indexOf(trap),1);e.hp=0;runStats.kills++;toast('陷阱捕获野猪！');enemies.splice(enemies.indexOf(e),1);drops.push({x:e.x,y:e.y,type:'carcass'})}}}
function animate(now){let dt=Math.min(40,now-last)*(batchLeft?AI.testSpeed:1);last=now;time+=dt;if(started&&p.health>0){p.hunger=Math.max(0,p.hunger-dt*.00055);if(!p.hunger){let loss=dt*.001;p.health=Math.max(0,p.health-loss);runStats.damage.hunger+=loss}let d=Math.floor(time/60000)+1;if(d!==day){day=d;weather=weatherList[Math.floor(Math.random()*weatherList.length)][0];let grown=spawnResources(4);toast(`春 · 第 ${day} 天：${weather}，新生物资 ${grown} 份`);if(batchLeft&&day>=AI.survivalTargetDay)finishRun(true)}resourceClock+=dt;if(resourceClock>8000){resourceClock=0;spawnResources(1)}let severity=weatherList.find(a=>a[0]===weather)[1],damage=Math.max(0,severity-weatherProtection());if(damage){weatherClock+=dt;if(weatherClock>2500){weatherClock=0;p.health=Math.max(0,p.health-damage);runStats.damage.weather+=damage;toast(`${weather}伤害 ${severity}，防护 ${weatherProtection()}，健康 -${damage}`)}}enemyClock+=dt;if(enemyClock>12000){enemyClock=0;if(Math.random()<.75)spawnEnemy()}aiClock+=dt;if(aiOn&&aiClock>650){aiClock=0;aiStep()}enemyAI();if(p.path.length){let n=p.path[0],speed=dt*.006,dist=Math.hypot(n.x-p.px,n.y-p.py);if(dist<=speed){p.px=p.x=n.x;p.py=p.y=n.y;p.path.shift()}else{p.px+=(n.x-p.px)/dist*speed;p.py+=(n.y-p.py)/dist*speed}}runStats.minHealth=Math.min(runStats.minHealth,p.health);runStats.minHunger=Math.min(runStats.minHunger,p.hunger);updateStats()}draw();requestAnimationFrame(animate)}
function updateStats(){$('#healthBar').style.width=p.health+'%';$('#healthText').textContent=Math.ceil(p.health);$('#hungerBar').style.width=p.hunger+'%';$('#hungerText').textContent=Math.ceil(p.hunger);$('#dayLabel').textContent=`春 · 第 ${day} 天 · ${weather}`;if(p.health<=0&&!runEnding)finishRun(false)}
function updateUI(){let total=Object.values(inv).reduce((a,b)=>a+b,0);$('#bagCount').textContent=`${total} / 20`;$('#itemsPanel').innerHTML=`<div class="inventory">${Object.keys(defs).map(k=>inv[k]?`<div class="item"><em>${inv[k]}</em><div class="item-icon">${defs[k][1]}</div><b>${defs[k][0]}</b>${['berry','meal'].includes(k)?`<button data-eat="${k}"></button>`:''}</div>`:'<div class="item empty">·</div>').join('')}</div><p style="color:#89988e;font-size:10px">浆果可直接吃；生鱼和动物肉必须在厨房烹饪。</p>`;$('#craftPanel').innerHTML=recipes.map(r=>{let can=Object.entries(r.cost).every(([k,n])=>inv[k]>=n);return `<div class="craft-card"><div class="craft-icon">${defs[r.id][1]}</div><div><h3>${r.name}</h3><p>${r.desc}</p><div class="cost">${Object.entries(r.cost).map(([k,n])=>`<span class="${inv[k]>=n?'ok':''}">${defs[k][1]} ${inv[k]}/${n}</span>`).join('　')}</div></div><button data-craft="${r.id}" ${can?'':'disabled'}>制作</button></div>`}).join('');$('#craftBadge').textContent=recipes.filter(r=>Object.entries(r.cost).every(([k,n])=>inv[k]>=n)).length;$$('[data-eat]').forEach(b=>b.onclick=()=>eat(b.dataset.eat));$$('[data-craft]').forEach(b=>b.onclick=()=>craft(b.dataset.craft));['rod','trap','fence'].forEach(k=>$(`[data-slot="${k}"]`).classList.toggle('locked',!inv[k]))}
function eat(type){if(!inv[type])return;inv[type]--;runStats.meals++;let gain=type==='meal'?45:12;p.hunger=Math.min(100,p.hunger+gain);if(type==='meal')p.health=Math.min(100,p.health+8);toast(`${defs[type][0]}：饱食 +${gain}`);updateUI();save()}
function craft(id){let r=recipes.find(a=>a.id===id);if(!r||!Object.entries(r.cost).every(([k,n])=>inv[k]>=n))return;Object.entries(r.cost).forEach(([k,n])=>inv[k]-=n);inv[id]++;toast(`制作完成：${r.name}${r.place?'，请点击空地放置':''}`);updateUI();save();if(r.place){closeBag();setMode(id)}}
function setMode(m){if(m!=='hand'&&!inv[m])return toast(`没有${defs[m][0]}`);mode=m;$$('.quick').forEach(b=>b.classList.toggle('active',b.dataset.slot===m));hideAction();toast(m==='hand'?'攻击模式：点击相邻动物':`点击空地放置${defs[m][0]}`)}
function canCraft(id){let r=recipes.find(a=>a.id===id);return r&&Object.entries(r.cost).every(([k,n])=>inv[k]>=n)}
function nearest(list){return list.map(a=>({a,path:pathfind(a.x,a.y)})).filter(v=>v.path).sort((a,b)=>a.path.length-b.path.length)[0]}
function aiPlace(){let spots=[[1,0],[-1,0],[0,1],[0,-1]].map(([dx,dy])=>({x:p.x+dx,y:p.y+dy})).filter(a=>!occupied(a.x,a.y)&&!(a.x===p.x&&a.y===p.y));if(!spots.length){setMode('hand');return false}place(spots[0].x,spots[0].y);return true}
function aiStep(){if(p.path.length||p.health<=0)return;if(['trap','fence','door','kitchen','shelter','strongShelter'].includes(mode)&&inv[mode])return void aiPlace();let adjacent=enemies.find(e=>Math.abs(e.x-p.x)+Math.abs(e.y-p.y)===1);if(adjacent){logEvent('AI：只反击近身野猪','ai');return void attack(adjacent)}if(p.hunger<AI.eatMealBelow&&inv.meal){logEvent('AI：饥饿，食用熟食','ai');return void eat('meal')}if(p.hunger<AI.eatBerryBelow&&inv.berry){logEvent('AI：低饥饿，食用浆果','ai');return void eat('berry')}let bad=weatherList.find(a=>a[0]===weather)?.[1],shelter=structures.find(a=>['shelter','strongShelter'].includes(a.type));if(bad&&shelter&&weatherProtection()<bad){logEvent('AI：天气恶劣，前往庇护所','ai');return void nextTo(shelter.x,shelter.y)}if(enemies.some(e=>Math.abs(e.x-p.x)+Math.abs(e.y-p.y)<=AI.trapThreatDistance)&&inv.trap){logEvent('AI：威胁接近，布置陷阱','ai');setMode('trap');return}let raw=inv.fish+inv.carcass,kitchen=structures.find(a=>a.type==='kitchen');if(raw&&kitchen){if(Math.abs(kitchen.x-p.x)+Math.abs(kitchen.y-p.y)===1)return void cook();return void nextTo(kitchen.x,kitchen.y)}let target=nearest(objects.concat(drops));if(target){if(Math.abs(target.a.x-p.x)+Math.abs(target.a.y-p.y)===1)return void pickup(target.a);return void nextTo(target.a.x,target.a.y)}for(let id of AI.craftPriority)if(canCraft(id)&&(!structures.some(a=>a.type===id)&&!inv[id])){logEvent(`AI：制作${defs[id][0]}`,'ai');return void craft(id)}if(p.hunger<AI.fishBelow&&inv.rod){let shores=[];for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++)if(!map[y][x]&&[[1,0],[-1,0],[0,1],[0,-1]].some(([dx,dy])=>map[y+dy]?.[x+dx]))shores.push({x,y});let shore=nearest(shores);if(shore){if(shore.path.length===0){inv.fish++;toast('AI 钓到一条生鱼')}else p.path=shore.path}}}
function toggleAI(){aiOn=!aiOn;updateAIButton();toast(aiOn?'AI 已接管，将自动求生':'AI 已关闭，恢复手动操作')}
function updateAIButton(){let b=$('#aiButton');b.classList.toggle('on',aiOn);b.querySelector('small').textContent=aiOn?'运行中':'关闭'}
function deathCause(){let d=runStats.damage;return Object.entries(d).sort((a,b)=>b[1]-a[1])[0][0]}
function archiveRun(success){let history=JSON.parse(localStorage.getItem('island-ai-history')||'[]'),record={at:new Date().toLocaleString(),success,day,seconds:Math.floor(time/1000),cause:success?'survived':deathCause(),kills:runStats.kills,meals:runStats.meals,minHealth:Math.ceil(runStats.minHealth),minHunger:Math.ceil(runStats.minHunger),damage:Object.fromEntries(Object.entries(runStats.damage).map(([k,v])=>[k,Math.round(v)])),builds:structures.map(a=>a.type),logs:[...gameLogs]};history.unshift(record);localStorage.setItem('island-ai-history',JSON.stringify(history.slice(0,30)));renderHistory();return record}
function finishRun(success){if(runEnding)return;runEnding=true;started=false;let wasBatch=!!batchLeft,result=LOCAL_AI_LAB?archiveRun(success):{cause:deathCause()};logEvent(success?'测试达标：存活到第 4 天':`本局倒下：主要原因 ${result.cause}`,'damage');if(batchLeft){batchLeft--;$('#runTenButton').textContent=batchLeft?`测试中，还剩 ${batchLeft} 局`:'▶ 连续测试 10 局';if(batchLeft)return void setTimeout(resetRun,350)}if(wasBatch&&LOCAL_AI_LAB)renderStrategyReview();aiOn=false;updateAIButton();$('#welcome').classList.remove('closed');$('#welcome').classList.add('gameover');$('.modal h1').textContent=wasBatch?'10 局测试完成':success?'测试达标':'你倒下了';$('.modal>p').textContent=wasBatch?'十局结果已汇总，并生成了下一版策略建议。':'本局已经结束，点击下方按钮重新开始。';$('#startButton').classList.add('hidden');if(LOCAL_AI_LAB)$('#viewDeathLog').classList.remove('hidden');$('#restartButton').classList.remove('hidden');save()}
function resetRun(){objects=INITIAL_OBJECTS.map(a=>({...a}));structures=[];enemies=[];drops=[];p={x:4,y:6,px:4,py:6,path:[],health:100,hunger:80,tile:p.tile,ox:p.ox,oy:p.oy};inv=Object.fromEntries(Object.keys(defs).map(k=>[k,0]));selected=null;mode='hand';time=0;day=1;weather='晴朗';enemyClock=weatherClock=aiClock=resourceClock=0;gameLogs=[];runStats={kills:0,meals:0,damage:{enemy:0,weather:0,hunger:0},minHealth:100,minHunger:80};runEnding=false;started=true;aiOn=true;$('#welcome').classList.add('closed');$('#welcome').classList.remove('gameover');$('#viewDeathLog').classList.add('hidden');$('#restartButton').classList.add('hidden');updateAIButton();updateUI();logEvent(`自动测试开始，批次剩余 ${batchLeft||1} 局`,'ai')}
function startTenRuns(){if(!LOCAL_AI_LAB)return;batchLeft=10;logEvent('启动连续 10 局 AI 回归测试','ai');$('#logPanel').classList.remove('open');$('#scrim').classList.remove('open');resetRun()}
function renderHistory(){let history=JSON.parse(localStorage.getItem('island-ai-history')||'[]'),last=history.slice(0,10);if(!last.length){$('#runSummary').textContent='尚无历史测试结果';return}let wins=last.filter(a=>a.success).length,causes={enemy:0,weather:0,hunger:0};last.filter(a=>!a.success).forEach(a=>causes[a.cause]=(causes[a.cause]||0)+1);let names={enemy:'野猪',weather:'天气',hunger:'饥饿'};let top=Object.entries(causes).sort((a,b)=>b[1]-a[1])[0];$('#runSummary').textContent=`最近 ${last.length} 局：存活至第4天 ${wins} 局 · 平均击杀 ${(last.reduce((n,a)=>n+a.kills,0)/last.length).toFixed(1)} · 主要死因 ${names[top[0]]} ${top[1]} 局 · 点击查看最近一局`}
function showLastHistory(){let last=JSON.parse(localStorage.getItem('island-ai-history')||'[]')[0];if(!last)return;$('#logDay').textContent=`历史：${last.at} · 第 ${last.day} 天 · ${last.success?'通过':'倒下'}`;$('#logState').textContent=`击杀 ${last.kills} · 进食 ${last.meals} · 最低健康 ${last.minHealth}`;$('#logEntries').innerHTML=last.logs.map(a=>`<div class="log-entry ${a.type}"><b>${a.stamp}</b>${a.text} <small>[H${a.hp}/F${a.food}]</small></div>`).join('')}
function nextVersion(v){let a=v.split('.').map(Number);a[2]++;return a.join('.')}
function moveFirst(list,id){return[id,...list.filter(x=>x!==id)]}
function renderStrategyReview(){let runs=JSON.parse(localStorage.getItem('island-ai-history')||'[]').slice(0,10),deaths={enemy:0,weather:0,hunger:0};runs.filter(r=>!r.success).forEach(r=>deaths[r.cause]++);let top=Object.entries(deaths).sort((a,b)=>b[1]-a[1])[0][0],next={...AI,craftPriority:[...AI.craftPriority],version:nextVersion(AI.version)};if(top==='enemy'){next.trapThreatDistance=Math.min(6,AI.trapThreatDistance+1);next.craftPriority=moveFirst(next.craftPriority,'trap');next.description='降低野猪死亡：更早布置陷阱'}else if(top==='hunger'){next.eatMealBelow=Math.min(85,AI.eatMealBelow+7);next.eatBerryBelow=Math.min(70,AI.eatBerryBelow+7);next.fishBelow=Math.min(90,AI.fishBelow+8);next.craftPriority=moveFirst(moveFirst(next.craftPriority,'rod'),'kitchen');next.description='降低饥饿死亡：提前进食并优先食物链'}else{next.craftPriority=moveFirst(next.craftPriority,'shelter');next.description='降低天气死亡：优先完成庇护所'}recommendedStrategy=next;let names={enemy:'野猪',weather:'天气',hunger:'饥饿'};$('#resultTable').innerHTML=`<table><thead><tr><th>局</th><th>结果</th><th>天数</th><th>死因</th><th>最低健康</th></tr></thead><tbody>${runs.map((r,i)=>`<tr><td>${i+1}</td><td>${r.success?'通过':'失败'}</td><td>${r.day}</td><td>${r.success?'—':names[r.cause]}</td><td>${r.minHealth}</td></tr>`).join('')}</tbody></table>`;let rows=[['版本',AI.version,next.version],['熟食阈值',AI.eatMealBelow,next.eatMealBelow],['浆果阈值',AI.eatBerryBelow,next.eatBerryBelow],['钓鱼阈值',AI.fishBelow,next.fishBelow],['陷阱距离',AI.trapThreatDistance,next.trapThreatDistance],['第一建造',AI.craftPriority[0],next.craftPriority[0]]];$('#strategyDiff').innerHTML=`<p>主要死因：${names[top]}（${deaths[top]} 局）。${next.description}</p><table><tr><th>参数</th><th>当前</th><th>推荐</th></tr>${rows.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td class="${r[1]!==r[2]?'changed':''}">${r[2]}</td></tr>`).join('')}</table>`;$('#strategyReview').classList.remove('hidden');$('#strategyStatus').textContent='建议尚未应用。'}
async function applyRecommendedStrategy(){if(!LOCAL_AI_LAB||!recommendedStrategy)return;let button=$('#applyStrategyButton');button.disabled=true;$('#strategyStatus').textContent='正在写入 ai-strategy.js…';try{let res=await fetch('/__ai_strategy',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(recommendedStrategy)}),data=await res.json();if(!res.ok)throw new Error(data.error||'写入失败');Object.assign(AI,recommendedStrategy);$('#strategyStatus').textContent=`已应用 ${data.version}。下一轮测试将使用新策略。`;button.textContent='策略已更新'}catch(e){$('#strategyStatus').textContent=`无法更新：${e.message}。请确认使用 node server.js 启动本地服务。`;button.disabled=false}}
function clearHistory(){localStorage.removeItem('island-ai-history');renderHistory();logEvent('历史测试记录已清空')}
function restartGame(){['island-v3','island-save-v3','island-save'].forEach(k=>localStorage.removeItem(k));location.reload()}
function logEvent(text,type='info'){let stamp=`D${day} ${String(Math.floor((time%60000)/1000)).padStart(2,'0')}s`,entry={stamp,text,type,hp:Math.ceil(p.health),food:Math.ceil(p.hunger)};gameLogs.unshift(entry);gameLogs=gameLogs.slice(0,120);$('#logDay').textContent=`春 · 第 ${day} 天 · ${weather} · 防护 ${weatherProtection()}`;$('#logState').textContent=`健康 ${entry.hp} · 饥饿 ${entry.food}`;$('#logEntries').innerHTML=gameLogs.map(a=>`<div class="log-entry ${a.type}"><b>${a.stamp}</b>${a.text} <small>[H${a.hp}/F${a.food}]</small></div>`).join('')}
function toast(s){let e=$('#toast');e.textContent=s;e.classList.add('show');logEvent(s,/攻击|伤害|健康 -|倒下/.test(s)?'damage':s.startsWith('AI')?'ai':'info');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1800)}
function toggleLog(){$('#logPanel').classList.toggle('open');$('#scrim').classList.toggle('open',$('#logPanel').classList.contains('open'))}
function openBag(){$('#bag').classList.add('open');$('#scrim').classList.add('open');updateUI()}function closeBag(){$('#bag').classList.remove('open');$('#scrim').classList.remove('open')}
function save(){localStorage.setItem('island-v3',JSON.stringify({inv,objects,structures,drops,health:p.health,hunger:p.hunger,day,weather}))}
canvas.addEventListener('pointerup',tap);$('#bagButton').onclick=openBag;$('#aiButton').onclick=toggleAI;$('#logButton').onclick=toggleLog;$('#closeLog').onclick=toggleLog;$('#runTenButton').onclick=startTenRuns;$('#clearHistoryButton').onclick=clearHistory;$('#applyStrategyButton').onclick=applyRecommendedStrategy;$('#runSummary').onclick=showLastHistory;$('#viewDeathLog').onclick=()=>{$('#logPanel').classList.add('open')};$('#closeBag').onclick=closeBag;$('#scrim').onclick=()=>{$('#logPanel').classList.remove('open');closeBag()};$('#startButton').onclick=()=>{started=true;logEvent('游戏开始：春季第 1 天');$('#welcome').classList.add('closed')};$('#restartButton').onclick=restartGame;$$('.quick').forEach(b=>b.onclick=()=>setMode(b.dataset.slot));$$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.toggle('active',x===b));$('#itemsPanel').classList.toggle('hidden',b.dataset.tab!=='items');$('#craftPanel').classList.toggle('hidden',b.dataset.tab!=='craft')});
document.documentElement.classList.add(LOCAL_AI_LAB?'local-ai-lab':'production');window.addEventListener('resize',resize);resize();updateUI();if(LOCAL_AI_LAB)renderHistory();requestAnimationFrame(animate);if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
