const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],AI=window.AI_STRATEGY,LOCAL_AI_LAB=['localhost','127.0.0.1','::1'].includes(location.hostname);
const COLS=9,ROWS=12,map=[[1,1,1,1,1,1,1,1,1],[1,1,0,0,0,0,1,1,1],[1,0,0,0,0,0,0,1,1],[1,0,0,0,0,0,0,0,1],[1,0,0,0,0,0,0,0,1],[1,1,0,0,0,0,0,0,1],[1,1,0,0,0,0,0,1,1],[1,0,0,0,0,0,0,1,1],[1,0,0,0,0,0,0,0,1],[1,1,0,0,0,0,0,1,1],[1,1,1,0,0,0,1,1,1],[1,1,1,1,1,1,1,1,1]];
const defs={wood:['木头','🪵'],grass:['草','🌿'],berry:['浆果','🫐'],fish:['生鱼','🐟'],carcass:['动物肉','🥩'],meal:['熟食','🍲'],spear:['木矛','🗡️'],strongSpear:['加固长矛','🔱'],hunterSpear:['猎兽矛','⚔️'],rod:['鱼竿','🎣'],trap:['陷阱','⌗'],fence:['木围栏','▥'],door:['木门','▯'],kitchen:['野外厨房','♨'],fridge:['木冰箱','🧊'],bed:['木床','🛏️'],shelter:['简易棚屋','⌂'],strongShelter:['加固庇护所','🏠']};
const INITIAL_OBJECTS=[{x:3,y:2,type:'wood'},{x:5,y:2,type:'grass'},{x:6,y:3,type:'berry'},{x:2,y:4,type:'grass'},{x:5,y:4,type:'wood'},{x:6,y:5,type:'grass'},{x:3,y:7,type:'berry'},{x:5,y:7,type:'wood'},{x:6,y:8,type:'grass'},{x:2,y:8,type:'wood'},{x:4,y:9,type:'wood'},{x:5,y:9,type:'grass'}];
let objects=INITIAL_OBJECTS.map(a=>({...a})),structures=[],enemies=[],drops=[];
let p={x:4,y:6,px:4,py:6,path:[],health:100,hunger:80,tile:40,ox:0,oy:0},inv=Object.fromEntries(Object.keys(defs).map(k=>[k,0]));
let selected=null,mode='hand',started=false,aiOn=false,time=0,last=performance.now(),day=1,lastSpoilDay=1,weather='晴朗',enemyClock=0,weatherClock=0,aiClock=0,resourceClock=0,gameLogs=[],batchLeft=0,runEnding=false,recommendedStrategy=null,runStats={kills:0,meals:0,damage:{enemy:0,weather:0,hunger:0},lastDamageSource:null,minHealth:100,minHunger:80};
const weatherList=[['晴朗',0],['小雨',0],['暴雨',1],['寒风',1],['多云',0]];
const ANIMALS={boar:{name:'野猪',color:'#76523f',hp:50,damage:8,meat:2,unlock:1},wolf:{name:'灰狼',color:'#59636a',hp:80,damage:12,meat:3,unlock:5},bear:{name:'棕熊',color:'#4b3327',hp:140,damage:18,meat:5,unlock:10}};
const BASE={x:4,y:6},BASE_PLAN=[];for(let y=4;y<=8;y++)for(let x=2;x<=6;x++)if(x===2||x===6||y===4||y===8)BASE_PLAN.push({x,y,type:x===4&&y===8?'door':'fence'});
const recipes=[{id:'spear',name:'木矛',desc:'基础武器，攻击伤害 40',cost:{wood:3,grass:2},cat:'weapon'},{id:'strongSpear',name:'加固长矛',desc:'替换木矛，攻击伤害 65',cost:{spear:1,wood:5,grass:2},cat:'weapon'},{id:'hunterSpear',name:'猎兽矛',desc:'替换长矛，攻击伤害 95',cost:{strongSpear:1,wood:8,grass:4},cat:'weapon'},{id:'trap',name:'简易陷阱',desc:'自动重伤踩中的动物',cost:{wood:2,grass:3},place:1,cat:'defense'},{id:'rod',name:'粗制鱼竿',desc:'站在岸边点击水面钓鱼',cost:{wood:3,grass:2},cat:'tool'},{id:'fence',name:'简易木栏',desc:'1级耐久40；点击可升级替换',cost:{wood:2},place:1,cat:'defense'},{id:'door',name:'木门',desc:'与围栏一起封闭小屋，可通行',cost:{wood:2,grass:1},place:1,cat:'defense'},{id:'kitchen',name:'野外厨房',desc:'生鱼和动物肉只能在这里烹饪',cost:{wood:4,grass:2},place:1,cat:'facility'},{id:'fridge',name:'木冰箱',desc:'无电保鲜箱，防止生鲜每日腐坏',cost:{wood:6,grass:3},place:1,cat:'facility'},{id:'bed',name:'木床',desc:'靠近后睡觉，恢复30点健康',cost:{wood:5,grass:4},place:1,cat:'facility'},{id:'shelter',name:'简易棚屋',desc:'天气防护1',cost:{wood:6,grass:5},place:1,cat:'defense'},{id:'strongShelter',name:'加固庇护所',desc:'天气防护2',cost:{wood:10,grass:6},place:1,cat:'defense'}];
function resize(){let r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio,2);canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);p.tile=Math.floor(Math.min(r.width/COLS,r.height/ROWS));p.ox=Math.floor((r.width-p.tile*COLS)/2);p.oy=Math.floor((r.height-p.tile*ROWS)/2)}
function tileXY(x,y){return[p.ox+x*p.tile,p.oy+y*p.tile]}
function growthInfo(a){let age=Math.max(0,time-(a.born||0));if(a.type==='wood'){if(age>=60000)return{name:'成熟树',icon:'🌳',yield:7,stage:3,next:0};if(age>=35000)return{name:'小树',icon:'🌲',yield:4,stage:2,next:60000-age};if(age>=15000)return{name:'小树苗',icon:'🌱',yield:2,stage:1,next:35000-age};return{name:'断枝',icon:'🪵',yield:1,stage:0,next:15000-age}}if(a.type==='grass'){if(age>=50000)return{name:'茂盛草丛',icon:'🌾',yield:5,stage:3,next:0};if(age>=28000)return{name:'高草',icon:'🌿',yield:3,stage:2,next:50000-age};if(age>=12000)return{name:'草丛',icon:'☘️',yield:2,stage:1,next:28000-age};return{name:'嫩芽',icon:'🌱',yield:1,stage:0,next:12000-age}}return{name:defs[a.type]?.[0]||a.type,icon:defs[a.type]?.[1]||'•',yield:a.amount||1,stage:0,next:0}}
function draw(){let t=p.tile;ctx.fillStyle='#102119';ctx.fillRect(0,0,canvas.clientWidth,canvas.clientHeight);for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++){let[X,Y]=tileXY(x,y);ctx.fillStyle=map[y][x]?((x+y)%2?'#245769':'#286174'):((x+y)%2?'#476a45':'#426341');ctx.fillRect(X,Y,t,t);if(map[y][x]){ctx.fillStyle='#78b5ad66';ctx.fillRect(X+(time/90+x*7)%Math.max(8,t-8),Y+t*.35,8,2)}else{ctx.fillStyle='#6f925c';ctx.fillRect(X+7+(x*5+y*3)%12,Y+8+(x*3)%17,2,4)}ctx.strokeStyle='#203a2d';ctx.strokeRect(X+.5,Y+.5,t-1,t-1)}
 if(selected){let[X,Y]=tileXY(selected.x,selected.y);ctx.strokeStyle='#f2c96b';ctx.lineWidth=2;ctx.strokeRect(X+2,Y+2,t-4,t-4);ctx.lineWidth=1}structures.forEach(drawStructure);[...objects,...drops].forEach(drawItem);enemies.forEach(drawEnemy);drawPlayer();if(weather==='暴雨'){ctx.strokeStyle='#c3e0e477';for(let i=0;i<18;i++){let x=(i*47+time*.13)%canvas.clientWidth,y=(i*71+time*.21)%canvas.clientHeight;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-5,y+12);ctx.stroke()}}}
function drawItem(a){let[X,Y]=tileXY(a.x,a.y),t=p.tile,g=growthInfo(a);ctx.font=`${t*(g.stage>=2?.68:.52)}px sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(g.icon,X+t/2,Y+t*.5);if(['wood','grass'].includes(a.type)){ctx.fillStyle='#101812aa';ctx.fillRect(X+t*.18,Y+t*.84,t*.64,3);ctx.fillStyle=['#8da565','#a9ba69','#d0b85c','#e1c067'][g.stage];ctx.fillRect(X+t*.18,Y+t*.84,t*.64*((g.stage+1)/4),3)}}
function drawStructure(a){let[X,Y]=tileXY(a.x,a.y),t=p.tile;ctx.save();ctx.translate(X,Y);if(['fridge','bed'].includes(a.type)){ctx.font=`${t*.62}px sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(defs[a.type][1],t*.5,t*.5)}else if(a.type==='fence'){ctx.fillStyle=['#8a6138','#a87842','#65716a'][(a.level||1)-1];ctx.fillRect(t*.1,t*.3,t*.8,t*.13);ctx.fillRect(t*.1,t*.64,t*.8,t*.13);for(let i=0;i<3;i++)ctx.fillRect(t*(.15+i*.31),t*.13,t*.13,t*.72)}else if(a.type==='door'){ctx.fillStyle=['#ad7a42','#bc8b53','#68756c'][(a.level||1)-1];ctx.fillRect(t*.2,t*.12,t*.6,t*.76);ctx.fillStyle='#201811';ctx.fillRect(t*.64,t*.48,4,4)}else if(a.type==='trap'){ctx.strokeStyle='#dec477';ctx.lineWidth=3;ctx.strokeRect(t*.2,t*.2,t*.6,t*.6);ctx.beginPath();ctx.moveTo(t*.2,t*.2);ctx.lineTo(t*.8,t*.8);ctx.moveTo(t*.8,t*.2);ctx.lineTo(t*.2,t*.8);ctx.stroke()}else{ctx.fillStyle=a.type==='kitchen'?'#584638':a.type==='strongShelter'?'#53635a':'#795535';ctx.fillRect(t*.12,t*.35,t*.76,t*.52);ctx.fillStyle=a.type==='kitchen'?'#e27443':a.type==='strongShelter'?'#aeb7a9':'#c79a5d';ctx.fillRect(t*.28,t*.17,t*.44,t*.3);ctx.fillStyle='#251a14';ctx.fillRect(t*.42,t*.57,t*.18,t*.3)}ctx.restore()}
function drawEnemy(e){let[X,Y]=tileXY(e.x,e.y),t=p.tile,a=ANIMALS[e.kind]||ANIMALS.boar;ctx.fillStyle=e.hit?'#d86d57':a.color;ctx.fillRect(X+t*.18,Y+t*.4,t*.64,t*.34);ctx.fillRect(X+t*.56,Y+t*.23,t*.31,t*.3);ctx.fillStyle='#211512';ctx.fillRect(X+t*.7,Y+t*.31,3,3);ctx.fillStyle='#39201b';ctx.fillRect(X+t*.16,Y+t*.12,t*.58,4);ctx.fillStyle='#66ad63';ctx.fillRect(X+t*.16,Y+t*.12,t*.58*e.hp/(e.maxHp||50),4)}
function drawPlayer(){let[X,Y]=tileXY(p.px,p.py),t=p.tile,b=p.path.length?Math.sin(time/80)*2:0;Y+=b;ctx.fillStyle='#111b16aa';ctx.beginPath();ctx.ellipse(X+t*.5,Y+t*.82,t*.25,t*.1,0,0,7);ctx.fill();ctx.fillStyle='#283c32';ctx.fillRect(X+t*.3,Y+t*.48,t*.4,t*.36);ctx.fillStyle='#d5a06e';ctx.fillRect(X+t*.31,Y+t*.18,t*.38,t*.34);ctx.fillStyle='#3b2921';ctx.fillRect(X+t*.27,Y+t*.12,t*.46,t*.16);ctx.fillStyle='#171c19';ctx.fillRect(X+t*.4,Y+t*.3,3,3);ctx.fillRect(X+t*.59,Y+t*.3,3,3)}
function occupied(x,y,animal=false){if(x<0||y<0||x>=COLS||y>=ROWS||map[y][x])return true;if(objects.concat(drops).some(a=>a.x===x&&a.y===y))return true;if(structures.some(a=>a.x===x&&a.y===y&&a.type!=='trap'&&!(a.type==='door'&&!animal)))return true;return !animal&&enemies.some(a=>a.x===x&&a.y===y)}
function pathfind(tx,ty,animal=false,start={x:p.x,y:p.y}){let q=[start],seen=new Map([[`${start.x},${start.y}`,null]]),end;while(q.length){let a=q.shift();if(a.x===tx&&a.y===ty){end=a;break}for(let[dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){let n={x:a.x+dx,y:a.y+dy},k=`${n.x},${n.y}`;if(!seen.has(k)&&(!occupied(n.x,n.y,animal)||(n.x===tx&&n.y===ty))){seen.set(k,a);q.push(n)}}}if(!end)return null;let out=[];while(end.x!==start.x||end.y!==start.y){out.unshift(end);end=seen.get(`${end.x},${end.y}`)}return out}
function nextTo(x,y){let best=[[1,0],[-1,0],[0,1],[0,-1]].map(([dx,dy])=>({x:x+dx,y:y+dy})).filter(a=>!occupied(a.x,a.y)).map(a=>({a,path:pathfind(a.x,a.y)})).filter(a=>a.path).sort((a,b)=>a.path.length-b.path.length)[0];if(best)p.path=best.path;else toast('无法靠近目标')}
function tap(e){if(!started||p.health<=0)return;let r=canvas.getBoundingClientRect(),x=Math.floor((e.clientX-r.left-p.ox)/p.tile),y=Math.floor((e.clientY-r.top-p.oy)/p.tile);if(x<0||y<0||x>=COLS||y>=ROWS)return;selected={x,y};if(['trap','fence','door','kitchen','fridge','bed','shelter','strongShelter'].includes(mode)){place(x,y);return}let foe=enemies.find(a=>a.x===x&&a.y===y);if(foe){Math.abs(p.x-x)+Math.abs(p.y-y)===1?attack(foe):nextTo(x,y);return}let item=objects.concat(drops).find(a=>a.x===x&&a.y===y);if(item){Math.abs(p.x-x)+Math.abs(p.y-y)===1?pickupPrompt(item):nextTo(x,y);return}let build=structures.find(a=>a.x===x&&a.y===y);if(build?.type==='kitchen'&&Math.abs(p.x-x)+Math.abs(p.y-y)===1){kitchenPrompt();return}if(build?.type==='bed'&&Math.abs(p.x-x)+Math.abs(p.y-y)===1){bedPrompt();return}if(['fence','door'].includes(build?.type)&&Math.abs(p.x-x)+Math.abs(p.y-y)===1){fencePrompt(build);return}hideAction();if(map[y][x]){if(inv.rod&&Math.abs(p.x-x)+Math.abs(p.y-y)===1)fish();else toast(inv.rod?'请先站到岸边':'水里不能走，需要鱼竿');return}let path=pathfind(x,y);if(path)p.path=path;else toast('那里过不去')}
function pickupPrompt(a){let g=growthInfo(a),growing=['wood','grass'].includes(a.type);$('#actionIcon').textContent=g.icon;$('#actionTitle').textContent=`采集${g.name}`;$('#actionText').textContent=a.type==='carcass'?'必须在厨房烹饪':growing?(g.next?`现在获得 ${g.yield} 份；继续生长会增产`:`已经成熟，可获得 ${g.yield} 份`):'收入背包';$('#actionButton').textContent='采集';$('#actionButton').disabled=false;$('#actionButton').onclick=()=>pickup(a);$('#actionPrompt').classList.remove('hidden')}
function pickup(a){let pool=objects.includes(a)?objects:drops,g=growthInfo(a);pool.splice(pool.indexOf(a),1);inv[a.type]+=g.yield;toast(`采集 ${g.icon} ${g.name}，获得${defs[a.type][0]} ×${g.yield}`);hideAction();updateUI();save()}
function kitchenPrompt(){let n=inv.fish+inv.carcass;$('#actionIcon').textContent='♨';$('#actionTitle').textContent='野外厨房';$('#actionText').textContent=n?`可烹饪 ${n} 份食材`:'没有生鱼或动物肉';$('#actionButton').textContent='烹饪';$('#actionButton').disabled=!n;$('#actionButton').onclick=cook;$('#actionPrompt').classList.remove('hidden')}
function cook(){let n=inv.fish+inv.carcass;if(!n)return;inv.meal+=n;inv.fish=inv.carcass=0;toast(`得到熟食 ×${n}`);kitchenPrompt();updateUI();save()}
function bedPrompt(){$('#actionIcon').textContent='🛏️';$('#actionTitle').textContent='木床';$('#actionText').textContent=p.health>=100?'健康已经全满':'睡觉恢复 30 点健康';$('#actionButton').textContent='睡觉';$('#actionButton').disabled=p.health>=100;$('#actionButton').onclick=sleep;$('#actionPrompt').classList.remove('hidden')}
function sleep(){p.health=Math.min(100,p.health+30);p.hunger=Math.max(0,p.hunger-8);toast('休息完成：健康 +30，饥饿 -8');hideAction();save()}
function wallName(wall,level=wall.level||1){let names=wall.type==='door'?['简易木门','加固木门','强化木门']:['简易木栏','加固木栏','强化护栏'];return names[level-1]}
function fencePrompt(wall){let level=wall.level||1,cost={wood:level+2,grass:1},can=level<3&&inv.wood>=cost.wood&&inv.grass>=cost.grass;$('#actionIcon').textContent=wall.type==='door'?'▯':'▥';$('#actionTitle').textContent=`${wallName(wall)} · ${level}级`;$('#actionText').textContent=level>=3?`最高等级 · 耐久 ${Math.ceil(wall.hp)}/${wall.maxHp}`:`点击升级后直接替换为${wallName(wall,level+1)} · 需要木头 ${cost.wood}、草 1 · 当前耐久 ${Math.ceil(wall.hp)}/${wall.maxHp}`;$('#actionButton').textContent=level>=3?'已满级':'升级替换';$('#actionButton').disabled=!can;$('#actionButton').onclick=()=>upgradeWall(wall);$('#actionPrompt').classList.remove('hidden')}
function upgradeWall(wall){let level=wall.level||1;if(level>=3)return;let wood=level+2;if(inv.wood<wood||inv.grass<1)return;inv.wood-=wood;inv.grass--;wall.level=level+1;wall.maxHp=[40,100,200][level];wall.hp=wall.maxHp;toast(`已替换为${wallName(wall)}，耐久 ${wall.maxHp}`);hideAction();updateUI();save()}
function spoilRawFood(){if(structures.some(a=>a.type==='fridge'))return;let lost=0;for(let type of ['fish','carcass'])if(inv[type]>0){inv[type]--;lost++}if(lost)toast(`没有木冰箱，${lost} 份生鲜腐坏了`)}
function hideAction(){$('#actionPrompt').classList.add('hidden')}
function fish(){toast('抛下鱼线…');setTimeout(()=>{inv.fish++;toast('钓到生鱼，请带到厨房');updateUI()},1000)}
function weaponInfo(){if(inv.hunterSpear)return{name:'猎兽矛',icon:'⚔️',damage:95};if(inv.strongSpear)return{name:'加固长矛',icon:'🔱',damage:65};if(inv.spear)return{name:'木矛',icon:'🗡️',damage:40};return{name:'徒手',icon:'✊',damage:15}}
function attack(e){let animal=ANIMALS[e.kind]||ANIMALS.boar,weapon=weaponInfo();e.hp-=weapon.damage;e.hit=true;setTimeout(()=>e.hit=false,120);toast(`${weapon.name}攻击${animal.name}，伤害 ${weapon.damage}`);if(e.hp<=0){runStats.kills++;enemies.splice(enemies.indexOf(e),1);drops.push({x:e.x,y:e.y,type:'carcass',amount:animal.meat});toast(`击败${animal.name}，掉落生肉 ×${animal.meat}`)}}
function place(x,y){if(!inv[mode])return setMode('hand');if(occupied(x,y)||structures.some(a=>a.x===x&&a.y===y)||p.x===x&&p.y===y)return toast('这里不能建造');let building={x,y,type:mode};if(['fence','door'].includes(mode))Object.assign(building,{level:1,hp:40,maxHp:40});structures.push(building);inv[mode]--;toast(`已放置${defs[mode][0]}`);setMode('hand');updateUI();save()}
function spawnEnemy(){let spots=[];for(let y=1;y<ROWS-1;y++)for(let x=1;x<COLS-1;x++)if(!occupied(x,y,true)&&Math.abs(x-p.x)+Math.abs(y-p.y)>5)spots.push({x,y});let maxEnemies=Math.min(6,3+Math.floor(day/4));if(!spots.length||enemies.length>=maxEnemies)return;let pool=Object.entries(ANIMALS).filter(([,a])=>day>=a.unlock),kind=pool[Math.floor(Math.random()*pool.length)][0],animal=ANIMALS[kind],spot=spots[Math.floor(Math.random()*spots.length)],hp=animal.hp+Math.floor((day-animal.unlock)/5)*10;enemies.push({...spot,kind,hp,maxHp:hp,lastMove:time,lastAttack:0,hit:false});toast(`⚠ ${animal.name}出现！${hp} 生命`)}
function spawnResources(count=1){const MAX=14;if(objects.length>=MAX)return 0;let empty=[];for(let y=1;y<ROWS-1;y++)for(let x=1;x<COLS-1;x++)if(!map[y][x]&&!occupied(x,y)&&!(p.x===x&&p.y===y))empty.push({x,y});let added=0;while(count--&&empty.length&&objects.length<MAX){let inside=empty.filter(a=>a.x>=3&&a.x<=5&&a.y>=5&&a.y<=7),pool=inside.length&&Math.random()<.45?inside:empty,spot=pool[Math.floor(Math.random()*pool.length)],index=empty.findIndex(a=>a.x===spot.x&&a.y===spot.y);empty.splice(index,1);let roll=Math.random(),type=roll<.42?'wood':roll<.77?'grass':'berry';objects.push({...spot,type,born:time});added++}if(added)save();return added}
function enclosedByFence(){let q=[{x:p.x,y:p.y}],seen=new Set([`${p.x},${p.y}`]);while(q.length){let a=q.shift();for(let[dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){let x=a.x+dx,y=a.y+dy;if(x<0||y<0||x>=COLS||y>=ROWS||map[y][x])return false;let wall=structures.some(s=>s.x===x&&s.y===y&&['fence','door'].includes(s.type));if(wall)continue;let k=`${x},${y}`;if(!seen.has(k)){seen.add(k);q.push({x,y});if(seen.size>24)return false}}}return structures.some(s=>s.type==='door')&&structures.filter(s=>s.type==='fence').length>=3}
function weatherProtection(){let strength=enclosedByFence()?1:0;if(structures.some(a=>a.type==='shelter'&&Math.abs(a.x-p.x)+Math.abs(a.y-p.y)<=1))strength=Math.max(strength,1);if(structures.some(a=>a.type==='strongShelter'&&Math.abs(a.x-p.x)+Math.abs(a.y-p.y)<=1))strength=Math.max(strength,2);return strength}
function enemyAI(){for(let e of [...enemies]){if(time-e.lastMove<750)continue;e.lastMove=time;let animal=ANIMALS[e.kind]||ANIMALS.boar,d=Math.abs(e.x-p.x)+Math.abs(e.y-p.y);if(d===1){if(time-e.lastAttack>1200){let hit=animal.damage+Math.floor((day-animal.unlock)/4)*2;e.lastAttack=time;p.health=Math.max(0,p.health-hit);runStats.damage.enemy+=hit;runStats.lastDamageSource='enemy';toast(`${animal.name}攻击！健康 -${hit}`)}continue}let path=pathfind(p.x,p.y,true,{x:e.x,y:e.y});if(!path?.length){let wall=structures.find(s=>['fence','door'].includes(s.type)&&Math.abs(s.x-e.x)+Math.abs(s.y-e.y)===1);if(wall){wall.hp=(wall.hp??40)-animal.damage;toast(`${animal.name}攻击${defs[wall.type][0]}，耐久 -${animal.damage}`);if(wall.hp<=0){structures.splice(structures.indexOf(wall),1);toast(`${defs[wall.type][0]}被摧毁！`)}}continue}let n=path[0];if(n.x===p.x&&n.y===p.y)continue;e.x=n.x;e.y=n.y;let trap=structures.find(a=>a.x===e.x&&a.y===e.y&&a.type==='trap');if(trap){structures.splice(structures.indexOf(trap),1);e.hp-=50;toast(`陷阱命中${animal.name}！`);if(e.hp<=0){runStats.kills++;enemies.splice(enemies.indexOf(e),1);drops.push({x:e.x,y:e.y,type:'carcass',amount:animal.meat})}}}}
function animate(now){let dt=Math.min(40,now-last)*(batchLeft?AI.testSpeed:1);last=now;time+=dt;if(started&&p.health>0){p.hunger=Math.max(0,p.hunger-dt*.00055);if(!p.hunger){let loss=dt*.001;p.health=Math.max(0,p.health-loss);runStats.damage.hunger+=loss;runStats.lastDamageSource='hunger'}let d=Math.floor(time/60000)+1;if(d!==day){day=d;weather=weatherList[Math.floor(Math.random()*weatherList.length)][0];let grown=spawnResources(4);toast(`春 · 第 ${day} 天：${weather}，新生物资 ${grown} 份`)}resourceClock+=dt;if(resourceClock>8000){resourceClock=0;spawnResources(1)}let baseSeverity=weatherList.find(a=>a[0]===weather)[1],severity=baseSeverity?baseSeverity+Math.floor((day-1)/5):0,damage=Math.max(0,severity-weatherProtection());if(damage){weatherClock+=dt;if(weatherClock>2500){weatherClock=0;p.health=Math.max(0,p.health-damage);runStats.damage.weather+=damage;runStats.lastDamageSource='weather';toast(`${weather}伤害 ${severity}，防护 ${weatherProtection()}，健康 -${damage}`)}}enemyClock+=dt;if(enemyClock>12000){enemyClock=0;if(Math.random()<.75)spawnEnemy()}aiClock+=dt;if(aiOn&&aiClock>650){aiClock=0;aiStep()}enemyAI();if(p.path.length){let n=p.path[0],speed=dt*.006,dist=Math.hypot(n.x-p.px,n.y-p.py);if(dist<=speed){p.px=p.x=n.x;p.py=p.y=n.y;p.path.shift()}else{p.px+=(n.x-p.px)/dist*speed;p.py+=(n.y-p.py)/dist*speed}}runStats.minHealth=Math.min(runStats.minHealth,p.health);runStats.minHunger=Math.min(runStats.minHunger,p.hunger);updateStats()}draw();requestAnimationFrame(animate)}
function updateStats(){$('#healthBar').style.width=p.health+'%';$('#healthText').textContent=Math.ceil(p.health);$('#hungerBar').style.width=p.hunger+'%';$('#hungerText').textContent=Math.ceil(p.hunger);$('#dayLabel').textContent=`春 · 第 ${day} 天 · ${weather}`;if(day>lastSpoilDay){lastSpoilDay=day;spoilRawFood();updateUI()}if(p.health<=0&&!runEnding)finishRun(false)}
function inventoryGroup(title,keys,note=''){let filled=keys.filter(k=>inv[k]);return `<h3 style="font-size:10px;color:#d6bd7c;margin:10px 0 6px">${title}</h3><div class="inventory">${filled.length?filled.map(k=>`<div class="item"><em>${inv[k]}</em><div class="item-icon">${defs[k][1]}</div><b>${defs[k][0]}</b>${['berry','meal'].includes(k)?`<button data-eat="${k}"></button>`:''}</div>`).join(''):'<div class="item empty">暂无</div>'}</div>${note?`<p style="color:#89988e;font-size:9px">${note}</p>`:''}`}
function craftGroup(title,cat){let list=recipes.filter(r=>r.cat===cat);return `<section class="craft-group"><h3>${title}</h3>${list.map(r=>{let can=Object.entries(r.cost).every(([k,n])=>inv[k]>=n);return `<div class="craft-card"><div class="craft-icon">${defs[r.id][1]}</div><div><h3>${r.name}</h3><p>${r.desc}</p><div class="cost">${Object.entries(r.cost).map(([k,n])=>`<span class="${inv[k]>=n?'ok':''}">${defs[k][1]} ${inv[k]}/${n}</span>`).join('　')}</div></div><button data-craft="${r.id}" ${can?'':'disabled'}>制作</button></div>`}).join('')}</section>`}
function updateUI(){let total=Object.values(inv).reduce((a,b)=>a+b,0),other=Object.keys(defs).filter(k=>!['berry','fish','carcass','meal'].includes(k)),weapon=weaponInfo(),hand=$('[data-slot="hand"]');$('#bagCount').textContent=`${total} / 24`;$('#itemsPanel').innerHTML=inventoryGroup('可直接食用',['berry'],'浆果无需加工。')+inventoryGroup('生鲜 · 不可直接食用',['fish','carcass'],'必须靠近厨房烹饪；没有木冰箱时每天腐坏一份。')+inventoryGroup('熟食',['meal'],'熟食可以安全食用并恢复健康。')+inventoryGroup('材料与装备',other);$('#craftPanel').innerHTML=craftGroup('⚔ 武器','weapon')+craftGroup('🛠 工具','tool')+craftGroup('🛡 防御建筑','defense')+craftGroup('🏕 生活设施','facility');$('#craftBadge').textContent=recipes.filter(r=>Object.entries(r.cost).every(([k,n])=>inv[k]>=n)).length;hand.querySelector('span').textContent=weapon.icon;hand.querySelector('small').textContent=weapon.name;$$('[data-eat]').forEach(b=>b.onclick=()=>eat(b.dataset.eat));$$('[data-craft]').forEach(b=>b.onclick=()=>craft(b.dataset.craft));['rod','trap','fence'].forEach(k=>$(`[data-slot="${k}"]`).classList.toggle('locked',!inv[k]))}
function eat(type){if(!inv[type])return;inv[type]--;runStats.meals++;let gain=type==='meal'?45:12;p.hunger=Math.min(100,p.hunger+gain);if(type==='meal')p.health=Math.min(100,p.health+8);toast(`${defs[type][0]}：饱食 +${gain}`);updateUI();save()}
function craft(id){let r=recipes.find(a=>a.id===id);if(!r||!Object.entries(r.cost).every(([k,n])=>inv[k]>=n))return;Object.entries(r.cost).forEach(([k,n])=>inv[k]-=n);inv[id]++;toast(`制作完成：${r.name}${r.place?'，请点击空地放置':''}`);updateUI();save();if(r.place){closeBag();setMode(id);if(aiOn)aiPlace()}}
function setMode(m){if(m!=='hand'&&!inv[m])return toast(`没有${defs[m][0]}`);mode=m;$$('.quick').forEach(b=>b.classList.toggle('active',b.dataset.slot===m));hideAction();toast(m==='hand'?'攻击模式：点击相邻动物':`点击空地放置${defs[m][0]}`)}
function canCraft(id){let r=recipes.find(a=>a.id===id);return r&&Object.entries(r.cost).every(([k,n])=>inv[k]>=n)}
function nearest(list){return list.map(a=>({a,path:pathfind(a.x,a.y)})).filter(v=>v.path).map(v=>({...v,score:v.path.length-(objects.includes(v.a)?growthInfo(v.a).yield*AI.growthValueWeight:0)})).sort((a,b)=>a.score-b.score)[0]}
function structureAt(x,y,type){return structures.some(a=>a.x===x&&a.y===y&&(!type||a.type===type))}
function nextBasePart(){return BASE_PLAN.find(a=>!structureAt(a.x,a.y,a.type))}
function waterEdge(x,y){return[[1,0],[-1,0],[0,1],[0,-1]].some(([dx,dy])=>map[y+dy]?.[x+dx])}
function safeUtilitySpot(){let choices=[{x:3,y:5},{x:4,y:5},{x:5,y:5},{x:3,y:6},{x:5,y:6},{x:3,y:7},{x:4,y:7},{x:5,y:7},{x:7,y:7},{x:7,y:8}];return choices.find(a=>!occupied(a.x,a.y)&&!structureAt(a.x,a.y)&&!(p.x===a.x&&p.y===a.y)&&!waterEdge(a.x,a.y)&&!BASE_PLAN.some(b=>b.x===a.x&&b.y===a.y))}
function aiPlace(){if(mode==='trap'){let nearestEnemy=enemies.map(e=>({e,d:Math.abs(e.x-p.x)+Math.abs(e.y-p.y)})).sort((a,b)=>a.d-b.d)[0]?.e,path=nearestEnemy&&pathfind(p.x,p.y,true,{x:nearestEnemy.x,y:nearestEnemy.y}),spot=path?.find(a=>!(a.x===p.x&&a.y===p.y)&&!occupied(a.x,a.y,true)&&!structureAt(a.x,a.y));if(spot){logEvent(`AI：预测动物路线，在 ${spot.x},${spot.y} 放陷阱`,'ai');place(spot.x,spot.y);return true}}if(['fence','door'].includes(mode)){let part=nextBasePart();if(part&&part.type===mode&&!occupied(part.x,part.y)&&!structureAt(part.x,part.y)){logEvent(`AI：按基地蓝图建造 ${mode} ${part.x},${part.y}`,'ai');place(part.x,part.y);return true}}if(['kitchen','fridge','bed','shelter','strongShelter'].includes(mode)){let spot=safeUtilitySpot();if(spot){logEvent(`AI：避开水边放置${defs[mode][0]}`,'ai');place(spot.x,spot.y);return true}}setMode('hand');return false}
function aiStep(){if(p.path.length||p.health<=0)return;if(['trap','fence','door','kitchen','shelter','strongShelter'].includes(mode)&&inv[mode])return void aiPlace();let adjacent=enemies.find(e=>Math.abs(e.x-p.x)+Math.abs(e.y-p.y)===1);if(adjacent){logEvent('AI：反击近身野猪','ai');return void attack(adjacent)}if(p.hunger<AI.eatMealBelow&&inv.meal)return logEvent('AI：饥饿，食用熟食','ai'),void eat('meal');if(p.hunger<AI.eatBerryBelow&&inv.berry)return logEvent('AI：低饥饿，食用浆果','ai'),void eat('berry');let bad=weatherList.find(a=>a[0]===weather)?.[1],shelter=structures.find(a=>['shelter','strongShelter'].includes(a.type));if(bad&&shelter&&weatherProtection()<bad)return logEvent('AI：天气恶劣，前往庇护所','ai'),void nextTo(shelter.x,shelter.y);let threat=enemies.some(e=>Math.abs(e.x-p.x)+Math.abs(e.y-p.y)<=AI.trapThreatDistance);if(threat){if(inv.trap){logEvent('AI：野猪进入警戒区，准备路径陷阱','ai');setMode('trap');return}if(canCraft('trap')){logEvent('AI：优先制作反野猪陷阱','ai');craft('trap');return}}let raw=inv.fish+inv.carcass,kitchen=structures.find(a=>a.type==='kitchen');if(raw&&kitchen){if(Math.abs(kitchen.x-p.x)+Math.abs(kitchen.y-p.y)===1)return void cook();return void nextTo(kitchen.x,kitchen.y)}if(!kitchen){if(inv.kitchen)return void setMode('kitchen');if(canCraft('kitchen'))return logEvent('AI：建设食物基础设施','ai'),void craft('kitchen')}if(AI.buildShelterBeforeBase&&!structures.some(a=>a.type==='shelter')){if(inv.shelter)return void setMode('shelter');if(canCraft('shelter'))return void craft('shelter')}let part=nextBasePart();if(part){let blocker=objects.concat(drops).find(a=>a.x===part.x&&a.y===part.y);if(blocker){if(Math.abs(blocker.x-p.x)+Math.abs(blocker.y-p.y)===1)return void pickup(blocker);return void nextTo(blocker.x,blocker.y)}if(inv[part.type])return void setMode(part.type);if(canCraft(part.type))return logEvent(`AI：为封闭基地制作${defs[part.type][0]}`,'ai'),void craft(part.type)}if(!structures.some(a=>a.type==='shelter')){if(inv.shelter)return void setMode('shelter');if(canCraft('shelter'))return void craft('shelter')}let target=nearest(objects.concat(drops));if(target){if(Math.abs(target.a.x-p.x)+Math.abs(target.a.y-p.y)===1)return void pickup(target.a);return void nextTo(target.a.x,target.a.y)}if(!inv.rod&&canCraft('rod'))return void craft('rod');if(p.hunger<AI.fishBelow&&inv.rod){let shores=[];for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++)if(!map[y][x]&&[[1,0],[-1,0],[0,1],[0,-1]].some(([dx,dy])=>map[y+dy]?.[x+dx]))shores.push({x,y});let shore=nearest(shores);if(shore){if(shore.path.length===0){inv.fish++;toast('AI 钓到一条生鱼')}else p.path=shore.path}}}
const coreAiStep=aiStep;
function aiGatherMaterials(){let target=nearest(objects);if(!target)return false;if(Math.abs(target.a.x-p.x)+Math.abs(target.a.y-p.y)===1)pickup(target.a);else nextTo(target.a.x,target.a.y);return true}
aiStep=function(){if(p.path.length||p.health<=0)return;let adjacent=enemies.find(e=>Math.abs(e.x-p.x)+Math.abs(e.y-p.y)===1);if(adjacent)return void attack(adjacent);if(p.hunger<AI.eatMealBelow&&inv.meal)return void eat('meal');if(p.hunger<AI.eatBerryBelow&&inv.berry)return void eat('berry');let kitchen=structures.find(a=>a.type==='kitchen');if(!kitchen){if(inv.kitchen){setMode('kitchen');aiPlace();return}if(canCraft('kitchen')){logEvent('AI里程碑 1：优先完成厨房','ai');craft('kitchen');return}aiGatherMaterials();return}let bed=structures.find(a=>a.type==='bed');if(!bed){if(inv.bed){setMode('bed');aiPlace();return}if(canCraft('bed')){logEvent('AI里程碑 2：厨房后立即制作木床','ai');craft('bed');return}aiGatherMaterials();return}let weaponGoal=!inv.spear&&!inv.strongSpear&&!inv.hunterSpear?'spear':day>=(AI.weapon3Day||10)&&!inv.hunterSpear?'hunterSpear':day>=(AI.weapon2Day||5)&&!inv.strongSpear&&!inv.hunterSpear?'strongSpear':null;if(weaponGoal){if(canCraft(weaponGoal)){logEvent(`AI武器里程碑：制作${defs[weaponGoal][0]}`,'ai');craft(weaponGoal)}else aiGatherMaterials();return}if(p.health<AI.bedHealthBelow){if(Math.abs(bed.x-p.x)+Math.abs(bed.y-p.y)===1){logEvent('AI：生命偏低，使用床休息','ai');sleep()}else nextTo(bed.x,bed.y);return}let raw=inv.fish+inv.carcass;if(raw>=2&&!structures.some(a=>a.type==='fridge')){if(inv.fridge){setMode('fridge');aiPlace();return}if(canCraft('fridge')){logEvent('AI里程碑 3：制作木冰箱保存生鲜','ai');craft('fridge');return}}let targetLevel=day>=AI.wallLevel3Day?3:day>=AI.wallLevel2Day?2:1,weakWall=structures.find(a=>['fence','door'].includes(a.type)&&(a.level||1)<targetLevel);if(weakWall){let need=(weakWall.level||1)+2;if(inv.wood>=need&&inv.grass>=1){logEvent(`AI：升级防线到 ${targetLevel} 级`,'ai');upgradeWall(weakWall)}else aiGatherMaterials();return}coreAiStep()}
function toggleAI(){aiOn=!aiOn;updateAIButton();toast(aiOn?'AI 已接管，将自动求生':'AI 已关闭，恢复手动操作')}
function updateAIButton(){let b=$('#aiButton');b.classList.toggle('on',aiOn);b.querySelector('small').textContent=aiOn?'运行中':'关闭'}
function mainDamageCause(){return Object.entries(runStats.damage).sort((a,b)=>b[1]-a[1])[0][0]}
function deathCause(){return runStats.lastDamageSource||mainDamageCause()}
function weatherDiagnosis(){let base=weatherList.find(a=>a[0]===weather)?.[1]||0,severity=base?base+Math.floor((day-1)/5):0,protection=weatherProtection(),enclosed=enclosedByFence(),hasShelter=structures.some(a=>['shelter','strongShelter'].includes(a.type)),reason=protection>=severity?'防护充足':!enclosed&&!hasShelter?'尚未建造房屋或庇护所':protection===0?'已有设施，但角色不在防护范围内':`防护 ${protection} 低于天气强度 ${severity}`;return{weather,severity,protection,enclosed,hasShelter,reason}}
function archiveRun(success){let history=JSON.parse(localStorage.getItem('island-ai-history')||'[]'),record={at:new Date().toLocaleString(),strategyVersion:AI.version,strategy:{...AI,craftPriority:[...AI.craftPriority]},success,day,seconds:Math.floor(time/1000),cause:success?'survived':deathCause(),mainDamage:mainDamageCause(),weatherReport:weatherDiagnosis(),kills:runStats.kills,meals:runStats.meals,minHealth:Math.ceil(runStats.minHealth),minHunger:Math.ceil(runStats.minHunger),damage:Object.fromEntries(Object.entries(runStats.damage).map(([k,v])=>[k,Math.round(v)])),builds:structures.map(a=>a.type),logs:[...gameLogs]};history.unshift(record);localStorage.setItem('island-ai-history',JSON.stringify(history.slice(0,50)));renderHistory();return record}
function finishRun(success){if(runEnding)return;runEnding=true;started=false;let wasBatch=!!batchLeft,result=LOCAL_AI_LAB?archiveRun(success):{cause:deathCause()};logEvent(success?'测试达标：存活到第 4 天':`本局倒下：主要原因 ${result.cause}`,'damage');if(batchLeft){batchLeft--;$('#runTenButton').textContent=batchLeft?`测试中，还剩 ${batchLeft} 局`:'▶ 连续测试 10 局';if(batchLeft)return void setTimeout(resetRun,350)}if(wasBatch&&LOCAL_AI_LAB)renderStrategyReview();aiOn=false;updateAIButton();$('#welcome').classList.remove('closed');$('#welcome').classList.add('gameover');$('.modal h1').textContent=wasBatch?'10 局测试完成':success?'测试达标':'你倒下了';$('.modal>p').textContent=wasBatch?'十局结果已汇总，并生成了下一版策略建议。':'本局已经结束，点击下方按钮重新开始。';$('#startButton').classList.add('hidden');if(LOCAL_AI_LAB)$('#viewDeathLog').classList.remove('hidden');$('#restartButton').classList.remove('hidden');save()}
function resetRun(){objects=INITIAL_OBJECTS.map(a=>({...a}));structures=[];enemies=[];drops=[];p={x:4,y:6,px:4,py:6,path:[],health:100,hunger:80,tile:p.tile,ox:p.ox,oy:p.oy};inv=Object.fromEntries(Object.keys(defs).map(k=>[k,0]));selected=null;mode='hand';time=0;day=lastSpoilDay=1;weather='晴朗';enemyClock=weatherClock=aiClock=resourceClock=0;gameLogs=[];runStats={kills:0,meals:0,damage:{enemy:0,weather:0,hunger:0},lastDamageSource:null,minHealth:100,minHunger:80};runEnding=false;started=true;aiOn=true;$('#welcome').classList.add('closed');$('#welcome').classList.remove('gameover');$('#viewDeathLog').classList.add('hidden');$('#restartButton').classList.add('hidden');updateAIButton();updateUI();logEvent(`自动测试开始，批次剩余 ${batchLeft||1} 局`,'ai')}
function startTenRuns(){if(!LOCAL_AI_LAB)return;batchLeft=10;recommendedStrategy=null;let button=$('#applyStrategyButton');button.disabled=false;button.dataset.applied='';button.textContent='应用推荐策略并更新文件';$('#strategyReview').classList.add('hidden');logEvent(`启动策略 v${AI.version} 的连续 10 局测试`,'ai');$('#logPanel').classList.remove('open');$('#scrim').classList.remove('open');resetRun()}
function renderHistory(){let history=JSON.parse(localStorage.getItem('island-ai-history')||'[]'),last=history.slice(0,10);if(!last.length){$('#runSummary').textContent='尚无历史测试结果';return}let days=last.map(a=>a.day).sort((a,b)=>a-b),avg=(days.reduce((a,b)=>a+b,0)/days.length).toFixed(1),median=days[Math.floor(days.length/2)],causes={enemy:0,weather:0,hunger:0};last.forEach(a=>causes[a.cause]=(causes[a.cause]||0)+1);let names={enemy:'野猪',weather:'天气',hunger:'饥饿'},top=Object.entries(causes).sort((a,b)=>b[1]-a[1])[0],version=last[0].strategyVersion||'旧版';$('#runSummary').textContent=`策略 v${version} · ${last.length} 局：平均 ${avg} 天 · 中位数 ${median} 天 · 最长 ${Math.max(...days)} 天 · 主要死因 ${names[top[0]]} ${top[1]} 局`}
function showLastHistory(){let last=JSON.parse(localStorage.getItem('island-ai-history')||'[]')[0];if(!last)return;let n={enemy:'动物',weather:'天气',hunger:'饥饿',survived:'通过'},report=last.weatherReport,diagnosis=last.cause==='weather'&&report?` · 诊断：${report.reason}`:'';$('#logDay').textContent=`历史：${last.at} · 第 ${last.day} 天 · 致命原因 ${n[last.cause]||last.cause}`;$('#logState').textContent=`累计伤害：动物 ${last.damage.enemy} · 天气 ${last.damage.weather} · 饥饿 ${last.damage.hunger}${diagnosis}`;$('#logEntries').innerHTML=last.logs.map(a=>`<div class="log-entry ${a.type}"><b>${a.stamp}</b>${a.text} <small>[H${a.hp}/F${a.food}]</small></div>`).join('')}
function nextVersion(v){let a=v.split('.').map(Number);a[2]++;return a.join('.')}
function moveFirst(list,id){return[id,...list.filter(x=>x!==id)]}
function renderStrategyReview(){let runs=JSON.parse(localStorage.getItem('island-ai-history')||'[]').slice(0,10),deaths={enemy:0,weather:0,hunger:0};runs.forEach(r=>deaths[r.cause]=(deaths[r.cause]||0)+1);let top=Object.entries(deaths).sort((a,b)=>b[1]-a[1])[0][0],next={...AI,craftPriority:[...AI.craftPriority],version:nextVersion(AI.version)};if(top==='enemy'){next.trapThreatDistance=Math.min(6,AI.trapThreatDistance+1);next.description='降低野猪死亡：扩大路径陷阱警戒范围'}else if(top==='hunger'){next.eatMealBelow=Math.min(85,AI.eatMealBelow+7);next.eatBerryBelow=Math.min(70,AI.eatBerryBelow+7);next.fishBelow=Math.min(90,AI.fishBelow+8);next.description='降低饥饿死亡：提前进食和钓鱼'}else{next.buildShelterBeforeBase=true;next.description='降低天气死亡：围墙完成前先造棚屋'}recommendedStrategy=next;let names={enemy:'野猪',weather:'天气',hunger:'饥饿'},days=runs.map(r=>r.day),avg=(days.reduce((a,b)=>a+b,0)/days.length).toFixed(1);$('#resultTable').innerHTML=`<table><thead><tr><th>局</th><th>存活天数</th><th>致命原因</th><th>主要累计伤害</th></tr></thead><tbody>${runs.map((r,i)=>`<tr><td>${i+1}</td><td>${r.day}</td><td>${names[r.cause]}</td><td>${names[r.mainDamage||r.cause]}</td></tr>`).join('')}</tbody></table><p>平均 ${avg} 天 · 最长 ${Math.max(...days)} 天</p>`;let rows=[['版本',AI.version,next.version],['熟食阈值',AI.eatMealBelow,next.eatMealBelow],['浆果阈值',AI.eatBerryBelow,next.eatBerryBelow],['钓鱼阈值',AI.fishBelow,next.fishBelow],['陷阱距离',AI.trapThreatDistance,next.trapThreatDistance],['先造棚屋',AI.buildShelterBeforeBase?'是':'否',next.buildShelterBeforeBase?'是':'否']];$('#strategyDiff').innerHTML=`<p>主要致命原因：${names[top]}（${deaths[top]} 局）。${next.description}</p><table><tr><th>参数</th><th>当前</th><th>推荐</th></tr>${rows.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td class="${r[1]!==r[2]?'changed':''}">${r[2]}</td></tr>`).join('')}</table>`;$('#strategyReview').classList.remove('hidden');$('#strategyStatus').textContent='建议尚未应用。'}
function strategySignature(s){let copy={...s};delete copy.version;delete copy.description;return JSON.stringify(copy)}
const heuristicStrategyReview=renderStrategyReview;
renderStrategyReview=function(){heuristicStrategyReview();let runs=JSON.parse(localStorage.getItem('island-ai-history')||'[]').slice(0,10),avg=runs.reduce((n,r)=>n+r.day,0)/runs.length,champion=JSON.parse(localStorage.getItem('island-ai-champion')||'null'),current={...AI,craftPriority:[...AI.craftPriority]},sameChampion=champion&&strategySignature(champion.strategy)===strategySignature(current),rejected=JSON.parse(localStorage.getItem('island-ai-rejected')||'[]');if(!champion||avg>champion.avg){champion={avg,strategy:current,version:AI.version};localStorage.setItem('island-ai-champion',JSON.stringify(champion));$('#strategyStatus').textContent=`当前策略成为冠军：平均生存 ${avg.toFixed(1)} 天。建议测试下一候选。`}else if(!sameChampion&&avg<=champion.avg){rejected.push(strategySignature(current));localStorage.setItem('island-ai-rejected',JSON.stringify(rejected.slice(-20)));recommendedStrategy={...champion.strategy,craftPriority:[...champion.strategy.craftPriority],version:nextVersion(AI.version),description:`候选策略退步，回滚冠军 v${champion.version}`};$('#strategyDiff').insertAdjacentHTML('afterbegin',`<p class="damage">本代平均 ${avg.toFixed(1)} 天，低于冠军 ${champion.avg.toFixed(1)} 天。拒绝本代并回滚，不会继续重复。</p>`);$('#strategyStatus').textContent='推荐操作：回滚到冠军策略。'}else if(sameChampion&&rejected.includes(strategySignature(recommendedStrategy))){recommendedStrategy.bedHealthBelow=Math.min(90,(AI.bedHealthBelow||75)+5);recommendedStrategy.wallLevel2Day=Math.max(2,(AI.wallLevel2Day||5)-1);recommendedStrategy.growthValueWeight=Number(((AI.growthValueWeight||1.5)+.25).toFixed(2));recommendedStrategy.description='避开已失败候选：更早休息、更早升级围栏、提高成熟资源价值';$('#strategyStatus').textContent='原建议曾失败，已自动换用不同的候选策略。'}}
async function applyRecommendedStrategy(){let button=$('#applyStrategyButton');if(button.dataset.applied)return startTenRuns();if(!LOCAL_AI_LAB||!recommendedStrategy)return;button.disabled=true;$('#strategyStatus').textContent='正在写入 ai-strategy.js…';try{let res=await fetch('/__ai_strategy',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(recommendedStrategy)}),data=await res.json();if(!res.ok)throw new Error(data.error||'写入失败');Object.assign(AI,recommendedStrategy);$('#strategyStatus').textContent=`已应用 v${data.version}。可以立即用新策略进行下一代测试。`;button.dataset.applied='1';button.disabled=false;button.textContent=`用 v${data.version} 继续测试 10 局`}catch(e){$('#strategyStatus').textContent=`无法更新：${e.message}。请确认使用 node server.js 启动本地服务。`;button.disabled=false}}
function clearHistory(){localStorage.removeItem('island-ai-history');renderHistory();logEvent('历史测试记录已清空')}
function restartGame(){['island-v3','island-save-v3','island-save'].forEach(k=>localStorage.removeItem(k));location.reload()}
function logEvent(text,type='info'){let stamp=`D${day} ${String(Math.floor((time%60000)/1000)).padStart(2,'0')}s`,entry={stamp,text,type,hp:Math.ceil(p.health),food:Math.ceil(p.hunger)};gameLogs.unshift(entry);gameLogs=gameLogs.slice(0,120);$('#logDay').textContent=`春 · 第 ${day} 天 · ${weather} · 防护 ${weatherProtection()}`;$('#logState').textContent=`健康 ${entry.hp} · 饥饿 ${entry.food}`;$('#logEntries').innerHTML=gameLogs.map(a=>`<div class="log-entry ${a.type}"><b>${a.stamp}</b>${a.text} <small>[H${a.hp}/F${a.food}]</small></div>`).join('')}
function toast(s){let e=$('#toast');e.textContent=s;e.classList.add('show');logEvent(s,/攻击|伤害|健康 -|倒下/.test(s)?'damage':s.startsWith('AI')?'ai':'info');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1800)}
function toggleLog(){$('#logPanel').classList.toggle('open');$('#scrim').classList.toggle('open',$('#logPanel').classList.contains('open'))}
function openBag(){$('#bag').classList.add('open');$('#scrim').classList.add('open');updateUI()}function closeBag(){$('#bag').classList.remove('open');$('#scrim').classList.remove('open')}
function save(){localStorage.setItem('island-v3',JSON.stringify({inv,objects,structures,drops,health:p.health,hunger:p.hunger,day,weather}))}
canvas.addEventListener('pointerup',tap);$('#bagButton').onclick=openBag;$('#aiButton').onclick=toggleAI;$('#logButton').onclick=toggleLog;$('#closeLog').onclick=toggleLog;$('#runTenButton').onclick=startTenRuns;$('#clearHistoryButton').onclick=clearHistory;$('#applyStrategyButton').onclick=applyRecommendedStrategy;$('#runSummary').onclick=showLastHistory;$('#viewDeathLog').onclick=()=>{$('#logPanel').classList.add('open')};$('#closeBag').onclick=closeBag;$('#scrim').onclick=()=>{$('#logPanel').classList.remove('open');closeBag()};$('#startButton').onclick=()=>{started=true;logEvent('游戏开始：春季第 1 天');$('#welcome').classList.add('closed')};$('#restartButton').onclick=restartGame;$$('.quick').forEach(b=>b.onclick=()=>setMode(b.dataset.slot));$$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.toggle('active',x===b));$('#itemsPanel').classList.toggle('hidden',b.dataset.tab!=='items');$('#craftPanel').classList.toggle('hidden',b.dataset.tab!=='craft')});
async function setupUpdates(){if(!('serviceWorker'in navigator))return;let hadController=!!navigator.serviceWorker.controller,reg=await navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'});reg.update();setInterval(()=>reg.update(),60000);navigator.serviceWorker.addEventListener('controllerchange',()=>{if(hadController)$('#updateBanner').classList.remove('hidden');hadController=true});$('#reloadUpdate').onclick=()=>location.reload()}
document.documentElement.classList.add(LOCAL_AI_LAB?'local-ai-lab':'production');window.addEventListener('resize',resize);resize();updateUI();if(LOCAL_AI_LAB){let oldChampion=JSON.parse(localStorage.getItem('island-ai-champion')||'null');if(oldChampion&&!Number.isFinite(oldChampion.strategy?.bedHealthBelow))localStorage.removeItem('island-ai-champion');renderHistory()}requestAnimationFrame(animate);window.addEventListener('load',setupUpdates);
