/* 本地真人教学 + 行为克隆。只把训练后的冠军权重写入 imitation-strategy.js。 */
const IAI=window.IMITATION_STRATEGY,IMITATION_DB='island-imitation-lab-v1',IMITATION_STORE='episodes',IMITATION_SEEDS=[0x1a11ce01,0x1a11ce02,0x1a11ce03,0x1a11ce04,0x1a11ce05,0x1a11ce06,0x1a11ce07,0x1a11ce08,0x1a11ce09,0x1a11ce0a];
let teaching=false,teachingSamples=[],imitationBatch=null,imitationTraining=false;
if(!Array.isArray(IAI.weights)||IAI.weights.length!==NEURAL_WEIGHT_COUNT)IAI.weights=initialNeuralWeights();
function imitationDb(){return new Promise((resolve,reject)=>{let req=indexedDB.open(IMITATION_DB,1);req.onupgradeneeded=()=>req.result.createObjectStore(IMITATION_STORE,{keyPath:'id',autoIncrement:true});req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function imitationEpisodes(){let db=await imitationDb();return new Promise((resolve,reject)=>{let req=db.transaction(IMITATION_STORE).objectStore(IMITATION_STORE).getAll();req.onsuccess=()=>resolve(req.result||[]);req.onerror=()=>reject(req.error)})}
async function storeTeachingEpisode(episode){let db=await imitationDb();return new Promise((resolve,reject)=>{let req=db.transaction(IMITATION_STORE,'readwrite').objectStore(IMITATION_STORE).add(episode);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function clearTeachingEpisodes(){let db=await imitationDb();return new Promise((resolve,reject)=>{let req=db.transaction(IMITATION_STORE,'readwrite').objectStore(IMITATION_STORE).clear();req.onsuccess=resolve;req.onerror=()=>reject(req.error)})}
async function resetTeachingDbForRules(){if(localStorage.getItem('island-imitation-db-reset-v10')!=='1')return;await new Promise((resolve,reject)=>{let req=indexedDB.deleteDatabase(IMITATION_DB);req.onsuccess=resolve;req.onblocked=resolve;req.onerror=()=>reject(req.error)});localStorage.removeItem('island-imitation-db-reset-v10')}
function actionIdentity(a){return`${a.type}:${a.recipe?.id||''}:${a.target?.x??''},${a.target?.y??''}:${a.enemy?.kind||''}`}
function imitationActions(){let actions=neuralActions(),dirs=[[1,0],[-1,0],[0,1],[0,-1]];for(let[dx,dy]of dirs){let x=p.x+dx,y=p.y+dy,s=structures.find(v=>v.x===x&&v.y===y&&v.type!=='bridge');if(s&&UPGRADEABLE.has(s.type)&&canUpgrade(s.type,s))actions.push({type:'use',name:`升级${defs[s.type]?.[0]||s.type}`,target:{x,y},dx,dy,run:()=>upgradeItem(s.type,s)});if(s)actions.push({type:'use',name:`拆除${defs[s.type]?.[0]||s.type}`,target:{x,y},dx,dy,run:()=>dismantle(s)})}if(inv.berry)actions.push({type:'craft',name:'制作种子',recipe:{id:'seed',cost:{berry:1}},run:makeBerrySeeds});return actions}
function recordHumanChoice(match,label){if(!teaching||aiOn||batchLeft||!started||p.health<=0)return;let actions=imitationActions(),chosen=actions.findIndex(match);if(chosen<0)return;let vectors=actions.map(neuralVector),choice=actions[chosen],previous=neuralLastType;teachingSamples.push({vectors,chosen,label:label||choice.name,day,health:Math.round(p.health),hunger:Math.round(p.hunger)});neuralRepeatCount=choice.type===previous?neuralRepeatCount+1:0;neuralLastType=choice.type;neuralLastHealth=p.health;neuralLastHunger=p.hunger;neuralLastX=p.x;neuralLastY=p.y;updateTeachingButton()}
function recordBy(type,details={}){recordHumanChoice(a=>a.type===type&&(!details.id||a.recipe?.id===details.id)&&(!details.target||a.target?.x===details.target.x&&a.target?.y===details.target.y),details.label)}
function wrapHumanAction(name,matcher){let original=window[name]||eval(name);let wrapped=function(...args){matcher(...args);return original.apply(this,args)};try{eval(`${name}=wrapped`)}catch{}return wrapped}
const imitationPickup=pickup;pickup=function(a){recordBy('gather',{target:{x:a.x,y:a.y}});return imitationPickup(a)};
const imitationAttack=attack;attack=function(e){recordBy('attack',{target:{x:e.x,y:e.y}});return imitationAttack(e)};
const imitationEat=eat;eat=function(type){recordHumanChoice(a=>a.type==='eat'&&(type==='meal'?a.food>.2:a.food<=.2),`吃${defs[type]?.[0]||type}`);return imitationEat(type)};
const imitationCraft=craft;craft=function(id){recordBy('craft',{id});return imitationCraft(id)};
const imitationCommitPlace=commitPlace;commitPlace=function(type,x,y,bridge){recordBy('place',{id:type,target:{x,y}});return imitationCommitPlace(type,x,y,bridge)};
const imitationSleep=sleep;sleep=function(){if(sleepingUntil<=performance.now())recordHumanChoice(a=>a.type==='use'&&a.name.includes('床'),'使用床');return imitationSleep()};
const imitationCook=cook;cook=function(){recordHumanChoice(a=>a.type==='use'&&a.name==='烹饪','烹饪');return imitationCook()};
const imitationFish=fish;fish=function(...args){if(!fishingInProgress)recordHumanChoice(a=>a.type==='fish','钓鱼');return imitationFish(...args)};
const imitationFarmAction=farmAction;farmAction=function(plot){recordBy('use',{target:{x:plot.x,y:plot.y},label:'操作农田'});return imitationFarmAction(plot)};
const imitationMakeSeeds=makeBerrySeeds;makeBerrySeeds=function(){recordHumanChoice(a=>a.type==='craft'&&a.recipe?.id==='seed','制作种子');return imitationMakeSeeds()};
const imitationUpgrade=upgradeItem;upgradeItem=function(type,item){if(item)recordHumanChoice(a=>a.type==='use'&&a.target?.x===item.x&&a.target?.y===item.y&&a.name.startsWith('升级'),`升级${type}`);return imitationUpgrade(type,item)};
const imitationRepairWall=repairWall;repairWall=function(item){recordHumanChoice(a=>a.type==='use'&&a.target?.x===item.x&&a.target?.y===item.y&&a.name.startsWith('修复'),`修复${item.type}`);return imitationRepairWall(item)};
const imitationDismantle=dismantle;dismantle=function(item){recordHumanChoice(a=>a.type==='use'&&a.target?.x===item.x&&a.target?.y===item.y&&a.name.startsWith('拆除'),`拆除${item.type}`);return imitationDismantle(item)};
canvas.addEventListener('pointerup',()=>{if(!teaching||aiOn||!started)return;setTimeout(()=>{let next=p.path[0];if(!next)return;recordHumanChoice(a=>a.type==='move'&&a.target?.x===next.x&&a.target?.y===next.y,'移动')},0)});
function updateTeachingButton(){let b=$('#teachButton');b.classList.toggle('on',teaching);b.querySelector('small').textContent=teaching?`${teachingSamples.length}步`:'关闭'}
function toggleTeaching(){if(aiOn||batchLeft)return toast('请先关闭自动玩家再开启教学');teaching=!teaching;teachingSamples=[];updateTeachingButton();toast(teaching?'教学模式开启：本局真人决策会保存在本机':'教学模式关闭：本局未完成的记录已丢弃')}
async function finishTeachingEpisode(success){if(!teaching||!teachingSamples.length)return;let episode={createdAt:new Date().toISOString(),gameRulesVersion:GAME_RULES_VERSION,day,cause:success?'survived':deathCause(),success,samples:teachingSamples};await storeTeachingEpisode(episode);teachingSamples=[];teaching=false;updateTeachingButton();await renderImitationSummary();toast(`教学局已保存：第 ${day} 天 · ${episode.cause}`)}
async function renderImitationSummary(){if(!LOCAL_AI_LAB)return;let episodes=await imitationEpisodes(),samples=episodes.reduce((n,e)=>n+e.samples.length,0),max=episodes.length?Math.max(...episodes.map(e=>e.day)):0,causes={};episodes.forEach(e=>causes[e.cause]=(causes[e.cause]||0)+1);$('#imitationDatasetSummary').textContent=`${episodes.length} 局 · ${samples} 个有效决策 · 最长 ${max} 天${episodes.length?` · 死因 ${Object.entries(causes).map(([k,v])=>`${k} ${v}`).join(' / ')}`:''}`}
function imitationScore(action){return netForward(neuralVector(action),IAI.weights).value}
function imitationAiStep(){if(p.path.length||p.health<=0||strandedByTide()||pendingPlacement||performance.now()<aiPresentationUntil)return;let actions=imitationActions(),choice=actions.sort((a,b)=>imitationScore(b)-imitationScore(a))[0];if(!choice)return;if(!batchLeft)logEvent(`模仿AI：${choice.name}（模仿分 ${imitationScore(choice).toFixed(2)}）`,'ai');choice.run()}
const imitationBaseAiStep=aiStep;aiStep=function(){return aiController==='imitation'?imitationAiStep():imitationBaseAiStep()};
const imitationBaseUpdateButton=updateAIButton;updateAIButton=function(){imitationBaseUpdateButton();let b=$('#imitationAiButton');b.classList.toggle('on',aiOn&&aiController==='imitation');b.querySelector('small').textContent=aiOn&&aiController==='imitation'?'运行中':'关闭'};
function toggleImitationAI(){if(!IAI.trained&&!localStorage.getItem('island-imitation-latest'))return toast('模仿 AI 还没有学习，请先完成教学和训练');if(aiOn&&aiController==='imitation')aiOn=false;else{aiController='imitation';aiOn=true}updateAIButton();toast(aiOn?'模仿 AI 已接管':'模仿 AI 已关闭')}
function imitationAccuracy(samples,weights){if(!samples.length)return 0;let correct=0;for(let s of samples){let scores=s.vectors.map(v=>netForward(v,weights).value),best=scores.indexOf(Math.max(...scores));if(best===s.chosen)correct++}return correct/samples.length}
async function trainImitation(){if(imitationTraining||batchLeft)return;let episodes=(await imitationEpisodes()).filter(e=>e.gameRulesVersion===GAME_RULES_VERSION);if(!episodes.length)return alert('还没有完整教学局。请开启“教 AI”并玩到本局结束。');let samples=episodes.flatMap(e=>e.samples.map(s=>({...s,weight:.6+Math.min(2,e.day/7)}))).filter(s=>s.vectors?.length>1&&s.chosen<s.vectors.length);if(samples.length<20)return alert(`目前只有 ${samples.length} 个有效决策，至少需要 20 个。`);imitationTraining=true;let epochs=Number($('#imitationEpochInput').value),rate=Number($('#imitationRateInput').value)/1000,split=Math.max(1,Math.floor(samples.length*.85)),train=samples.slice(0,split),valid=samples.slice(split),latestWeights=JSON.parse(localStorage.getItem('island-imitation-latest')||'null')?.weights,weights=latestWeights?.length===NEURAL_WEIGHT_COUNT?[...latestWeights]:[...IAI.weights];$('#imitationTrainingStatus').textContent=`正在学习 ${samples.length} 个真人决策…`;for(let epoch=0;epoch<epochs;epoch++){for(let i=train.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[train[i],train[j]]=[train[j],train[i]]}let loss=0;for(let s of train){let caches=s.vectors.map(v=>netForward(v,weights)),prob=softmax(caches.map(c=>c.value)),g=Array(NEURAL_WEIGHT_COUNT).fill(0);loss-=Math.log(Math.max(1e-8,prob[s.chosen]));for(let j=0;j<caches.length;j++)addNetGradient(caches[j],weights,s.weight*((j===s.chosen?1:0)-prob[j]),g);let scale=rate/Math.max(1,Math.sqrt(g.reduce((n,v)=>n+v*v,0)));for(let i=0;i<weights.length;i++)weights[i]=Math.max(-6,Math.min(6,weights[i]+g[i]*scale))}let acc=imitationAccuracy(valid.length?valid:train,weights);$('#imitationTrainingStatus').textContent=`第 ${epoch+1}/${epochs} 轮 · Loss ${(loss/train.length).toFixed(3)} · 验证准确率 ${(acc*100).toFixed(1)}%`;await new Promise(requestAnimationFrame)}IAI.weights=weights;IAI.trained=true;IAI.requiresTraining=false;let accuracy=imitationAccuracy(valid.length?valid:train,weights),latest={weights,episodes:episodes.length,samples:samples.length,accuracy,trainedAt:new Date().toISOString()};localStorage.setItem('island-imitation-latest',JSON.stringify(latest));imitationTraining=false;$('#imitationTrainingStatus').textContent=`学习完成 · ${samples.length} 个决策 · 验证准确率 ${(accuracy*100).toFixed(1)}% · 请测试 10 局决定是否晋升冠军`}
async function persistImitationChampion(avg){let previous=JSON.parse(localStorage.getItem('island-imitation-champion')||'{}');if(Number(previous.avg||0)>=avg)return false;let parts=(IAI.version||'1.0.0').split('.').map(Number);parts[2]++;let latest=JSON.parse(localStorage.getItem('island-imitation-latest')||'{}'),strategy={...IAI,version:parts.join('.'),gameRulesVersion:GAME_RULES_VERSION,trained:true,requiresTraining:false,averageDays:avg,weights:[...IAI.weights],trainingSummary:{averageDays:avg,episodes:latest.episodes||0,samples:latest.samples||0,validationAccuracy:latest.accuracy||0,trainedAt:new Date().toISOString()}},res=await fetch('/__imitation_strategy',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(strategy)}),data=await res.json();if(!res.ok)throw new Error(data.error||'模仿冠军写入失败');Object.assign(IAI,data.strategy||strategy);localStorage.setItem('island-imitation-champion',JSON.stringify({avg,weights:[...IAI.weights],version:IAI.version,benchmark:'imitation-fixed-v1'}));return true}
function startImitationTest(){if(!LOCAL_AI_LAB||batchLeft||evolution||ppoTraining)return;let latest=JSON.parse(localStorage.getItem('island-imitation-latest')||'null');if(latest?.weights?.length===NEURAL_WEIGHT_COUNT)IAI.weights=[...latest.weights];else if(!IAI.trained)return alert('请先让模仿 AI 学习教学数据。');imitationBatch={runs:[],index:0};batchLeft=10;aiController='imitation';BATCH_SPEED=160;document.body.classList.add('batch-running');$('#batchRunResults').innerHTML='<small>等待第 1 局固定评测…</small>';$('#batchProgressTitle').textContent='模仿 AI · 10 局固定种子评测';$('#batchProgressExplain').textContent='只有平均成绩超过旧冠军才会写入线上权重文件';window.IMITATION_EVAL_SEED=IMITATION_SEEDS[0];resetRun()}
function finishImitationRun(success){if(runEnding)return;runEnding=true;started=false;let record={day,cause:success?'survived':deathCause()};imitationBatch.runs.push(record);imitationBatch.index++;batchLeft--;$('#batchRunResults').insertAdjacentHTML('beforeend',`<p><span>固定评测 ${imitationBatch.index}/10</span><span><b>${day} 天</b> · ${record.cause}</span></p>`);if(batchLeft){window.IMITATION_EVAL_SEED=IMITATION_SEEDS[imitationBatch.index];return void setTimeout(resetRun,10)}let runs=imitationBatch.runs,avg=runs.reduce((n,r)=>n+r.day,0)/runs.length,old=Number(JSON.parse(localStorage.getItem('island-imitation-champion')||'{}').avg||IAI.averageDays||0),improved=avg>old+.01;imitationBatch=null;window.IMITATION_EVAL_SEED=null;batchLeft=0;aiOn=false;document.body.classList.remove('batch-running');updateAIButton();$('#logPanel').classList.add('open');$('#scrim').classList.add('open');$('#strategyReview').classList.remove('hidden');$('#strategyReviewTitle').textContent='模仿 AI 固定评测';$('#resultTable').innerHTML=`<p class="batch-result-line">👤 平均 <b>${avg.toFixed(1)}</b> 天 · 最短 ${Math.min(...runs.map(r=>r.day))} · 最长 ${Math.max(...runs.map(r=>r.day))} · ${improved?'超过旧冠军':'保留旧冠军 '+old.toFixed(1)}</p>`;$('#strategyDiff').innerHTML='<small>教学数据仍只在本机；只有通过固定评测的601个权重会写入策略文件。</small>';$('#strategyStatus').textContent=improved?'正在写入模仿冠军…':'本轮没有覆盖正式冠军。';if(improved)persistImitationChampion(avg).then(()=>$('#strategyStatus').textContent=`模仿冠军 ${avg.toFixed(1)} 天已写入 imitation-strategy.js`).catch(e=>$('#strategyStatus').textContent=`写入失败：${e.message}`)}
const imitationBaseFinish=finishRun;finishRun=function(success){if(imitationBatch)return finishImitationRun(success);if(teaching)finishTeachingEpisode(success).catch(e=>console.error(e));return imitationBaseFinish(success)};
async function resetImitation(){if(batchLeft||imitationTraining)return alert('请先结束当前训练或测试。');if(!confirm('确定重置模仿 AI 吗？\n教学局、训练检查点和模仿冠军都会删除；其他 AI 不受影响。'))return;await clearTeachingEpisodes();localStorage.removeItem('island-imitation-latest');localStorage.removeItem('island-imitation-champion');let res=await fetch('/__imitation_strategy_reset',{method:'POST'});if(!res.ok)return alert('重置权重文件失败，请使用 node server.js 打开。');location.reload()}
$('#teachButton').onclick=toggleTeaching;$('#imitationAiButton').onclick=toggleImitationAI;$('#trainImitationButton').onclick=trainImitation;$('#testImitationButton').onclick=startImitationTest;$('#resetImitationButton').onclick=resetImitation;$('#imitationEpochInput').oninput=e=>$('#imitationEpochValue').textContent=e.target.value;$('#imitationRateInput').oninput=e=>$('#imitationRateValue').textContent=(Number(e.target.value)/1000).toFixed(3);updateTeachingButton();resetTeachingDbForRules().then(renderImitationSummary).catch(()=>$('#imitationDatasetSummary').textContent='无法读取 IndexedDB 教学数据');
