const http=require('http'),fs=require('fs'),path=require('path');
const ROOT=__dirname,PORT=Number(process.env.PORT||4173),MIME={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.webmanifest':'application/manifest+json','.png':'image/png'};
const STRATEGY_DEFAULTS={version:'1.7.0',description:'开放动作效用AI',eatMealBelow:62,eatBerryBelow:42,fishBelow:70,trapThreatDistance:5,testSpeed:4,buildShelterBeforeBase:false,growthValueWeight:1.5,bedHealthBelow:75,wallLevel2Day:5,wallLevel3Day:10,weapon2Day:5,weapon3Day:10,survivalWeight:2.2,hungerWeight:1.8,threatWeight:2,tideWeight:1.7,buildingWeight:1.35,resourceWeight:1,repairWeight:1.5,futureWeight:1.2,explorationWeight:.7,farmingWeight:1.4,storageWeight:1.1,clothingWeight:1.3,craftPriority:['kitchen','trap','fence','door','fridge','bed','shelter','rod','strongShelter','bridge','boat','hoe','wateringCan','farmPlot','storage']};
const FEATURE_DEFAULTS={urgency:38,hunger:32,health:34,threat:36,tide:30,weather:24,future:16,yield:12,distance:-2.2},ACTION_DEFAULTS={attack:42,flee:18,eatMeal:20,eatBerry:12,cook:18,sleep:14,repairBridge:12,harvest:24,water:16,sow:14,makeSeeds:8,evacuate:28,upgradeWall:12,gather:16,fish:10};
function send(res,status,body,type='application/json'){res.writeHead(status,{'Content-Type':type,'Cache-Control':'no-store'});res.end(body)}
function normalizeStrategy(s){let out={...STRATEGY_DEFAULTS,...s};out.craftPriority=Array.isArray(s?.craftPriority)?s.craftPriority.filter(x=>typeof x==='string'):[...STRATEGY_DEFAULTS.craftPriority];out.featureWeights={...FEATURE_DEFAULTS,...(s?.featureWeights||{})};out.actionWeights={...ACTION_DEFAULTS,...(s?.actionWeights||{})};return out}
function validStrategy(s){return s&&/^\d+\.\d+\.\d+$/.test(s.version)&&[s.eatMealBelow,s.eatBerryBelow,s.fishBelow,s.trapThreatDistance,s.testSpeed,s.growthValueWeight,s.bedHealthBelow,s.wallLevel2Day,s.wallLevel3Day,s.weapon2Day,s.weapon3Day,s.survivalWeight,s.hungerWeight,s.threatWeight,s.tideWeight,s.buildingWeight,s.resourceWeight,s.repairWeight,s.futureWeight,s.explorationWeight,s.farmingWeight,s.storageWeight,s.clothingWeight].every(Number.isFinite)&&Object.values(s.featureWeights||{}).every(Number.isFinite)&&Object.values(s.actionWeights||{}).every(Number.isFinite)&&Array.isArray(s.craftPriority)&&s.craftPriority.length&&s.craftPriority.every(x=>typeof x==='string')}
function strategySource(s){return `/**\n * 正式 AI 策略配置。\n * 本地回归测试确认新参数更好后，只修改这个文件并发布。\n */\nwindow.AI_STRATEGY=${JSON.stringify(s,null,2)};\n`}
const server=http.createServer((req,res)=>{
  if(req.method==='POST'&&req.url==='/__ai_strategy'){let body='';req.on('data',c=>{body+=c;if(body.length>20000)req.destroy()});req.on('end',()=>{try{let strategy=normalizeStrategy(JSON.parse(body));if(!validStrategy(strategy))return send(res,400,JSON.stringify({ok:false,error:'策略格式无效，请检查版本号和参数类型'}));fs.writeFileSync(path.join(ROOT,'ai-strategy.js'),strategySource(strategy));send(res,200,JSON.stringify({ok:true,version:strategy.version,strategy}))}catch(e){send(res,400,JSON.stringify({ok:false,error:e.message}))}});return}
  let url=new URL(req.url,'http://localhost'),file=path.join(ROOT,url.pathname==='/'?'index.html':url.pathname);if(!file.startsWith(ROOT))return send(res,403,'Forbidden','text/plain');fs.stat(file,(err,st)=>{if(err||!st.isFile())return send(res,404,'Not found','text/plain');res.writeHead(200,{'Content-Type':MIME[path.extname(file)]||'application/octet-stream','Cache-Control':'no-store'});fs.createReadStream(file).pipe(res)})
});
server.listen(PORT,'0.0.0.0',()=>console.log(`Local AI lab: http://localhost:${PORT}`));
