const http=require('http'),fs=require('fs'),path=require('path');
const ROOT=__dirname,PORT=Number(process.env.PORT||4173),MIME={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.webmanifest':'application/manifest+json','.png':'image/png'};
const STRATEGY_DEFAULTS={version:'3.0.0',description:'带时间规划、耐久陷阱与濒死响应的开放动作效用AI',policySchema:3,gameRulesVersion:'critical-survival-v8',requiresRetraining:true,trained:false,eatMealBelow:62,eatBerryBelow:42,fishBelow:70,trapThreatDistance:5,testSpeed:4,growthValueWeight:1.5,bedHealthBelow:75,wallLevel2Day:5,wallLevel3Day:10,weapon2Day:5,weapon3Day:10,survivalWeight:2.2,hungerWeight:1.8,threatWeight:2,tideWeight:1.7,buildingWeight:1.35,resourceWeight:1,repairWeight:1.5,futureWeight:1.2,explorationWeight:.7,farmingWeight:1.4,storageWeight:1.1,clothingWeight:1.3,craftPriority:['kitchen','trap','fence','door','fridge','bed','rainCoat','warmCoat','coolClothes','spear','strongSpear','hunterSpear','rod','bridge','boat','hoe','wateringCan','farmPlot','storage']};
const FEATURE_DEFAULTS={urgency:38,hunger:32,health:34,criticalHealth:46,dying:68,threat:36,tide:30,weather:24,future:16,yield:12,distance:-2.2,seasonProgress:10,seasonLead:18,tideLead:20,growthPotential:14,foodReserve:10,clothingGap:22,durabilityRisk:18,seasonDanger:16,worldProgress:16,enemyTier:22,trapDurability:18,trapSaturation:-18},ACTION_DEFAULTS={attack:42,flee:18,eatMeal:20,eatBerry:12,cook:18,sleep:14,repairBridge:12,harvest:24,water:16,sow:14,makeSeeds:8,evacuate:28,seekHome:24,upgradeWall:12,upgradeItem:9,upgradeTrap:14,gather:16,fish:10,waitGrowth:4,prepareClothing:12};
const REQUIRED_FEATURES=Object.keys(FEATURE_DEFAULTS),REQUIRED_ACTIONS=Object.keys(ACTION_DEFAULTS);
const NEURAL_DEFAULTS={version:'1.0.0',gameRulesVersion:'critical-survival-v8',architecture:{input:48,hidden:12},trained:false,requiresRetraining:true,averageDays:0,weights:[]},NEURAL_WEIGHT_COUNT=601;
function send(res,status,body,type='application/json'){res.writeHead(status,{'Content-Type':type,'Cache-Control':'no-store'});res.end(body)}
function normalizeStrategy(s){let out={...STRATEGY_DEFAULTS,...s},allowed=new Set(STRATEGY_DEFAULTS.craftPriority);delete out.buildShelterBeforeBase;out.craftPriority=Array.isArray(s?.craftPriority)?s.craftPriority.filter(x=>allowed.has(x)):[...STRATEGY_DEFAULTS.craftPriority];out.featureWeights={...FEATURE_DEFAULTS,...(s?.featureWeights||{})};out.actionWeights={...ACTION_DEFAULTS,...(s?.actionWeights||{})};delete out.actionWeights['craft:shelter'];delete out.actionWeights['craft:strongShelter'];return out}
function validStrategy(s){return s&&s.policySchema===3&&/^\d+\.\d+\.\d+$/.test(s.version)&&[s.eatMealBelow,s.eatBerryBelow,s.fishBelow,s.trapThreatDistance,s.testSpeed,s.growthValueWeight,s.bedHealthBelow,s.wallLevel2Day,s.wallLevel3Day,s.weapon2Day,s.weapon3Day,s.survivalWeight,s.hungerWeight,s.threatWeight,s.tideWeight,s.buildingWeight,s.resourceWeight,s.repairWeight,s.futureWeight,s.explorationWeight,s.farmingWeight,s.storageWeight,s.clothingWeight].every(Number.isFinite)&&REQUIRED_FEATURES.every(k=>Number.isFinite(s.featureWeights?.[k]))&&REQUIRED_ACTIONS.every(k=>Number.isFinite(s.actionWeights?.[k]))&&Object.values(s.featureWeights||{}).every(Number.isFinite)&&Object.values(s.actionWeights||{}).every(Number.isFinite)&&Array.isArray(s.craftPriority)&&s.craftPriority.length&&s.craftPriority.every(x=>typeof x==='string')}
function strategySource(s){return `/**\n * 正式开放AI策略（schema v${s.policySchema}）。\n * 本地自动进化写入全部状态权重与动作权重；commit并push后由GitHub Pages发布。\n */\nwindow.AI_STRATEGY=${JSON.stringify(s,null,2)};\n`}
function normalizeNeuralStrategy(s={}){return{...NEURAL_DEFAULTS,...s,architecture:{...NEURAL_DEFAULTS.architecture,...(s.architecture||{})},weights:Array.isArray(s.weights)?s.weights.map(Number):[]}}
function validNeuralStrategy(s){return s&&/^\d+\.\d+\.\d+$/.test(s.version)&&s.gameRulesVersion===NEURAL_DEFAULTS.gameRulesVersion&&s.architecture?.input===48&&s.architecture?.hidden===12&&s.weights.length===NEURAL_WEIGHT_COUNT&&s.weights.every(Number.isFinite)}
function neuralStrategySource(s){return `/** 神经网络AI冠军：由本地训练写入，push后同步线上。 */\nwindow.NEURAL_STRATEGY=${JSON.stringify(s,null,2)};\n`}
const server=http.createServer((req,res)=>{
  if(req.method==='POST'&&req.url==='/__neural_strategy_reset'){try{let strategy=normalizeNeuralStrategy();fs.writeFileSync(path.join(ROOT,'neural-strategy.js'),neuralStrategySource(strategy));send(res,200,JSON.stringify({ok:true,strategy}))}catch(e){send(res,500,JSON.stringify({ok:false,error:e.message}))}return}
  if(req.method==='POST'&&req.url==='/__neural_strategy'){let body='';req.on('data',c=>{body+=c;if(body.length>100000)req.destroy()});req.on('end',()=>{try{let strategy=normalizeNeuralStrategy(JSON.parse(body));if(!validNeuralStrategy(strategy))return send(res,400,JSON.stringify({ok:false,error:'神经策略格式无效：必须是 48×12 网络的 601 个有限权重'}));fs.writeFileSync(path.join(ROOT,'neural-strategy.js'),neuralStrategySource(strategy));send(res,200,JSON.stringify({ok:true,version:strategy.version,weightCount:strategy.weights.length,strategy}))}catch(e){send(res,400,JSON.stringify({ok:false,error:e.message}))}});return}
  if(req.method==='POST'&&req.url==='/__ai_strategy_reset'){try{let strategy=normalizeStrategy({version:'3.0.0',description:'AI训练已重置：从默认开放权重重新开始',gameRulesVersion:STRATEGY_DEFAULTS.gameRulesVersion,policySchema:STRATEGY_DEFAULTS.policySchema,requiresRetraining:true,trained:false});delete strategy.trainingSummary;fs.writeFileSync(path.join(ROOT,'ai-strategy.js'),strategySource(strategy));send(res,200,JSON.stringify({ok:true,strategy}))}catch(e){send(res,500,JSON.stringify({ok:false,error:e.message}))}return}
  if(req.method==='POST'&&req.url==='/__ai_strategy'){let body='';req.on('data',c=>{body+=c;if(body.length>20000)req.destroy()});req.on('end',()=>{try{let strategy=normalizeStrategy(JSON.parse(body));if(!validStrategy(strategy))return send(res,400,JSON.stringify({ok:false,error:'开放策略格式无效：缺少schema、状态权重或动作权重'}));fs.writeFileSync(path.join(ROOT,'ai-strategy.js'),strategySource(strategy));send(res,200,JSON.stringify({ok:true,version:strategy.version,featureCount:Object.keys(strategy.featureWeights).length,actionCount:Object.keys(strategy.actionWeights).length,trained:strategy.trained===true,strategy}))}catch(e){send(res,400,JSON.stringify({ok:false,error:e.message}))}});return}
  let url=new URL(req.url,'http://localhost'),file=path.join(ROOT,url.pathname==='/'?'index.html':url.pathname);if(!file.startsWith(ROOT))return send(res,403,'Forbidden','text/plain');fs.stat(file,(err,st)=>{if(err||!st.isFile())return send(res,404,'Not found','text/plain');res.writeHead(200,{'Content-Type':MIME[path.extname(file)]||'application/octet-stream','Cache-Control':'no-store'});fs.createReadStream(file).pipe(res)})
});
server.listen(PORT,'0.0.0.0',()=>console.log(`Local AI lab: http://localhost:${PORT}`));
